// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/api/rpc/account/account.proto
// DO NOT EDIT!

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/account/account.proto

It has these top-level messages:
	User
	SignUpRequest
	VerificationRequest
	LogInRequest
	PasswordResetRequest
	PasswordSetRequest
	PasswordChangeRequest
	ForgotLoginRequest
	GetUserRequest
	GetUserReply
	ListUsersRequest
	ListUsersReply
	CreateOrganizationRequest
	DeleteOrganizationRequest
	AddUserToOrganizationRequest
	RemoveUserFromOrganizationRequest
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Users
type User struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	CreateDt int64  `protobuf:"varint,3,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

type SignUpRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *SignUpRequest) Reset()                    { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string            { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()               {}
func (*SignUpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SignUpRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type VerificationRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *VerificationRequest) Reset()                    { *m = VerificationRequest{} }
func (m *VerificationRequest) String() string            { return proto.CompactTextString(m) }
func (*VerificationRequest) ProtoMessage()               {}
func (*VerificationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VerificationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogInRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LogInRequest) Reset()                    { *m = LogInRequest{} }
func (m *LogInRequest) String() string            { return proto.CompactTextString(m) }
func (*LogInRequest) ProtoMessage()               {}
func (*LogInRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LogInRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PasswordResetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *PasswordResetRequest) Reset()                    { *m = PasswordResetRequest{} }
func (m *PasswordResetRequest) String() string            { return proto.CompactTextString(m) }
func (*PasswordResetRequest) ProtoMessage()               {}
func (*PasswordResetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PasswordResetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PasswordSetRequest struct {
	Token    string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *PasswordSetRequest) Reset()                    { *m = PasswordSetRequest{} }
func (m *PasswordSetRequest) String() string            { return proto.CompactTextString(m) }
func (*PasswordSetRequest) ProtoMessage()               {}
func (*PasswordSetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PasswordSetRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PasswordSetRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type PasswordChangeRequest struct {
	ExistingPassword string `protobuf:"bytes,1,opt,name=existingPassword" json:"existingPassword,omitempty"`
	NewPassword      string `protobuf:"bytes,2,opt,name=newPassword" json:"newPassword,omitempty"`
}

func (m *PasswordChangeRequest) Reset()                    { *m = PasswordChangeRequest{} }
func (m *PasswordChangeRequest) String() string            { return proto.CompactTextString(m) }
func (*PasswordChangeRequest) ProtoMessage()               {}
func (*PasswordChangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PasswordChangeRequest) GetExistingPassword() string {
	if m != nil {
		return m.ExistingPassword
	}
	return ""
}

func (m *PasswordChangeRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ForgotLoginRequest struct {
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
}

func (m *ForgotLoginRequest) Reset()                    { *m = ForgotLoginRequest{} }
func (m *ForgotLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*ForgotLoginRequest) ProtoMessage()               {}
func (*ForgotLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ForgotLoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUserReply struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserReply) Reset()                    { *m = GetUserReply{} }
func (m *GetUserReply) String() string            { return proto.CompactTextString(m) }
func (*GetUserReply) ProtoMessage()               {}
func (*GetUserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetUserReply) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ListUsersRequest struct {
}

func (m *ListUsersRequest) Reset()                    { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()               {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type ListUsersReply struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *ListUsersReply) Reset()                    { *m = ListUsersReply{} }
func (m *ListUsersReply) String() string            { return proto.CompactTextString(m) }
func (*ListUsersReply) ProtoMessage()               {}
func (*ListUsersReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ListUsersReply) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

// Organizations
type CreateOrganizationRequest struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
}

func (m *CreateOrganizationRequest) Reset()                    { *m = CreateOrganizationRequest{} }
func (m *CreateOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateOrganizationRequest) ProtoMessage()               {}
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CreateOrganizationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOrganizationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type DeleteOrganizationRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *DeleteOrganizationRequest) Reset()                    { *m = DeleteOrganizationRequest{} }
func (m *DeleteOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteOrganizationRequest) ProtoMessage()               {}
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *DeleteOrganizationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddUserToOrganizationRequest struct {
	OrganizationName string `protobuf:"bytes,1,opt,name=organization_name,json=organizationName" json:"organization_name,omitempty"`
	UserName         string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *AddUserToOrganizationRequest) Reset()                    { *m = AddUserToOrganizationRequest{} }
func (m *AddUserToOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*AddUserToOrganizationRequest) ProtoMessage()               {}
func (*AddUserToOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *AddUserToOrganizationRequest) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *AddUserToOrganizationRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type RemoveUserFromOrganizationRequest struct {
	OrganizationName string `protobuf:"bytes,1,opt,name=organization_name,json=organizationName" json:"organization_name,omitempty"`
	UserName         string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *RemoveUserFromOrganizationRequest) Reset()         { *m = RemoveUserFromOrganizationRequest{} }
func (m *RemoveUserFromOrganizationRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveUserFromOrganizationRequest) ProtoMessage()    {}
func (*RemoveUserFromOrganizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15}
}

func (m *RemoveUserFromOrganizationRequest) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *RemoveUserFromOrganizationRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "account.User")
	proto.RegisterType((*SignUpRequest)(nil), "account.SignUpRequest")
	proto.RegisterType((*VerificationRequest)(nil), "account.VerificationRequest")
	proto.RegisterType((*LogInRequest)(nil), "account.LogInRequest")
	proto.RegisterType((*PasswordResetRequest)(nil), "account.PasswordResetRequest")
	proto.RegisterType((*PasswordSetRequest)(nil), "account.PasswordSetRequest")
	proto.RegisterType((*PasswordChangeRequest)(nil), "account.PasswordChangeRequest")
	proto.RegisterType((*ForgotLoginRequest)(nil), "account.ForgotLoginRequest")
	proto.RegisterType((*GetUserRequest)(nil), "account.GetUserRequest")
	proto.RegisterType((*GetUserReply)(nil), "account.GetUserReply")
	proto.RegisterType((*ListUsersRequest)(nil), "account.ListUsersRequest")
	proto.RegisterType((*ListUsersReply)(nil), "account.ListUsersReply")
	proto.RegisterType((*CreateOrganizationRequest)(nil), "account.CreateOrganizationRequest")
	proto.RegisterType((*DeleteOrganizationRequest)(nil), "account.DeleteOrganizationRequest")
	proto.RegisterType((*AddUserToOrganizationRequest)(nil), "account.AddUserToOrganizationRequest")
	proto.RegisterType((*RemoveUserFromOrganizationRequest)(nil), "account.RemoveUserFromOrganizationRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Account service

type AccountClient interface {
	// Users
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Verify(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Login(ctx context.Context, in *LogInRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	PasswordReset(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	PasswordSet(ctx context.Context, in *PasswordSetRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	PasswordChange(ctx context.Context, in *PasswordChangeRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	ForgotLogin(ctx context.Context, in *ForgotLoginRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersReply, error)
	// Organizations
	CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	AddUserToOrganization(ctx context.Context, in *AddUserToOrganizationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	RemoveUserFromOrganization(ctx context.Context, in *RemoveUserFromOrganizationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	DeleteOrganization(ctx context.Context, in *DeleteOrganizationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/SignUp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Verify(ctx context.Context, in *VerificationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/Verify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) Login(ctx context.Context, in *LogInRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) PasswordReset(ctx context.Context, in *PasswordResetRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/PasswordReset", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) PasswordSet(ctx context.Context, in *PasswordSetRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/PasswordSet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) PasswordChange(ctx context.Context, in *PasswordChangeRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/PasswordChange", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ForgotLogin(ctx context.Context, in *ForgotLoginRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/ForgotLogin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserReply, error) {
	out := new(GetUserReply)
	err := grpc.Invoke(ctx, "/account.Account/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersReply, error) {
	out := new(ListUsersReply)
	err := grpc.Invoke(ctx, "/account.Account/ListUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/CreateOrganization", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) AddUserToOrganization(ctx context.Context, in *AddUserToOrganizationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/AddUserToOrganization", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) RemoveUserFromOrganization(ctx context.Context, in *RemoveUserFromOrganizationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/RemoveUserFromOrganization", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountClient) DeleteOrganization(ctx context.Context, in *DeleteOrganizationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/account.Account/DeleteOrganization", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountServer interface {
	// Users
	SignUp(context.Context, *SignUpRequest) (*google_protobuf1.Empty, error)
	Verify(context.Context, *VerificationRequest) (*google_protobuf1.Empty, error)
	Login(context.Context, *LogInRequest) (*google_protobuf1.Empty, error)
	PasswordReset(context.Context, *PasswordResetRequest) (*google_protobuf1.Empty, error)
	PasswordSet(context.Context, *PasswordSetRequest) (*google_protobuf1.Empty, error)
	PasswordChange(context.Context, *PasswordChangeRequest) (*google_protobuf1.Empty, error)
	ForgotLogin(context.Context, *ForgotLoginRequest) (*google_protobuf1.Empty, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserReply, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersReply, error)
	// Organizations
	CreateOrganization(context.Context, *CreateOrganizationRequest) (*google_protobuf1.Empty, error)
	AddUserToOrganization(context.Context, *AddUserToOrganizationRequest) (*google_protobuf1.Empty, error)
	RemoveUserFromOrganization(context.Context, *RemoveUserFromOrganizationRequest) (*google_protobuf1.Empty, error)
	DeleteOrganization(context.Context, *DeleteOrganizationRequest) (*google_protobuf1.Empty, error)
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Verify(ctx, req.(*VerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Login(ctx, req.(*LogInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_PasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).PasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/PasswordReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).PasswordReset(ctx, req.(*PasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_PasswordSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).PasswordSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/PasswordSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).PasswordSet(ctx, req.(*PasswordSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_PasswordChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).PasswordChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/PasswordChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).PasswordChange(ctx, req.(*PasswordChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_ForgotLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ForgotLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/ForgotLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ForgotLogin(ctx, req.(*ForgotLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_CreateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).CreateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/CreateOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).CreateOrganization(ctx, req.(*CreateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_AddUserToOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserToOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).AddUserToOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/AddUserToOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).AddUserToOrganization(ctx, req.(*AddUserToOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_RemoveUserFromOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserFromOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).RemoveUserFromOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/RemoveUserFromOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).RemoveUserFromOrganization(ctx, req.(*RemoveUserFromOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Account_DeleteOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).DeleteOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.Account/DeleteOrganization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).DeleteOrganization(ctx, req.(*DeleteOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _Account_SignUp_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Account_Verify_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Account_Login_Handler,
		},
		{
			MethodName: "PasswordReset",
			Handler:    _Account_PasswordReset_Handler,
		},
		{
			MethodName: "PasswordSet",
			Handler:    _Account_PasswordSet_Handler,
		},
		{
			MethodName: "PasswordChange",
			Handler:    _Account_PasswordChange_Handler,
		},
		{
			MethodName: "ForgotLogin",
			Handler:    _Account_ForgotLogin_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Account_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Account_ListUsers_Handler,
		},
		{
			MethodName: "CreateOrganization",
			Handler:    _Account_CreateOrganization_Handler,
		},
		{
			MethodName: "AddUserToOrganization",
			Handler:    _Account_AddUserToOrganization_Handler,
		},
		{
			MethodName: "RemoveUserFromOrganization",
			Handler:    _Account_RemoveUserFromOrganization_Handler,
		},
		{
			MethodName: "DeleteOrganization",
			Handler:    _Account_DeleteOrganization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/appcelerator/amp/api/rpc/account/account.proto",
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/account/account.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 869 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x95, 0xdd, 0x4e, 0xe3, 0x46,
	0x14, 0xc7, 0x65, 0x42, 0x80, 0x9c, 0x00, 0x0d, 0xd3, 0x04, 0x12, 0x27, 0xd0, 0x30, 0xb4, 0x12,
	0x0d, 0x52, 0x2c, 0x68, 0xab, 0x8a, 0xaa, 0x6a, 0x45, 0xf9, 0xa8, 0x2a, 0xd1, 0x16, 0x25, 0x4d,
	0x6f, 0x7a, 0x81, 0x4c, 0x32, 0x18, 0xab, 0xb6, 0xc7, 0xd8, 0x13, 0x68, 0x8a, 0x72, 0xb3, 0xaf,
	0xb0, 0x17, 0x2b, 0xed, 0xf5, 0xbe, 0xd1, 0xbe, 0xc2, 0x3e, 0xc8, 0x6a, 0xc6, 0x5f, 0x13, 0x1c,
	0x07, 0x76, 0xa5, 0xbd, 0x4a, 0x66, 0xce, 0xf1, 0xff, 0x77, 0x7c, 0xe6, 0xcc, 0xdf, 0x70, 0x68,
	0x98, 0xec, 0x66, 0x78, 0xd5, 0xee, 0x53, 0x5b, 0xd3, 0x5d, 0xb7, 0x4f, 0x2c, 0xe2, 0xe9, 0x8c,
	0x7a, 0x9a, 0x6e, 0xbb, 0x9a, 0xee, 0x9a, 0x9a, 0xe7, 0xf6, 0x35, 0xbd, 0xdf, 0xa7, 0x43, 0x87,
	0x45, 0xbf, 0x6d, 0xd7, 0xa3, 0x8c, 0xa2, 0xc5, 0x70, 0xa9, 0x36, 0x0c, 0x4a, 0x0d, 0x8b, 0x88,
	0x74, 0xdd, 0x71, 0x28, 0xd3, 0x99, 0x49, 0x1d, 0x3f, 0x48, 0x53, 0xeb, 0x61, 0x54, 0xac, 0xae,
	0x86, 0xd7, 0x1a, 0xb1, 0x5d, 0x36, 0x0a, 0x82, 0xf8, 0x77, 0x98, 0xef, 0xf9, 0xc4, 0x43, 0x08,
	0xe6, 0x1d, 0xdd, 0x26, 0x55, 0xa5, 0xa9, 0xec, 0x16, 0x3a, 0xe2, 0x3f, 0x2a, 0x43, 0x9e, 0xd8,
	0xba, 0x69, 0x55, 0xe7, 0xc4, 0x66, 0xb0, 0x40, 0x75, 0x28, 0xf4, 0x3d, 0xa2, 0x33, 0x72, 0x39,
	0x60, 0xd5, 0x5c, 0x53, 0xd9, 0xcd, 0x75, 0x96, 0x82, 0x8d, 0x13, 0x86, 0x7b, 0xb0, 0xd2, 0x35,
	0x0d, 0xa7, 0xe7, 0x76, 0xc8, 0xed, 0x90, 0xf8, 0x6c, 0xaa, 0xae, 0x0a, 0x4b, 0xae, 0xee, 0xfb,
	0xf7, 0xd4, 0x1b, 0x84, 0xd2, 0xf1, 0x3a, 0x61, 0xe6, 0x24, 0x26, 0xde, 0x83, 0xcf, 0xff, 0x26,
	0x9e, 0x79, 0x6d, 0xf6, 0xc5, 0x9b, 0x45, 0xe2, 0x65, 0xc8, 0x33, 0xfa, 0x2f, 0x71, 0x42, 0xf5,
	0x60, 0x81, 0x7f, 0x82, 0xe5, 0x73, 0x6a, 0xfc, 0xe6, 0x7c, 0x64, 0x09, 0xb8, 0x05, 0xe5, 0x8b,
	0xf0, 0x7f, 0x87, 0xf8, 0x84, 0xcd, 0xd0, 0xc1, 0x67, 0x80, 0xa2, 0xdc, 0x6e, 0x92, 0x39, 0xb5,
	0xae, 0x99, 0x4c, 0x02, 0x95, 0x48, 0xe7, 0xf8, 0x46, 0x77, 0x0c, 0x12, 0x49, 0xb5, 0xa0, 0x44,
	0xfe, 0x33, 0x7d, 0x66, 0x3a, 0x46, 0x94, 0x10, 0xaa, 0xa6, 0xf6, 0x51, 0x13, 0x8a, 0x0e, 0xb9,
	0xbf, 0x98, 0x64, 0xc8, 0x5b, 0xb8, 0x05, 0xe8, 0x8c, 0x7a, 0x06, 0x65, 0xe7, 0xd4, 0x30, 0xe5,
	0x36, 0x06, 0x3d, 0x57, 0xe4, 0x9e, 0x7f, 0x09, 0xab, 0xbf, 0x12, 0xc6, 0x87, 0x63, 0x56, 0x03,
	0xf6, 0x61, 0x39, 0xce, 0x72, 0xad, 0x11, 0xda, 0x86, 0xf9, 0xa1, 0x4f, 0x3c, 0x91, 0x53, 0x3c,
	0x58, 0x69, 0x47, 0x13, 0x2b, 0x32, 0x44, 0x08, 0x23, 0x28, 0x9d, 0x9b, 0xbe, 0x78, 0xc6, 0x0f,
	0xa5, 0xf1, 0x77, 0xb0, 0x2a, 0xed, 0x71, 0xa1, 0x1d, 0xc8, 0xf3, 0x6c, 0xbf, 0xaa, 0x34, 0x73,
	0x69, 0xa5, 0x20, 0x86, 0x4f, 0xa1, 0x76, 0x2c, 0x46, 0xef, 0x4f, 0xcf, 0xd0, 0x1d, 0xf3, 0xff,
	0x89, 0xe9, 0x78, 0xf6, 0x48, 0x63, 0x0d, 0x6a, 0x27, 0xc4, 0x22, 0xcf, 0x96, 0xc1, 0x37, 0xd0,
	0x38, 0x1a, 0x0c, 0x78, 0x25, 0x7f, 0xd1, 0x69, 0xcf, 0xec, 0xc1, 0x1a, 0x95, 0xb6, 0x2f, 0x25,
	0x81, 0x92, 0x1c, 0xf8, 0x83, 0xd7, 0x54, 0x87, 0x02, 0x7f, 0x9b, 0x20, 0x29, 0x1c, 0x0c, 0xbe,
	0xc1, 0x83, 0xd8, 0x86, 0xed, 0x0e, 0xb1, 0xe9, 0x1d, 0xe1, 0xb0, 0x33, 0x8f, 0xda, 0x9f, 0x14,
	0x77, 0xf0, 0xba, 0x08, 0x8b, 0x47, 0x41, 0xa3, 0x51, 0x0f, 0x16, 0x82, 0xbb, 0x8c, 0xd6, 0xe3,
	0xe6, 0x4f, 0x5c, 0x6e, 0x75, 0xbd, 0x1d, 0x58, 0x4b, 0x3b, 0xb2, 0x96, 0xf6, 0x29, 0xb7, 0x16,
	0x5c, 0x7f, 0xf1, 0xf6, 0xdd, 0xcb, 0xb9, 0x0a, 0x2e, 0x69, 0x77, 0xfb, 0x9a, 0x38, 0x29, 0xcd,
	0x37, 0x0d, 0x67, 0xe8, 0xfe, 0xa0, 0xb4, 0xd0, 0x3f, 0xb0, 0x20, 0xee, 0xf2, 0x08, 0x35, 0x62,
	0xd9, 0x29, 0x97, 0xfb, 0x43, 0xc4, 0xef, 0x84, 0x1e, 0x17, 0xef, 0x40, 0x5e, 0x8c, 0x36, 0xaa,
	0xc4, 0xda, 0xb2, 0x17, 0x64, 0x8a, 0xaa, 0x42, 0xb4, 0x8c, 0x3f, 0x4b, 0x44, 0x2d, 0xae, 0xc3,
	0x35, 0x6f, 0x61, 0x65, 0xc2, 0x0f, 0xd0, 0x66, 0xac, 0x3d, 0xcd, 0x27, 0x32, 0x19, 0x5f, 0x0b,
	0xc6, 0x0e, 0xde, 0x4a, 0x18, 0x0f, 0xfc, 0x10, 0xc6, 0x9a, 0x2b, 0xcb, 0x70, 0xe4, 0x00, 0x8a,
	0x92, 0xad, 0xa0, 0x7a, 0x0a, 0xd8, 0x7d, 0x1a, 0xd7, 0x14, 0x38, 0x15, 0x57, 0x12, 0x9c, 0x9b,
	0x3c, 0xcd, 0x29, 0x36, 0xac, 0x4e, 0x9a, 0x0e, 0xda, 0x4a, 0x81, 0x26, 0xdc, 0x28, 0x93, 0xb5,
	0x23, 0x58, 0x9b, 0xb8, 0x9a, 0x66, 0x05, 0x02, 0x1c, 0x67, 0x41, 0x51, 0x32, 0x1f, 0xe9, 0xa5,
	0xd2, 0x96, 0x94, 0x09, 0xda, 0x15, 0x20, 0x8c, 0x37, 0xa5, 0x1e, 0x8a, 0x3b, 0x3c, 0xd6, 0xae,
	0x13, 0x15, 0x4e, 0xeb, 0xc2, 0x62, 0x68, 0x4c, 0x68, 0x23, 0x26, 0x4d, 0x1a, 0x9a, 0x5a, 0x49,
	0x07, 0x5c, 0x6b, 0x84, 0xab, 0x02, 0x82, 0x50, 0xe9, 0xf1, 0x41, 0xa1, 0x0e, 0x14, 0x62, 0x9b,
	0x42, 0xb5, 0x64, 0xc4, 0x1e, 0xd9, 0x99, 0xba, 0x31, 0x2d, 0xc4, 0xa5, 0xd7, 0x84, 0x74, 0x11,
	0x15, 0x62, 0x69, 0xc4, 0x00, 0xa5, 0x3d, 0x0c, 0xe1, 0x58, 0x21, 0xd3, 0xe0, 0x32, 0x9b, 0x84,
	0x05, 0xa4, 0x81, 0x37, 0x38, 0x44, 0xbe, 0xff, 0x5a, 0xf0, 0x9d, 0xe6, 0xed, 0x79, 0xa5, 0x40,
	0x65, 0xaa, 0x85, 0xa1, 0xaf, 0x62, 0xf2, 0x2c, 0x8b, 0xcb, 0x84, 0xff, 0x2c, 0xe0, 0x87, 0xf8,
	0xdb, 0x14, 0xfc, 0x21, 0xe5, 0x51, 0x63, 0x4d, 0x1f, 0x0c, 0xb4, 0x87, 0xd8, 0x8e, 0xc6, 0xbc,
	0xb2, 0x37, 0x0a, 0xa8, 0xd9, 0x96, 0x87, 0x5a, 0x71, 0x79, 0x4f, 0xfa, 0x62, 0x66, 0x8d, 0xbf,
	0x88, 0x1a, 0x7f, 0xc4, 0xdf, 0x3f, 0xab, 0x46, 0x4f, 0x70, 0x1e, 0x97, 0x79, 0x0b, 0x28, 0xfd,
	0xcd, 0x90, 0x8e, 0x2d, 0xf3, 0x83, 0x92, 0x59, 0xd5, 0x17, 0xa2, 0xaa, 0x5a, 0x2b, 0x7d, 0x6c,
	0xc1, 0xf4, 0x5d, 0x2d, 0x88, 0x07, 0xbe, 0x79, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x66, 0x03, 0x4e,
	0x49, 0x33, 0x0a, 0x00, 0x00,
}
