#!/bin/bash
set -e

TAGS=( latest 1.11 1.11.0 )
OWNER=appcelerator
IMAGE=gotools

docker build -t ${OWNER}/${IMAGE} .

for tag in "${TAGS[@]}"
do
  docker tag ${OWNER}/${IMAGE} ${OWNER}/${IMAGE}:${tag}
#  docker push ${OWNER}/${IMAGE}:${tag}
done

