version: "3"

services:

    server:
        image: ${imageAmp}
        command: ["adm-server"]
        deploy:
            mode: replicated
            replicas: 1
            labels:
                io.amp.role: "infrastructure"
                io.amp.mapping: "ampadm:31315:tcp:8081"
            placement:
                constraints: [node.role == manager]
        labels:
            io.amp.role: "infrastructure"                 
        ports:
            - "31315:31315"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock                  
        networks:
            - infra 
            - public

    agent:
        image: ${imageAmp}
        command: ["adm-agent"]
        deploy:
            mode: global
            labels:
                io.amp.role: "infrastructure"
        labels:
            io.amp.role: "infrastructure"                 
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock                
        networks:
            - infra 

networks:
    infra:
        external:
            name: ampcore_infra
    public:
        external:
            name: ampcore_public

  

