FROM appcelerator/alpine:20160726
COPY ./amp /usr/local/bin/amp
COPY ./amplifier /usr/local/bin/amplifier
COPY ./amp-agent /usr/local/bin/amp-agent
COPY ./amp-log-worker /usr/local/bin/amp-log-worker
COPY ./amplifier-gateway /usr/local/bin/amplifier-gateway
COPY ./cluster-server /usr/local/bin/cluster-server
COPY ./cluster-agent /usr/local/bin/cluster-agent
EXPOSE 50101
ENTRYPOINT []
CMD [ "amplifier" ]
