// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/api/rpc/service/service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/service/service.proto

It has these top-level messages:
	ServiceSpec
	NetworkAttachment
	PublishSpec
	ReplicatedService
	GlobalService
	ServiceCreateRequest
	ServiceCreateResponse
	RemoveRequest
	RemoveResponse
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceSpec struct {
	Image string `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Types that are valid to be assigned to Mode:
	//	*ServiceSpec_Replicated
	//	*ServiceSpec_Global
	Mode            isServiceSpec_Mode   `protobuf_oneof:"mode"`
	Env             []string             `protobuf:"bytes,5,rep,name=env" json:"env,omitempty"`
	Networks        []*NetworkAttachment `protobuf:"bytes,6,rep,name=networks" json:"networks,omitempty"`
	Labels          map[string]string    `protobuf:"bytes,7,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContainerLabels map[string]string    `protobuf:"bytes,8,rep,name=container_labels,json=containerLabels" json:"container_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PublishSpecs    []*PublishSpec       `protobuf:"bytes,9,rep,name=publish_specs,json=publishSpecs" json:"publish_specs,omitempty"`
	Args            []string             `protobuf:"bytes,10,rep,name=args" json:"args,omitempty"`
	Mounts          []string             `protobuf:"bytes,11,rep,name=mounts" json:"mounts,omitempty"`
	RegistryAuth    string               `protobuf:"bytes,12,opt,name=registry_auth,json=registryAuth" json:"registry_auth,omitempty"`
}

func (m *ServiceSpec) Reset()                    { *m = ServiceSpec{} }
func (m *ServiceSpec) String() string            { return proto.CompactTextString(m) }
func (*ServiceSpec) ProtoMessage()               {}
func (*ServiceSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isServiceSpec_Mode interface {
	isServiceSpec_Mode()
}

type ServiceSpec_Replicated struct {
	Replicated *ReplicatedService `protobuf:"bytes,3,opt,name=replicated,oneof"`
}
type ServiceSpec_Global struct {
	Global *GlobalService `protobuf:"bytes,4,opt,name=global,oneof"`
}

func (*ServiceSpec_Replicated) isServiceSpec_Mode() {}
func (*ServiceSpec_Global) isServiceSpec_Mode()     {}

func (m *ServiceSpec) GetMode() isServiceSpec_Mode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (m *ServiceSpec) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ServiceSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceSpec) GetReplicated() *ReplicatedService {
	if x, ok := m.GetMode().(*ServiceSpec_Replicated); ok {
		return x.Replicated
	}
	return nil
}

func (m *ServiceSpec) GetGlobal() *GlobalService {
	if x, ok := m.GetMode().(*ServiceSpec_Global); ok {
		return x.Global
	}
	return nil
}

func (m *ServiceSpec) GetEnv() []string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ServiceSpec) GetNetworks() []*NetworkAttachment {
	if m != nil {
		return m.Networks
	}
	return nil
}

func (m *ServiceSpec) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ServiceSpec) GetContainerLabels() map[string]string {
	if m != nil {
		return m.ContainerLabels
	}
	return nil
}

func (m *ServiceSpec) GetPublishSpecs() []*PublishSpec {
	if m != nil {
		return m.PublishSpecs
	}
	return nil
}

func (m *ServiceSpec) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ServiceSpec) GetMounts() []string {
	if m != nil {
		return m.Mounts
	}
	return nil
}

func (m *ServiceSpec) GetRegistryAuth() string {
	if m != nil {
		return m.RegistryAuth
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ServiceSpec) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ServiceSpec_OneofMarshaler, _ServiceSpec_OneofUnmarshaler, _ServiceSpec_OneofSizer, []interface{}{
		(*ServiceSpec_Replicated)(nil),
		(*ServiceSpec_Global)(nil),
	}
}

func _ServiceSpec_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ServiceSpec)
	// mode
	switch x := m.Mode.(type) {
	case *ServiceSpec_Replicated:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Replicated); err != nil {
			return err
		}
	case *ServiceSpec_Global:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Global); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ServiceSpec.Mode has unexpected type %T", x)
	}
	return nil
}

func _ServiceSpec_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ServiceSpec)
	switch tag {
	case 3: // mode.replicated
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplicatedService)
		err := b.DecodeMessage(msg)
		m.Mode = &ServiceSpec_Replicated{msg}
		return true, err
	case 4: // mode.global
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GlobalService)
		err := b.DecodeMessage(msg)
		m.Mode = &ServiceSpec_Global{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ServiceSpec_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ServiceSpec)
	// mode
	switch x := m.Mode.(type) {
	case *ServiceSpec_Replicated:
		s := proto.Size(x.Replicated)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ServiceSpec_Global:
		s := proto.Size(x.Global)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NetworkAttachment struct {
	Target  string   `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	Aliases []string `protobuf:"bytes,2,rep,name=aliases" json:"aliases,omitempty"`
}

func (m *NetworkAttachment) Reset()                    { *m = NetworkAttachment{} }
func (m *NetworkAttachment) String() string            { return proto.CompactTextString(m) }
func (*NetworkAttachment) ProtoMessage()               {}
func (*NetworkAttachment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NetworkAttachment) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *NetworkAttachment) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

type PublishSpec struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Protocol     string `protobuf:"bytes,2,opt,name=protocol" json:"protocol,omitempty"`
	PublishPort  uint32 `protobuf:"varint,3,opt,name=publish_port,json=publishPort" json:"publish_port,omitempty"`
	InternalPort uint32 `protobuf:"varint,4,opt,name=internal_port,json=internalPort" json:"internal_port,omitempty"`
}

func (m *PublishSpec) Reset()                    { *m = PublishSpec{} }
func (m *PublishSpec) String() string            { return proto.CompactTextString(m) }
func (*PublishSpec) ProtoMessage()               {}
func (*PublishSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PublishSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PublishSpec) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *PublishSpec) GetPublishPort() uint32 {
	if m != nil {
		return m.PublishPort
	}
	return 0
}

func (m *PublishSpec) GetInternalPort() uint32 {
	if m != nil {
		return m.InternalPort
	}
	return 0
}

type ReplicatedService struct {
	Replicas uint64 `protobuf:"varint,1,opt,name=replicas" json:"replicas,omitempty"`
}

func (m *ReplicatedService) Reset()                    { *m = ReplicatedService{} }
func (m *ReplicatedService) String() string            { return proto.CompactTextString(m) }
func (*ReplicatedService) ProtoMessage()               {}
func (*ReplicatedService) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReplicatedService) GetReplicas() uint64 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

type GlobalService struct {
}

func (m *GlobalService) Reset()                    { *m = GlobalService{} }
func (m *GlobalService) String() string            { return proto.CompactTextString(m) }
func (*GlobalService) ProtoMessage()               {}
func (*GlobalService) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ServiceCreateRequest struct {
	ServiceSpec *ServiceSpec `protobuf:"bytes,1,opt,name=service_spec,json=serviceSpec" json:"service_spec,omitempty"`
}

func (m *ServiceCreateRequest) Reset()                    { *m = ServiceCreateRequest{} }
func (m *ServiceCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceCreateRequest) ProtoMessage()               {}
func (*ServiceCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ServiceCreateRequest) GetServiceSpec() *ServiceSpec {
	if m != nil {
		return m.ServiceSpec
	}
	return nil
}

type ServiceCreateResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ServiceCreateResponse) Reset()                    { *m = ServiceCreateResponse{} }
func (m *ServiceCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceCreateResponse) ProtoMessage()               {}
func (*ServiceCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServiceCreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveRequest struct {
	Ident string `protobuf:"bytes,1,opt,name=ident" json:"ident,omitempty"`
}

func (m *RemoveRequest) Reset()                    { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()               {}
func (*RemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RemoveRequest) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

type RemoveResponse struct {
	Ident string `protobuf:"bytes,1,opt,name=ident" json:"ident,omitempty"`
}

func (m *RemoveResponse) Reset()                    { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()               {}
func (*RemoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RemoveResponse) GetIdent() string {
	if m != nil {
		return m.Ident
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceSpec)(nil), "service.ServiceSpec")
	proto.RegisterType((*NetworkAttachment)(nil), "service.NetworkAttachment")
	proto.RegisterType((*PublishSpec)(nil), "service.PublishSpec")
	proto.RegisterType((*ReplicatedService)(nil), "service.ReplicatedService")
	proto.RegisterType((*GlobalService)(nil), "service.GlobalService")
	proto.RegisterType((*ServiceCreateRequest)(nil), "service.ServiceCreateRequest")
	proto.RegisterType((*ServiceCreateResponse)(nil), "service.ServiceCreateResponse")
	proto.RegisterType((*RemoveRequest)(nil), "service.RemoveRequest")
	proto.RegisterType((*RemoveResponse)(nil), "service.RemoveResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Service service

type ServiceClient interface {
	Create(ctx context.Context, in *ServiceCreateRequest, opts ...grpc.CallOption) (*ServiceCreateResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Create(ctx context.Context, in *ServiceCreateRequest, opts ...grpc.CallOption) (*ServiceCreateResponse, error) {
	out := new(ServiceCreateResponse)
	err := grpc.Invoke(ctx, "/service.Service/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := grpc.Invoke(ctx, "/service.Service/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceServer interface {
	Create(context.Context, *ServiceCreateRequest) (*ServiceCreateResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Create(ctx, req.(*ServiceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Service_Create_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Service_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/appcelerator/amp/api/rpc/service/service.proto",
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/service/service.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xbe, 0x4e, 0x52, 0xa7, 0x3d, 0x4e, 0xfa, 0x33, 0x37, 0xcd, 0xb5, 0x72, 0x7f, 0x94, 0x6b,
	0x04, 0x94, 0x2e, 0x62, 0x28, 0x12, 0xb4, 0x15, 0x9b, 0xb6, 0xaa, 0x60, 0x81, 0xa0, 0x72, 0x11,
	0xdb, 0x68, 0xe2, 0x1c, 0x39, 0x56, 0xed, 0x19, 0x33, 0x33, 0x09, 0xaa, 0x10, 0x1b, 0x24, 0x9e,
	0x00, 0x9e, 0x88, 0x57, 0xe0, 0x15, 0x78, 0x10, 0xe4, 0xf1, 0xd8, 0x75, 0xda, 0xb2, 0x60, 0xe5,
	0xf9, 0xce, 0x7c, 0xf3, 0x9d, 0x1f, 0x7f, 0x33, 0x70, 0x10, 0xc5, 0x6a, 0x36, 0x9f, 0x8c, 0x42,
	0x9e, 0xfa, 0x34, 0xcb, 0x42, 0x4c, 0x50, 0x50, 0xc5, 0x85, 0x4f, 0xd3, 0xcc, 0xa7, 0x59, 0xec,
	0x8b, 0x2c, 0xf4, 0x25, 0x8a, 0x45, 0x1c, 0x62, 0xf9, 0x1d, 0x65, 0x82, 0x2b, 0x4e, 0xda, 0x06,
	0x0e, 0xfe, 0x89, 0x38, 0x8f, 0x12, 0xd4, 0x74, 0xca, 0x18, 0x57, 0x54, 0xc5, 0x9c, 0xc9, 0x82,
	0xe6, 0x7d, 0x5d, 0x01, 0xe7, 0xbc, 0x60, 0x9e, 0x67, 0x18, 0x92, 0x1e, 0xac, 0xc4, 0x29, 0x8d,
	0xd0, 0xb5, 0x86, 0xd6, 0xce, 0x5a, 0x50, 0x00, 0x42, 0xa0, 0xc5, 0x68, 0x8a, 0x6e, 0x43, 0x07,
	0xf5, 0x9a, 0x3c, 0x03, 0x10, 0x98, 0x25, 0x71, 0x48, 0x15, 0x4e, 0xdd, 0xe6, 0xd0, 0xda, 0x71,
	0xf6, 0x06, 0xa3, 0xb2, 0x88, 0xa0, 0xda, 0x32, 0xea, 0x2f, 0xfe, 0x08, 0x6a, 0x7c, 0xf2, 0x10,
	0xec, 0x28, 0xe1, 0x13, 0x9a, 0xb8, 0x2d, 0x7d, 0xb2, 0x5f, 0x9d, 0x7c, 0xae, 0xc3, 0x57, 0xa7,
	0x0c, 0x8f, 0x6c, 0x42, 0x13, 0xd9, 0xc2, 0x5d, 0x19, 0x36, 0x77, 0xd6, 0x82, 0x7c, 0x49, 0x9e,
	0xc0, 0x2a, 0x43, 0xf5, 0x9e, 0x8b, 0x0b, 0xe9, 0xda, 0xc3, 0xe6, 0x52, 0xfe, 0x57, 0xc5, 0xc6,
	0x91, 0x52, 0x34, 0x9c, 0xa5, 0xc8, 0x54, 0x50, 0x71, 0xc9, 0x3e, 0xd8, 0x09, 0x9d, 0x60, 0x22,
	0xdd, 0xb6, 0x3e, 0x35, 0xac, 0x4e, 0xd5, 0x26, 0x31, 0x7a, 0xa9, 0x29, 0xa7, 0x4c, 0x89, 0xcb,
	0xc0, 0xf0, 0xc9, 0x1b, 0xd8, 0x0c, 0x39, 0x53, 0x34, 0x66, 0x28, 0xc6, 0x46, 0x63, 0x55, 0x6b,
	0x3c, 0xb8, 0x55, 0xe3, 0xa4, 0x24, 0xd7, 0xc5, 0x36, 0xc2, 0xe5, 0x28, 0x39, 0x80, 0x6e, 0x36,
	0x9f, 0x24, 0xb1, 0x9c, 0x8d, 0x65, 0x86, 0xa1, 0x74, 0xd7, 0xb4, 0x64, 0xaf, 0x92, 0x3c, 0x2b,
	0x76, 0x73, 0xc9, 0xa0, 0x93, 0x5d, 0x01, 0x99, 0xff, 0x18, 0x2a, 0x22, 0xe9, 0x82, 0x9e, 0x8a,
	0x5e, 0x93, 0x3e, 0xd8, 0x29, 0x9f, 0x33, 0x25, 0x5d, 0x47, 0x47, 0x0d, 0x22, 0x77, 0xa0, 0x2b,
	0x30, 0x8a, 0xa5, 0x12, 0x97, 0x63, 0x3a, 0x57, 0x33, 0xb7, 0xa3, 0xff, 0x66, 0xa7, 0x0c, 0x1e,
	0xcd, 0xd5, 0x6c, 0x70, 0x00, 0x4e, 0xad, 0xd6, 0x7c, 0xe8, 0x17, 0x78, 0x69, 0xcc, 0x90, 0x2f,
	0x73, 0x83, 0x2c, 0x68, 0x32, 0x2f, 0xbd, 0x50, 0x80, 0xc3, 0xc6, 0xbe, 0x35, 0x38, 0x86, 0xde,
	0x6d, 0xfd, 0xfe, 0x8e, 0xc6, 0xb1, 0x0d, 0xad, 0x94, 0x4f, 0xd1, 0x3b, 0x85, 0xad, 0x1b, 0x7f,
	0x30, 0x6f, 0x4c, 0x51, 0x11, 0xa1, 0x32, 0x5a, 0x06, 0x11, 0x17, 0xda, 0x34, 0x89, 0xa9, 0x44,
	0xe9, 0x36, 0x74, 0xc7, 0x25, 0xf4, 0x3e, 0x5b, 0xe0, 0xd4, 0x86, 0x57, 0xf9, 0xd8, 0xaa, 0xf9,
	0x78, 0x00, 0xab, 0xfa, 0x2a, 0x84, 0x3c, 0x31, 0xf5, 0x54, 0x98, 0xfc, 0x0f, 0xe5, 0xb8, 0xc7,
	0x19, 0x17, 0x4a, 0xbb, 0xbc, 0x1b, 0x38, 0x26, 0x76, 0xc6, 0x85, 0xca, 0xa7, 0x1a, 0x33, 0x85,
	0x82, 0xd1, 0xa4, 0xe0, 0xb4, 0x34, 0xa7, 0x53, 0x06, 0x73, 0x92, 0xe7, 0xc3, 0xd6, 0x8d, 0x0b,
	0x91, 0x27, 0x36, 0x17, 0x42, 0xea, 0x82, 0x5a, 0x41, 0x85, 0xbd, 0x0d, 0xe8, 0x2e, 0xdd, 0x03,
	0xef, 0x35, 0xf4, 0xcc, 0xf2, 0x44, 0x20, 0x55, 0x18, 0xe0, 0xbb, 0x39, 0x4a, 0x45, 0x9e, 0x42,
	0xc7, 0xb8, 0x44, 0x7b, 0x47, 0x0b, 0xd5, 0xad, 0x53, 0x73, 0x63, 0xe0, 0xc8, 0x2b, 0xe0, 0xdd,
	0x87, 0xed, 0x6b, 0x82, 0x32, 0xe3, 0x4c, 0x22, 0x59, 0x87, 0x46, 0x3c, 0x35, 0x13, 0x6a, 0xc4,
	0x53, 0xef, 0x2e, 0x74, 0x03, 0x4c, 0xf9, 0xa2, 0x4a, 0x99, 0x3f, 0x11, 0x53, 0x64, 0xaa, 0x7a,
	0x22, 0x72, 0xe0, 0xdd, 0x83, 0xf5, 0x92, 0x66, 0x84, 0x6e, 0xe5, 0xed, 0x7d, 0xb3, 0xa0, 0x5d,
	0x4e, 0x60, 0x0c, 0x76, 0x91, 0x9c, 0xfc, 0x7b, 0xbd, 0xe0, 0xa5, 0x2e, 0x07, 0xff, 0xfd, 0x6a,
	0xbb, 0x48, 0xe5, 0xf5, 0x3f, 0x7d, 0xff, 0xf1, 0xa5, 0xb1, 0xe9, 0x39, 0xfe, 0xe2, 0x51, 0xf9,
	0x0e, 0x1e, 0x5a, 0xbb, 0xe4, 0x2d, 0xd8, 0x45, 0x51, 0xa4, 0x5f, 0x7b, 0x99, 0x6a, 0xcd, 0x0c,
	0xfe, 0xba, 0x11, 0x37, 0x92, 0x7f, 0x6b, 0xc9, 0xed, 0xdd, 0x3f, 0x6b, 0x92, 0xfe, 0x07, 0xdd,
	0xc3, 0xc7, 0x89, 0xad, 0x1d, 0xf2, 0xf8, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xde, 0x25,
	0xc1, 0xa0, 0x05, 0x00, 0x00,
}
