// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/api/rpc/service/service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/service/service.proto

It has these top-level messages:
	ServiceCreateRequest
	ServiceCreateResponse
	ServiceRemoveRequest
	ServiceSpec
	PublishSpec
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceCreateRequest struct {
	ServiceSpec *ServiceSpec `protobuf:"bytes,1,opt,name=service_spec,json=serviceSpec" json:"service_spec,omitempty"`
}

func (m *ServiceCreateRequest) Reset()                    { *m = ServiceCreateRequest{} }
func (m *ServiceCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceCreateRequest) ProtoMessage()               {}
func (*ServiceCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceCreateRequest) GetServiceSpec() *ServiceSpec {
	if m != nil {
		return m.ServiceSpec
	}
	return nil
}

type ServiceCreateResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ServiceCreateResponse) Reset()                    { *m = ServiceCreateResponse{} }
func (m *ServiceCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceCreateResponse) ProtoMessage()               {}
func (*ServiceCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ServiceRemoveRequest struct {
	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
}

func (m *ServiceRemoveRequest) Reset()                    { *m = ServiceRemoveRequest{} }
func (m *ServiceRemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*ServiceRemoveRequest) ProtoMessage()               {}
func (*ServiceRemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ServiceSpec struct {
	Image           string            `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
	Name            string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Replicas        uint64            `protobuf:"varint,3,opt,name=replicas" json:"replicas,omitempty"`
	Env             []string          `protobuf:"bytes,4,rep,name=env" json:"env,omitempty"`
	Labels          map[string]string `protobuf:"bytes,5,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContainerLabels map[string]string `protobuf:"bytes,6,rep,name=container_labels,json=containerLabels" json:"container_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PublishSpecs    []*PublishSpec    `protobuf:"bytes,7,rep,name=publish_specs,json=publishSpecs" json:"publish_specs,omitempty"`
}

func (m *ServiceSpec) Reset()                    { *m = ServiceSpec{} }
func (m *ServiceSpec) String() string            { return proto.CompactTextString(m) }
func (*ServiceSpec) ProtoMessage()               {}
func (*ServiceSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServiceSpec) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ServiceSpec) GetContainerLabels() map[string]string {
	if m != nil {
		return m.ContainerLabels
	}
	return nil
}

func (m *ServiceSpec) GetPublishSpecs() []*PublishSpec {
	if m != nil {
		return m.PublishSpecs
	}
	return nil
}

type PublishSpec struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Protocol     string `protobuf:"bytes,2,opt,name=protocol" json:"protocol,omitempty"`
	PublishPort  uint32 `protobuf:"varint,3,opt,name=publish_port,json=publishPort" json:"publish_port,omitempty"`
	InternalPort uint32 `protobuf:"varint,4,opt,name=internal_port,json=internalPort" json:"internal_port,omitempty"`
}

func (m *PublishSpec) Reset()                    { *m = PublishSpec{} }
func (m *PublishSpec) String() string            { return proto.CompactTextString(m) }
func (*PublishSpec) ProtoMessage()               {}
func (*PublishSpec) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*ServiceCreateRequest)(nil), "service.ServiceCreateRequest")
	proto.RegisterType((*ServiceCreateResponse)(nil), "service.ServiceCreateResponse")
	proto.RegisterType((*ServiceRemoveRequest)(nil), "service.ServiceRemoveRequest")
	proto.RegisterType((*ServiceSpec)(nil), "service.ServiceSpec")
	proto.RegisterType((*PublishSpec)(nil), "service.PublishSpec")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Service service

type ServiceClient interface {
	Create(ctx context.Context, in *ServiceCreateRequest, opts ...grpc.CallOption) (*ServiceCreateResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Create(ctx context.Context, in *ServiceCreateRequest, opts ...grpc.CallOption) (*ServiceCreateResponse, error) {
	out := new(ServiceCreateResponse)
	err := grpc.Invoke(ctx, "/service.Service/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceServer interface {
	Create(context.Context, *ServiceCreateRequest) (*ServiceCreateResponse, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Create(ctx, req.(*ServiceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Service_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/service/service.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 449 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0x5d, 0x6b, 0xdb, 0x30,
	0x14, 0x9d, 0xe3, 0x34, 0x59, 0xae, 0x93, 0xad, 0x88, 0x0c, 0x4c, 0xa0, 0xc3, 0xf3, 0x1e, 0x96,
	0xbd, 0xc4, 0x90, 0x31, 0xd6, 0xec, 0x71, 0x65, 0x0f, 0x85, 0xc1, 0x8a, 0xdb, 0xf7, 0xa0, 0x28,
	0x97, 0x56, 0xcc, 0x96, 0x34, 0x49, 0x09, 0xf4, 0x07, 0xec, 0xf7, 0xec, 0x2f, 0x0e, 0xcb, 0xb2,
	0xe3, 0x94, 0xec, 0xa1, 0x4f, 0xb9, 0xe7, 0xea, 0xe4, 0xdc, 0x8f, 0x73, 0x0d, 0xab, 0x7b, 0x6e,
	0x1f, 0x76, 0x9b, 0x05, 0x93, 0x65, 0x46, 0x95, 0x62, 0x58, 0xa0, 0xa6, 0x56, 0xea, 0x8c, 0x96,
	0x2a, 0xa3, 0x8a, 0x67, 0x5a, 0xb1, 0xcc, 0xa0, 0xde, 0x73, 0x86, 0xcd, 0xef, 0x42, 0x69, 0x69,
	0x25, 0x19, 0x7a, 0x98, 0xfe, 0x84, 0xe9, 0x6d, 0x1d, 0x5e, 0x69, 0xa4, 0x16, 0x73, 0xfc, 0xbd,
	0x43, 0x63, 0xc9, 0x17, 0x18, 0x7b, 0xca, 0xda, 0x28, 0x64, 0x71, 0x90, 0x04, 0xf3, 0x68, 0x39,
	0x5d, 0x34, 0x32, 0xfe, 0x4f, 0xb7, 0x0a, 0x59, 0x1e, 0x99, 0x03, 0x48, 0x3f, 0xc0, 0x9b, 0x27,
	0x82, 0x46, 0x49, 0x61, 0x90, 0xbc, 0x82, 0x1e, 0xdf, 0x3a, 0x9d, 0x51, 0xde, 0xe3, 0xdb, 0xf4,
	0x73, 0x5b, 0x39, 0xc7, 0x52, 0xee, 0xdb, 0xca, 0x17, 0x00, 0x4d, 0xe5, 0x96, 0x3f, 0xf2, 0x99,
	0xeb, 0x6d, 0xfa, 0x37, 0x84, 0xa8, 0x53, 0x9c, 0x4c, 0xe1, 0x8c, 0x97, 0xf4, 0x1e, 0x3d, 0xb3,
	0x06, 0x84, 0x40, 0x5f, 0xd0, 0x12, 0xe3, 0x9e, 0x4b, 0xba, 0x98, 0xcc, 0xe0, 0xa5, 0x46, 0x55,
	0x70, 0x46, 0x4d, 0x1c, 0x26, 0xc1, 0xbc, 0x9f, 0xb7, 0x98, 0x9c, 0x43, 0x88, 0x62, 0x1f, 0xf7,
	0x93, 0x70, 0x3e, 0xca, 0xab, 0x90, 0x5c, 0xc2, 0xa0, 0xa0, 0x1b, 0x2c, 0x4c, 0x7c, 0x96, 0x84,
	0xf3, 0x68, 0x99, 0x9c, 0x1a, 0x7d, 0xf1, 0xc3, 0x51, 0xbe, 0x0b, 0xab, 0x1f, 0x73, 0xcf, 0x27,
	0x77, 0x70, 0xce, 0xa4, 0xb0, 0x94, 0x0b, 0xd4, 0x6b, 0xaf, 0x31, 0x70, 0x1a, 0x1f, 0x4f, 0x6a,
	0x5c, 0x35, 0xe4, 0xae, 0xd8, 0x6b, 0x76, 0x9c, 0x25, 0x2b, 0x98, 0xa8, 0xdd, 0xa6, 0xe0, 0xe6,
	0xc1, 0x19, 0x62, 0xe2, 0xa1, 0x93, 0x3c, 0x38, 0x72, 0x53, 0xbf, 0x3a, 0x47, 0xc6, 0xea, 0x00,
	0xcc, 0x6c, 0x05, 0x51, 0x47, 0xba, 0x9a, 0xf5, 0x17, 0x3e, 0xfa, 0x7d, 0x55, 0x61, 0xb5, 0xc3,
	0x3d, 0x2d, 0x76, 0xcd, 0xba, 0x6a, 0xf0, 0xb5, 0x77, 0x19, 0xcc, 0xbe, 0xc1, 0xf4, 0x54, 0x7b,
	0xcf, 0xd1, 0x48, 0xff, 0x04, 0x10, 0x75, 0x9a, 0x6b, 0xbd, 0x09, 0x8e, 0xbd, 0x71, 0x87, 0xc9,
	0x64, 0xe1, 0x05, 0x5a, 0x4c, 0xde, 0x41, 0x33, 0xce, 0x5a, 0x49, 0x6d, 0x9d, 0x77, 0x93, 0x3c,
	0xf2, 0xb9, 0x1b, 0xa9, 0x2d, 0x79, 0x0f, 0x13, 0x2e, 0x2c, 0x6a, 0x41, 0x8b, 0x9a, 0xd3, 0x77,
	0x9c, 0x71, 0x93, 0xac, 0x48, 0xcb, 0x3b, 0x18, 0xfa, 0xb5, 0x93, 0x6b, 0x18, 0xd4, 0xd7, 0x49,
	0x2e, 0x9e, 0x5a, 0x72, 0xf4, 0x19, 0xcc, 0xde, 0xfe, 0xef, 0xb9, 0x3e, 0xea, 0xf4, 0xc5, 0x66,
	0xe0, 0xfa, 0xfc, 0xf4, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x21, 0xe4, 0xff, 0x8d, 0x03, 0x00,
	0x00,
}
