version: "3"

services:
  pinger:
    image: subfuzion/pinger
    labels:
      amp.service.stabilize.timeout: "30s"
      amp.service.stabilize.delay: "5s"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
