version: "3.3"

networks:
  default:
    external:
      name: ampnet

volumes:
  etcd-data:

secrets:
  default.certificate.amp:
    file: defaults/certificate.amp
  default.amplifier.yml:
    file: defaults/amplifier.yml

services:

  amplifier:
    image: appcelerator/amplifier:${TAG:-0.13.1}
    networks:
      - default
    environment:
      REGISTRATION: ${REGISTRATION:-none}
      NOTIFICATIONS: ${NOTIFICATIONS:-false}
    ports:
      - "50101:50101"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "6s"
      amp.service.stabilize.timeout: "30s"
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
      restart_policy:
        condition: on-failure
    secrets:
      - source: default.certificate.amp
        target: cert0.pem
        mode: 0400
      - source: default.amplifier.yml
        target: amplifier.yml

  etcd:
    image: appcelerator/etcd:3.1.10
    networks:
      default:
    volumes:
      - etcd-data:/data
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 1
    command:
      - "--advertise-client-urls"
      - "http://etcd:2379"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "20s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"

