// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/api/rpc/topic/topic.proto
// DO NOT EDIT!

/*
Package topic is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/topic/topic.proto

It has these top-level messages:
	TopicEntry
	CreateRequest
	CreateReply
	ListRequest
	ListReply
	DeleteRequest
	DeleteReply
*/
package topic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TopicEntry struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *TopicEntry) Reset()                    { *m = TopicEntry{} }
func (m *TopicEntry) String() string            { return proto.CompactTextString(m) }
func (*TopicEntry) ProtoMessage()               {}
func (*TopicEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateRequest struct {
	Topic *TopicEntry `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetTopic() *TopicEntry {
	if m != nil {
		return m.Topic
	}
	return nil
}

type CreateReply struct {
	Topic *TopicEntry `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
}

func (m *CreateReply) Reset()                    { *m = CreateReply{} }
func (m *CreateReply) String() string            { return proto.CompactTextString(m) }
func (*CreateReply) ProtoMessage()               {}
func (*CreateReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateReply) GetTopic() *TopicEntry {
	if m != nil {
		return m.Topic
	}
	return nil
}

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ListReply struct {
	Topics []*TopicEntry `protobuf:"bytes,1,rep,name=topics" json:"topics,omitempty"`
}

func (m *ListReply) Reset()                    { *m = ListReply{} }
func (m *ListReply) String() string            { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()               {}
func (*ListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListReply) GetTopics() []*TopicEntry {
	if m != nil {
		return m.Topics
	}
	return nil
}

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DeleteReply struct {
	Topic *TopicEntry `protobuf:"bytes,1,opt,name=topic" json:"topic,omitempty"`
}

func (m *DeleteReply) Reset()                    { *m = DeleteReply{} }
func (m *DeleteReply) String() string            { return proto.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()               {}
func (*DeleteReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteReply) GetTopic() *TopicEntry {
	if m != nil {
		return m.Topic
	}
	return nil
}

func init() {
	proto.RegisterType((*TopicEntry)(nil), "topic.TopicEntry")
	proto.RegisterType((*CreateRequest)(nil), "topic.CreateRequest")
	proto.RegisterType((*CreateReply)(nil), "topic.CreateReply")
	proto.RegisterType((*ListRequest)(nil), "topic.ListRequest")
	proto.RegisterType((*ListReply)(nil), "topic.ListReply")
	proto.RegisterType((*DeleteRequest)(nil), "topic.DeleteRequest")
	proto.RegisterType((*DeleteReply)(nil), "topic.DeleteReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Topic service

type TopicClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error)
}

type topicClient struct {
	cc *grpc.ClientConn
}

func NewTopicClient(cc *grpc.ClientConn) TopicClient {
	return &topicClient{cc}
}

func (c *topicClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	out := new(CreateReply)
	err := grpc.Invoke(ctx, "/topic.Topic/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := grpc.Invoke(ctx, "/topic.Topic/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topicClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := grpc.Invoke(ctx, "/topic.Topic/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Topic service

type TopicServer interface {
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	List(context.Context, *ListRequest) (*ListReply, error)
	Delete(context.Context, *DeleteRequest) (*DeleteReply, error)
}

func RegisterTopicServer(s *grpc.Server, srv TopicServer) {
	s.RegisterService(&_Topic_serviceDesc, srv)
}

func _Topic_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topic.Topic/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Topic_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topic.Topic/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Topic_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopicServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/topic.Topic/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopicServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Topic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "topic.Topic",
	HandlerType: (*TopicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Topic_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Topic_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Topic_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/topic/topic.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x51, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0x26, 0x79, 0xdb, 0x40, 0x27, 0xe4, 0x45, 0x07, 0x0f, 0xa1, 0x17, 0x4b, 0x2e, 0x2a, 0x48,
	0x56, 0x22, 0x16, 0xef, 0xea, 0xcd, 0x53, 0xf0, 0x0f, 0x6c, 0xd3, 0x41, 0x17, 0x92, 0xee, 0xba,
	0xd9, 0x1e, 0xfa, 0x63, 0xfc, 0xaf, 0xb2, 0x1f, 0x69, 0x9b, 0xe2, 0x41, 0x2f, 0x61, 0xe6, 0xc9,
	0x33, 0xcf, 0x47, 0x02, 0x0f, 0xef, 0xc2, 0x7c, 0x6c, 0x57, 0x65, 0x23, 0x3b, 0xc6, 0x95, 0x6a,
	0xa8, 0x25, 0xcd, 0x8d, 0xd4, 0x8c, 0x77, 0x8a, 0x71, 0x25, 0x98, 0x56, 0x0d, 0x33, 0x52, 0x89,
	0xf0, 0x2c, 0x95, 0x96, 0x46, 0xe2, 0xd4, 0x2d, 0xc5, 0x1d, 0xc0, 0x9b, 0x1d, 0x5e, 0x36, 0x46,
	0xef, 0xf0, 0x3f, 0xc4, 0x62, 0x9d, 0x47, 0x8b, 0xe8, 0x7a, 0x56, 0xc7, 0x62, 0x8d, 0x08, 0x93,
	0x0d, 0xef, 0x28, 0x8f, 0x1d, 0xe2, 0xe6, 0xe2, 0x11, 0xb2, 0x27, 0x4d, 0xdc, 0x50, 0x4d, 0x9f,
	0x5b, 0xea, 0x0d, 0x5e, 0x81, 0xd7, 0x72, 0x77, 0x69, 0x75, 0x5e, 0x7a, 0x9b, 0x83, 0x6c, 0x1d,
	0xbc, 0x96, 0x90, 0x0e, 0x97, 0xaa, 0xdd, 0xfd, 0xfe, 0x2e, 0x83, 0xf4, 0x55, 0xf4, 0x26, 0xf8,
	0x15, 0x4b, 0x98, 0xf9, 0xd5, 0x8a, 0xdc, 0x40, 0xe2, 0x48, 0x7d, 0x1e, 0x2d, 0xfe, 0xfd, 0xac,
	0x12, 0x08, 0xc5, 0x25, 0x64, 0xcf, 0xd4, 0xd2, 0x21, 0xf8, 0x49, 0x5b, 0x9b, 0x6f, 0x20, 0xfc,
	0x25, 0x5f, 0xf5, 0x15, 0xc1, 0xd4, 0xa1, 0x58, 0x41, 0xe2, 0x1b, 0xe2, 0x45, 0x60, 0x8f, 0x3e,
	0xd5, 0x1c, 0x4f, 0x50, 0x6b, 0x73, 0x0b, 0x13, 0x5b, 0x07, 0x87, 0x77, 0x47, 0x55, 0xe7, 0x67,
	0x23, 0xcc, 0xb2, 0x2b, 0x48, 0x7c, 0xc6, 0xbd, 0xc3, 0xa8, 0xd3, 0xde, 0xe1, 0xa8, 0xc8, 0x2a,
	0x71, 0x7f, 0xfc, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x92, 0x94, 0x44, 0x3e, 0x2a, 0x02, 0x00,
	0x00,
}
