version: '2'
services:
  prometheus:
    extends:
      file: docker-compose.yml
      service: prometheus
  grafana:
    extends:
      file: docker-compose.yml
      service: grafana
  sut:
    image: appcelerator/sut
    build: ./sut
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - grafana
      - prometheus
