version: "3.1"

networks:
  default:
    external:
      name: ampnet

services:

  proxy:
    image: appcelerator/alpine:3.6.0
    networks:
      - default
    command: ["curl", "-sf", "http://stats:stats@${AMP_STACK:-amp}_proxy:1936/haproxy?stats;csv"]
    labels:
      io.amp.role: "infrastructure"
      io.amp.test:
      amp.service.stabilize.delay: "0s"
      amp.service.stabilize.timeout: "15s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.test:
      placement:
        constraints:
        - node.labels.amp.type.route == true
      restart_policy:
        condition: none
