version: "3.1"

networks:
  default:
    external:
      name: ampnet

services:

  docker-engine:
    image: appcelerator/socat:latest
    networks:
      - default
    #ports:
    #  - "4999:4999"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "20s"
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
        io.amp.metrics.port: "4999"
