version: "3.3"

networks:
  public:
    external: true
  core:
    external: true
  monit:
    external: true

secrets:
  certificate_amp:
    external: true

services:

  proxy:
    image: dockercloud/haproxy:1.6.7
    networks:
      - core
      - public
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.route == true
    environment:
      CERT_FOLDER: "/run/secrets"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "30s"
    ports:
      - "80:80"
      - "443:443"
      - "1936:1936"
    secrets:
      - source: certificate_amp
        target: cert0.pem
        mode: 0400
