#!/bin/bash

ec=0
result=$(amp -s localhost version)
echo $result

# not finding the version is an error
version="v[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}"
echo $result | grep -E "Version:[[:space:]]+$version"
if [[ $? -ne 0 ]]; then
	((ec++))
	echo "error: missing version"
fi

# finding "not connected" is an error
echo $result | grep "not connected"
if [[ $? -eq 0 ]]; then
	((ec++))
	echo "error: not connected"
fi

exit $ec

