// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/api/rpc/stack/stack.proto
// DO NOT EDIT!

/*
Package stack is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/stack/stack.proto

It has these top-level messages:
	DeployRequest
	DeployReply
	ListRequest
	ListReply
	StackReply
	RemoveRequest
	RemoveReply
*/
package stack

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Compose []byte `protobuf:"bytes,2,opt,name=compose,proto3" json:"compose,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeployRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployRequest) GetCompose() []byte {
	if m != nil {
		return m.Compose
	}
	return nil
}

type DeployReply struct {
	FullName string `protobuf:"bytes,1,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	Answer   string `protobuf:"bytes,2,opt,name=answer" json:"answer,omitempty"`
}

func (m *DeployReply) Reset()                    { *m = DeployReply{} }
func (m *DeployReply) String() string            { return proto.CompactTextString(m) }
func (*DeployReply) ProtoMessage()               {}
func (*DeployReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeployReply) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *DeployReply) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListReply struct {
	List []*StackReply `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ListReply) Reset()                    { *m = ListReply{} }
func (m *ListReply) String() string            { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()               {}
func (*ListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListReply) GetList() []*StackReply {
	if m != nil {
		return m.List
	}
	return nil
}

type StackReply struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Service string `protobuf:"bytes,3,opt,name=service" json:"service,omitempty"`
	Owner   string `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
}

func (m *StackReply) Reset()                    { *m = StackReply{} }
func (m *StackReply) String() string            { return proto.CompactTextString(m) }
func (*StackReply) ProtoMessage()               {}
func (*StackReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StackReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StackReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StackReply) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *StackReply) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type RemoveRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RemoveRequest) Reset()                    { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()               {}
func (*RemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RemoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemoveReply struct {
	Answer string `protobuf:"bytes,1,opt,name=answer" json:"answer,omitempty"`
}

func (m *RemoveReply) Reset()                    { *m = RemoveReply{} }
func (m *RemoveReply) String() string            { return proto.CompactTextString(m) }
func (*RemoveReply) ProtoMessage()               {}
func (*RemoveReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveReply) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func init() {
	proto.RegisterType((*DeployRequest)(nil), "stack.DeployRequest")
	proto.RegisterType((*DeployReply)(nil), "stack.DeployReply")
	proto.RegisterType((*ListRequest)(nil), "stack.ListRequest")
	proto.RegisterType((*ListReply)(nil), "stack.ListReply")
	proto.RegisterType((*StackReply)(nil), "stack.StackReply")
	proto.RegisterType((*RemoveRequest)(nil), "stack.RemoveRequest")
	proto.RegisterType((*RemoveReply)(nil), "stack.RemoveReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Stack service

type StackClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveReply, error)
}

type stackClient struct {
	cc *grpc.ClientConn
}

func NewStackClient(cc *grpc.ClientConn) StackClient {
	return &stackClient{cc}
}

func (c *stackClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error) {
	out := new(DeployReply)
	err := grpc.Invoke(ctx, "/stack.Stack/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := grpc.Invoke(ctx, "/stack.Stack/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveReply, error) {
	out := new(RemoveReply)
	err := grpc.Invoke(ctx, "/stack.Stack/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Stack service

type StackServer interface {
	Deploy(context.Context, *DeployRequest) (*DeployReply, error)
	List(context.Context, *ListRequest) (*ListReply, error)
	Remove(context.Context, *RemoveRequest) (*RemoveReply, error)
}

func RegisterStackServer(s *grpc.Server, srv StackServer) {
	s.RegisterService(&_Stack_serviceDesc, srv)
}

func _Stack_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stack.Stack/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stack_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stack.Stack/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stack_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stack.Stack/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stack_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stack.Stack",
	HandlerType: (*StackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _Stack_Deploy_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Stack_List_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Stack_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/appcelerator/amp/api/rpc/stack/stack.proto",
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/stack/stack.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x51, 0x4f, 0xb3, 0x30,
	0x14, 0x0d, 0x8c, 0xf1, 0x7d, 0x5c, 0x9c, 0xd1, 0x66, 0x31, 0x64, 0x3e, 0xb8, 0x34, 0x59, 0xb2,
	0x07, 0x33, 0x12, 0x8c, 0x8f, 0xbe, 0x18, 0x1f, 0x8d, 0x0f, 0xf8, 0x03, 0xb4, 0x63, 0x57, 0x6d,
	0x84, 0xb5, 0xb6, 0xdd, 0x96, 0xfd, 0x18, 0xff, 0xab, 0x69, 0x81, 0x0d, 0xf6, 0xd2, 0x70, 0x4e,
	0x2f, 0xe7, 0x9e, 0x73, 0x00, 0xee, 0x3f, 0xb9, 0xf9, 0xda, 0x2c, 0x17, 0x85, 0xa8, 0x52, 0x26,
	0x65, 0x81, 0x25, 0x2a, 0x66, 0x84, 0x4a, 0x59, 0x25, 0x53, 0x26, 0x79, 0xaa, 0x64, 0x91, 0x6a,
	0xc3, 0x8a, 0xef, 0xfa, 0x5c, 0x48, 0x25, 0x8c, 0x20, 0x43, 0x07, 0xe8, 0x03, 0x8c, 0x9e, 0x50,
	0x96, 0x62, 0x9f, 0xe3, 0xcf, 0x06, 0xb5, 0x21, 0x04, 0x82, 0x35, 0xab, 0x30, 0xf1, 0xa6, 0xde,
	0x3c, 0xca, 0xdd, 0x33, 0x49, 0xe0, 0x5f, 0x21, 0x2a, 0x29, 0x34, 0x26, 0xfe, 0xd4, 0x9b, 0x9f,
	0xe5, 0x2d, 0xa4, 0x8f, 0x10, 0xb7, 0xaf, 0xcb, 0x72, 0x4f, 0xae, 0x21, 0xfa, 0xd8, 0x94, 0xe5,
	0x5b, 0x47, 0xe1, 0xbf, 0x25, 0x5e, 0xac, 0xca, 0x15, 0x84, 0x6c, 0xad, 0x77, 0xa8, 0x9c, 0x48,
	0x94, 0x37, 0x88, 0x8e, 0x20, 0x7e, 0xe6, 0xda, 0x34, 0x06, 0x68, 0x06, 0x51, 0x0d, 0xad, 0xe0,
	0x0c, 0x82, 0x92, 0x6b, 0x93, 0x78, 0xd3, 0xc1, 0x3c, 0xce, 0x2e, 0x17, 0x75, 0x82, 0x57, 0x7b,
	0xba, 0x81, 0xdc, 0x5d, 0xd3, 0x77, 0x80, 0x23, 0x47, 0xce, 0xc1, 0xe7, 0xab, 0x66, 0xbd, 0xcf,
	0x57, 0x87, 0x48, 0x7e, 0x3f, 0x92, 0x46, 0xb5, 0xe5, 0x05, 0x26, 0x03, 0x47, 0xb7, 0x90, 0x8c,
	0x61, 0x28, 0x76, 0x6b, 0x54, 0x49, 0xe0, 0xf8, 0x1a, 0xd0, 0x1b, 0x18, 0xe5, 0x58, 0x89, 0x2d,
	0xb6, 0x3d, 0x9d, 0x2c, 0xa1, 0x33, 0x88, 0xdb, 0x01, 0xeb, 0xe1, 0x18, 0xd6, 0xeb, 0x86, 0xcd,
	0x7e, 0x3d, 0x18, 0x3a, 0xab, 0x24, 0x83, 0xb0, 0xae, 0x8e, 0x8c, 0x9b, 0x58, 0xbd, 0x0f, 0x31,
	0x21, 0x27, 0xac, 0x55, 0xbd, 0x85, 0xc0, 0x76, 0x43, 0xda, 0xbb, 0x4e, 0x6f, 0x93, 0x8b, 0x1e,
	0x67, 0xa7, 0x33, 0x08, 0x6b, 0x4b, 0x87, 0x0d, 0xbd, 0x08, 0x87, 0x0d, 0x1d, 0xdf, 0xcb, 0xd0,
	0xfd, 0x1d, 0x77, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xc5, 0xe9, 0xc3, 0x56, 0x02, 0x00,
	0x00,
}
