// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/api/rpc/stack/stack.proto
// DO NOT EDIT!

/*
Package stack is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/stack/stack.proto

It has these top-level messages:
	DeployRequest
	DeployReply
	ListRequest
	ListReply
	RemoveRequest
*/
package stack

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeployRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Compose []byte `protobuf:"bytes,2,opt,name=compose,proto3" json:"compose,omitempty"`
}

func (m *DeployRequest) Reset()                    { *m = DeployRequest{} }
func (m *DeployRequest) String() string            { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()               {}
func (*DeployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeployRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployRequest) GetCompose() []byte {
	if m != nil {
		return m.Compose
	}
	return nil
}

type DeployReply struct {
}

func (m *DeployReply) Reset()                    { *m = DeployReply{} }
func (m *DeployReply) String() string            { return proto.CompactTextString(m) }
func (*DeployReply) ProtoMessage()               {}
func (*DeployReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ListReply struct {
}

func (m *ListReply) Reset()                    { *m = ListReply{} }
func (m *ListReply) String() string            { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()               {}
func (*ListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RemoveRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RemoveRequest) Reset()                    { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()               {}
func (*RemoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RemoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*DeployRequest)(nil), "stack.DeployRequest")
	proto.RegisterType((*DeployReply)(nil), "stack.DeployReply")
	proto.RegisterType((*ListRequest)(nil), "stack.ListRequest")
	proto.RegisterType((*ListReply)(nil), "stack.ListReply")
	proto.RegisterType((*RemoveRequest)(nil), "stack.RemoveRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Stack service

type StackClient interface {
	Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type stackClient struct {
	cc *grpc.ClientConn
}

func NewStackClient(cc *grpc.ClientConn) StackClient {
	return &stackClient{cc}
}

func (c *stackClient) Deploy(ctx context.Context, in *DeployRequest, opts ...grpc.CallOption) (*DeployReply, error) {
	out := new(DeployReply)
	err := grpc.Invoke(ctx, "/stack.Stack/Deploy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := grpc.Invoke(ctx, "/stack.Stack/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/stack.Stack/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Stack service

type StackServer interface {
	Deploy(context.Context, *DeployRequest) (*DeployReply, error)
	List(context.Context, *ListRequest) (*ListReply, error)
	Remove(context.Context, *RemoveRequest) (*google_protobuf.Empty, error)
}

func RegisterStackServer(s *grpc.Server, srv StackServer) {
	s.RegisterService(&_Stack_serviceDesc, srv)
}

func _Stack_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stack.Stack/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).Deploy(ctx, req.(*DeployRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stack_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stack.Stack/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stack_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stack.Stack/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Stack_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stack.Stack",
	HandlerType: (*StackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deploy",
			Handler:    _Stack_Deploy_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Stack_List_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Stack_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/appcelerator/amp/api/rpc/stack/stack.proto",
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/stack/stack.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0xa5, 0xad, 0x74, 0x6a, 0x44, 0x16, 0x91, 0x90, 0x8b, 0x25, 0xa7, 0x1e, 0x64, 0x17,
	0x5a, 0xf4, 0xe6, 0x4d, 0x6f, 0x9e, 0xe2, 0x17, 0x6c, 0xd2, 0x31, 0x06, 0x77, 0x3b, 0x63, 0xb2,
	0x11, 0xf2, 0x39, 0xfe, 0xa9, 0x6c, 0xb6, 0x91, 0xc6, 0xcb, 0xb0, 0x6f, 0xde, 0xbe, 0x79, 0x6f,
	0x06, 0x1e, 0xaa, 0xda, 0x7d, 0x74, 0x85, 0x2c, 0xc9, 0x2a, 0xcd, 0x5c, 0xa2, 0xc1, 0x46, 0x3b,
	0x6a, 0x94, 0xb6, 0xac, 0x34, 0xd7, 0xaa, 0xe1, 0x52, 0xb5, 0x4e, 0x97, 0x9f, 0xa1, 0x4a, 0x6e,
	0xc8, 0x91, 0x58, 0x0c, 0x20, 0xdd, 0x9f, 0xa9, 0x2b, 0x32, 0xfa, 0x58, 0xa9, 0x81, 0x2f, 0xba,
	0x77, 0xc5, 0xae, 0x67, 0x6c, 0x15, 0x5a, 0x76, 0x7d, 0xa8, 0x41, 0x9b, 0x3d, 0x41, 0xfc, 0x8c,
	0x6c, 0xa8, 0xcf, 0xf1, 0xab, 0xc3, 0xd6, 0x09, 0x01, 0xf3, 0xa3, 0xb6, 0x98, 0x44, 0x9b, 0x68,
	0xbb, 0xca, 0x87, 0xb7, 0x48, 0xe0, 0xa2, 0x24, 0xcb, 0xd4, 0x62, 0x32, 0xdb, 0x44, 0xdb, 0xcb,
	0x7c, 0x84, 0x59, 0x0c, 0xeb, 0x51, 0xce, 0xa6, 0xf7, 0xf0, 0xb5, 0x6e, 0xdd, 0x69, 0x56, 0xb6,
	0x86, 0x55, 0x80, 0x9e, 0xbb, 0x83, 0x38, 0x47, 0x4b, 0xdf, 0x38, 0x3a, 0x5d, 0xc1, 0xac, 0x3e,
	0x9c, 0x7c, 0x66, 0xf5, 0x61, 0xf7, 0x13, 0xc1, 0xe2, 0xcd, 0x6f, 0x22, 0x76, 0xb0, 0x0c, 0x53,
	0xc5, 0x8d, 0x0c, 0x8b, 0x4e, 0x32, 0xa6, 0xe2, 0x5f, 0x97, 0x4d, 0x2f, 0xee, 0x61, 0xee, 0xbd,
	0xc4, 0xc8, 0x9d, 0xe5, 0x48, 0xaf, 0x27, 0x3d, 0xff, 0xfb, 0x11, 0x96, 0x21, 0xcc, 0x9f, 0xc3,
	0x24, 0x5b, 0x7a, 0x2b, 0x2b, 0xa2, 0xca, 0xa0, 0x1c, 0x2f, 0x28, 0x5f, 0xfc, 0xd1, 0x8a, 0xe5,
	0x80, 0xf7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x91, 0xd1, 0x06, 0x6f, 0xaa, 0x01, 0x00, 0x00,
}
