// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/api/rpc/stack/stack.proto
// DO NOT EDIT!

/*
Package stack is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/stack/stack.proto

It has these top-level messages:
	UpRequest
	UpReply
	StackRequest
	StackReply
	StackID
	Stack
	ListRequest
	ServiceIdList
	ListReply
	StackInfo
*/
package stack

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import service "github.com/appcelerator/amp/api/rpc/service"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StackState int32

const (
	StackState_Stopped     StackState = 0
	StackState_Starting    StackState = 1
	StackState_Running     StackState = 2
	StackState_Redeploying StackState = 3
)

var StackState_name = map[int32]string{
	0: "Stopped",
	1: "Starting",
	2: "Running",
	3: "Redeploying",
}
var StackState_value = map[string]int32{
	"Stopped":     0,
	"Starting":    1,
	"Running":     2,
	"Redeploying": 3,
}

func (x StackState) String() string {
	return proto.EnumName(StackState_name, int32(x))
}
func (StackState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UpRequest struct {
	StackName string `protobuf:"bytes,1,opt,name=stack_name,json=stackName" json:"stack_name,omitempty"`
	Stackfile string `protobuf:"bytes,2,opt,name=stackfile" json:"stackfile,omitempty"`
}

func (m *UpRequest) Reset()                    { *m = UpRequest{} }
func (m *UpRequest) String() string            { return proto.CompactTextString(m) }
func (*UpRequest) ProtoMessage()               {}
func (*UpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UpReply struct {
	StackId string `protobuf:"bytes,1,opt,name=stack_id,json=stackId" json:"stack_id,omitempty"`
}

func (m *UpReply) Reset()                    { *m = UpReply{} }
func (m *UpReply) String() string            { return proto.CompactTextString(m) }
func (*UpReply) ProtoMessage()               {}
func (*UpReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StackRequest struct {
	StackIdent string `protobuf:"bytes,1,opt,name=stack_ident,json=stackIdent" json:"stack_ident,omitempty"`
}

func (m *StackRequest) Reset()                    { *m = StackRequest{} }
func (m *StackRequest) String() string            { return proto.CompactTextString(m) }
func (*StackRequest) ProtoMessage()               {}
func (*StackRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StackReply struct {
	StackId string `protobuf:"bytes,1,opt,name=stack_id,json=stackId" json:"stack_id,omitempty"`
}

func (m *StackReply) Reset()                    { *m = StackReply{} }
func (m *StackReply) String() string            { return proto.CompactTextString(m) }
func (*StackReply) ProtoMessage()               {}
func (*StackReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type StackID struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *StackID) Reset()                    { *m = StackID{} }
func (m *StackID) String() string            { return proto.CompactTextString(m) }
func (*StackID) ProtoMessage()               {}
func (*StackID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Stack struct {
	Name     string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id       string                 `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Services []*service.ServiceSpec `protobuf:"bytes,3,rep,name=services" json:"services,omitempty"`
}

func (m *Stack) Reset()                    { *m = Stack{} }
func (m *Stack) String() string            { return proto.CompactTextString(m) }
func (*Stack) ProtoMessage()               {}
func (*Stack) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Stack) GetServices() []*service.ServiceSpec {
	if m != nil {
		return m.Services
	}
	return nil
}

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ServiceIdList struct {
	List []string `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ServiceIdList) Reset()                    { *m = ServiceIdList{} }
func (m *ServiceIdList) String() string            { return proto.CompactTextString(m) }
func (*ServiceIdList) ProtoMessage()               {}
func (*ServiceIdList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ListReply struct {
	List []*StackInfo `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ListReply) Reset()                    { *m = ListReply{} }
func (m *ListReply) String() string            { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()               {}
func (*ListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListReply) GetList() []*StackInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type StackInfo struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	State string `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
}

func (m *StackInfo) Reset()                    { *m = StackInfo{} }
func (m *StackInfo) String() string            { return proto.CompactTextString(m) }
func (*StackInfo) ProtoMessage()               {}
func (*StackInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*UpRequest)(nil), "stack.UpRequest")
	proto.RegisterType((*UpReply)(nil), "stack.UpReply")
	proto.RegisterType((*StackRequest)(nil), "stack.StackRequest")
	proto.RegisterType((*StackReply)(nil), "stack.StackReply")
	proto.RegisterType((*StackID)(nil), "stack.StackID")
	proto.RegisterType((*Stack)(nil), "stack.Stack")
	proto.RegisterType((*ListRequest)(nil), "stack.ListRequest")
	proto.RegisterType((*ServiceIdList)(nil), "stack.ServiceIdList")
	proto.RegisterType((*ListReply)(nil), "stack.ListReply")
	proto.RegisterType((*StackInfo)(nil), "stack.StackInfo")
	proto.RegisterEnum("stack.StackState", StackState_name, StackState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for StackService service

type StackServiceClient interface {
	Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (*UpReply, error)
	Stop(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*StackReply, error)
	Remove(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*StackReply, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
}

type stackServiceClient struct {
	cc *grpc.ClientConn
}

func NewStackServiceClient(cc *grpc.ClientConn) StackServiceClient {
	return &stackServiceClient{cc}
}

func (c *stackServiceClient) Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (*UpReply, error) {
	out := new(UpReply)
	err := grpc.Invoke(ctx, "/stack.StackService/Up", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackServiceClient) Stop(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*StackReply, error) {
	out := new(StackReply)
	err := grpc.Invoke(ctx, "/stack.StackService/Stop", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackServiceClient) Remove(ctx context.Context, in *StackRequest, opts ...grpc.CallOption) (*StackReply, error) {
	out := new(StackReply)
	err := grpc.Invoke(ctx, "/stack.StackService/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stackServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := grpc.Invoke(ctx, "/stack.StackService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StackService service

type StackServiceServer interface {
	Up(context.Context, *UpRequest) (*UpReply, error)
	Stop(context.Context, *StackRequest) (*StackReply, error)
	Remove(context.Context, *StackRequest) (*StackReply, error)
	List(context.Context, *ListRequest) (*ListReply, error)
}

func RegisterStackServiceServer(s *grpc.Server, srv StackServiceServer) {
	s.RegisterService(&_StackService_serviceDesc, srv)
}

func _StackService_Up_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServiceServer).Up(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stack.StackService/Up",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServiceServer).Up(ctx, req.(*UpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stack.StackService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServiceServer).Stop(ctx, req.(*StackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stack.StackService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServiceServer).Remove(ctx, req.(*StackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StackService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StackServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stack.StackService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StackServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StackService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stack.StackService",
	HandlerType: (*StackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Up",
			Handler:    _StackService_Up_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _StackService_Stop_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _StackService_Remove_Handler,
		},
		{
			MethodName: "List",
			Handler:    _StackService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/stack/stack.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0xa6, 0x49, 0xb7, 0x36, 0x97, 0x6d, 0x14, 0xb3, 0x87, 0xae, 0x02, 0x31, 0x99, 0x09, 0x26,
	0x84, 0x92, 0x51, 0xc4, 0x03, 0xef, 0x4c, 0xa2, 0x12, 0xe2, 0x21, 0xd1, 0x1e, 0x11, 0xf2, 0x92,
	0xdb, 0xb0, 0x48, 0x62, 0x93, 0xb8, 0x93, 0xfa, 0x07, 0xf9, 0x5d, 0xe8, 0x6c, 0x27, 0xca, 0x9e,
	0xe8, 0x4b, 0xed, 0xfb, 0xee, 0xbb, 0xef, 0xfa, 0xdd, 0x39, 0xf0, 0xe9, 0x5e, 0x9a, 0x5f, 0xdb,
	0xdb, 0xa4, 0x50, 0x75, 0x2a, 0xb4, 0x2e, 0xb0, 0xc2, 0x56, 0x18, 0xd5, 0xa6, 0xa2, 0xd6, 0xa9,
	0xd0, 0x32, 0x6d, 0x75, 0x91, 0x76, 0x46, 0x14, 0xbf, 0xdd, 0x6f, 0xa2, 0x5b, 0x65, 0x14, 0x3b,
	0xb0, 0xc1, 0xea, 0xf3, 0x5e, 0xd5, 0xd8, 0x3e, 0xc8, 0x02, 0xfb, 0xd3, 0x29, 0xf0, 0xaf, 0x10,
	0xdd, 0xe8, 0x0c, 0xff, 0x6c, 0xb1, 0x33, 0xec, 0x25, 0x80, 0x15, 0xfc, 0xd9, 0x88, 0x1a, 0x97,
	0x93, 0xf3, 0xc9, 0x65, 0x94, 0x45, 0x16, 0xf9, 0x2e, 0x6a, 0x64, 0x2f, 0xc0, 0x05, 0x77, 0xb2,
	0xc2, 0x65, 0x30, 0xca, 0x12, 0xc0, 0x2f, 0x60, 0x46, 0x4a, 0xba, 0xda, 0xb1, 0x33, 0x98, 0x3b,
	0x1d, 0x59, 0x7a, 0x95, 0x99, 0x8d, 0x37, 0x25, 0x4f, 0xe1, 0x28, 0xa7, 0x6b, 0xdf, 0xf2, 0x15,
	0xc4, 0x3d, 0x15, 0x1b, 0xe3, 0xd9, 0xe0, 0xd9, 0xd8, 0x18, 0xfe, 0x16, 0xc0, 0x17, 0xfc, 0x47,
	0xf9, 0x0c, 0x66, 0x96, 0xb8, 0xf9, 0xc2, 0x4e, 0x20, 0x18, 0xf2, 0x81, 0x2c, 0xf9, 0x0f, 0x38,
	0xb0, 0x29, 0xc6, 0x60, 0x3a, 0xb2, 0x66, 0xef, 0x9e, 0x1c, 0xf4, 0x64, 0x76, 0x05, 0x73, 0x3f,
	0xa2, 0x6e, 0x19, 0x9e, 0x87, 0x97, 0xf1, 0xfa, 0x34, 0xe9, 0x67, 0x96, 0xbb, 0x33, 0xd7, 0x58,
	0x64, 0x03, 0x8b, 0x1f, 0x43, 0xfc, 0x4d, 0x76, 0xc6, 0x5b, 0xe2, 0xaf, 0xe1, 0xd8, 0xf3, 0x36,
	0x25, 0xe1, 0xd4, 0xb5, 0x92, 0x1d, 0x99, 0x0b, 0xa9, 0x2b, 0xdd, 0xf9, 0x07, 0x88, 0x5c, 0x0d,
	0xb9, 0xba, 0x18, 0x11, 0xe2, 0xf5, 0x22, 0x71, 0x2b, 0x76, 0x6e, 0x9a, 0x3b, 0xe5, 0x4b, 0xae,
	0x21, 0x1a, 0xa0, 0xbd, 0x9c, 0x9c, 0x02, 0xbd, 0x0f, 0x83, 0xcb, 0xd0, 0x42, 0x2e, 0x78, 0x77,
	0xed, 0x07, 0x9a, 0x53, 0xc4, 0x62, 0x9a, 0x9a, 0xd2, 0x1a, 0xcb, 0xc5, 0x13, 0x76, 0x04, 0xf3,
	0xdc, 0x88, 0xd6, 0xc8, 0xe6, 0x7e, 0x31, 0xa1, 0x54, 0xb6, 0x6d, 0x1a, 0x0a, 0x02, 0xf6, 0x14,
	0xe2, 0x0c, 0x4b, 0xd4, 0x95, 0xda, 0x11, 0x10, 0xae, 0xff, 0x4e, 0xfc, 0x26, 0xbd, 0x57, 0xf6,
	0x06, 0x82, 0x1b, 0xcd, 0xfa, 0x3f, 0x3f, 0x3c, 0xaa, 0xd5, 0xc9, 0x08, 0x21, 0xb3, 0x09, 0x4c,
	0xa9, 0x23, 0x7b, 0x3e, 0xb6, 0xd9, 0x93, 0x9f, 0x3d, 0x06, 0x89, 0x7f, 0x05, 0x87, 0x19, 0xd6,
	0xea, 0x01, 0xf7, 0xae, 0x78, 0x0f, 0x53, 0x37, 0x77, 0x9f, 0x1a, 0x2d, 0x67, 0xb5, 0x78, 0x84,
	0xe9, 0x6a, 0x77, 0x7b, 0x68, 0x3f, 0x84, 0x8f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x46, 0x31,
	0xa2, 0x01, 0x83, 0x03, 0x00, 0x00,
}
