version: "3.3"

networks:
  public:
    external: true
  monit:
    external: true
  core:
    external: true

volumes:
  alertmanager-data:
  grafana-data:
  prometheus-data:

configs:
  prometheus_alerts_rules:
    external: true

secrets:
  alertmanager_yml:
    external: true

services:

  prometheus:
    image: appcelerator/amp-prometheus:${TAG:-latest}
    networks:
      - public
      - monit
      - core
    volumes:
      - prometheus-data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      SERVICE_PORTS: 9090
      VIRTUAL_HOST: "http://alerts.*,https://alerts.*"
      PROMETHEUS_EXTERNAL_URL: "${PROMETHEUS_EXTERNAL_URL:-https://alerts.local.appcelerator.io}"
    ports:
      - "9090:9090"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "45s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.metrics == true
    configs:
      - source: prometheus_alerts_rules
        target: /etc/prometheus/alerts.rules
        mode: 0400

  cadvisor:
    image: google/cadvisor:v0.28.0
    networks:
      - core
      - monit
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "20s"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      #- /dev/disk:/dev/disk:ro
    # ports:
    #  - "8080:8080"
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
        io.amp.metrics.port: "8080"

  docker-engine:
    image: appcelerator/socat:latest
    networks:
      - core
      - monit
    #ports:
    #  - "4999:4999"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "20s"
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
        io.amp.metrics.port: "4999"

  haproxy_exporter:
    image: prom/haproxy-exporter:v0.8.0
    command: ["--haproxy.scrape-uri", "http://stats:stats@proxy:1936/haproxy?stats;csv"]
    networks:
      - monit
      - core
    #ports:
      #- target: 9101
      #- published: 9101
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "20s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.metrics.port: "9101"
        io.amp.metrics.mode: "exporter"
      placement:
        constraints:
        - node.labels.amp.type.core == true

  nats_exporter:
    image: appcelerator/prometheus-nats-exporter:0.17.0
    networks:
      - monit
      - core
    command: ["-varz", "-routez", "-connz", "-subz", "nats,http://nats:8222"]
    #ports:
      #- target: 7777
      #- published: 7777
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "20s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.metrics.port: "7777"
        io.amp.metrics.mode: "exporter"
      placement:
        constraints:
        - node.labels.amp.type.core == true

  nodes:
    image: prom/node-exporter:v0.15.1
    networks:
      - monit
      - core
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #ports:
    #  - "9100:9100"
    command: [ "--path.procfs", "/host/proc", "--path.sysfs", "/host/sys", "--collector.filesystem.ignored-mount-points", "^/(sys|proc|dev|host|etc|var|rootfs/var/lib/docker|rootfs/run/docker/netns|rootfs/sys/kernel/debug)($$|/)"]
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "20s"
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
        io.amp.metrics.port: "9100"

  alertmanager:
    image: prom/alertmanager:v0.10.0
    networks:
      - core
    volumes:
      - alertmanager-data:/alertmanager
    ports:
      - "9093:9093"
    environment:
      VIRTUAL_HOST: "https://alertmanager.*,alertmanager.*"
      SERVICE_PORTS: "9093"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "30s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.core == true
    secrets:
      - source: alertmanager_yml
        target: alertmanager.yml
        mode: 0400
    command: [ "-config.file=/run/secrets/alertmanager.yml",
             "-storage.path=/alertmanager",
             "-web.external-url=http://localhost:9093" ]

  grafana:
    image: appcelerator/grafana-amp:1.2.9
    networks:
      - core
      - public
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      SERVICE_PORTS: 3000
      VIRTUAL_HOST: "http://dashboard.*,https://dashboard.*"
    ports:
      - "3000:3000"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "8s"
      amp.service.stabilize.timeout: "60s"
      amp.service.pull.timeout: "120s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.core == true
