version: "3"

networks:
  public:
    external: true

services:

  visualizer:
    image: dockersamples/visualizer
    networks:
      - public
    environment:
      SERVICE_PORTS: "8080"
      VIRTUAL_HOST: "http://visualizer.*,https://visualizer.*"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer
    networks:
      - public
    environment:
      SERVICE_PORTS: "9000"
      VIRTUAL_HOST: "http://portainer.*,https://portainer.*"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
