version: "2"
services:
  zookeeper:
    image: appcelerator/zookeeper:3.4.8
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: appcelerator/kafka:10.0.0.1
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      TOPIC_LIST: "telegraf"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  telegraf-agent:
    image: appcelerator/telegraf
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    environment:
      OUTPUT_INFLUXDB_ENABLED: "false"
      OUTPUT_KAFKA_ENABLED: "true"
      OUTPUT_KAFKA_BROKER_URL: "kafka:9092"
      OUTPUT_KAFKA_TOPIC: "telegraf"
      INPUT_DOCKER_ENABLED: "false"
      INPUT_CPU_ENABLED: "false"
      INPUT_DISK_ENABLED: "false"
      INPUT_DISKIO_ENABLED: "false"
      INPUT_KERNEL_ENABLED: "false"
      INPUT_MEM_ENABLED: "false"
      INPUT_PROCESS_ENABLED: "false"
      INPUT_SWAP_ENABLED: "false"
      INPUT_SYSTEM_ENABLED: "false"
      INPUT_NETSTAT_ENABLED: "false"
      INPUT_NET_ENABLED: "false"
      INPUT_LISTENER_ENABLED: "true"
      INTERVAL: 2s
      FLUSH_INTERVAL: 2s
      FLUSH_JITTER: 0s
    depends_on:
      - kafka
      - zookeeper

  telegraf-consumer:
    image: appcelerator/telegraf
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/docker-compose-telegraf-output:/var/data
    environment:
      OUTPUT_INFLUXDB_ENABLED: "false"
      OUTPUT_FILE_ENABLED: "true"
      OUTPUT_FILE_PATH: "/var/data/output.dat"
      INPUT_KAFKA_ENABLED: "true"
      INPUT_KAFKA_BROKER_URL: "kafka:9092"
      INPUT_KAFKA_ZOOKEEPER_PEER: "zookeeper:2181"
      INPUT_KAFKA_TOPIC: "telegraf"
      INPUT_DOCKER_ENABLED: "false"
      INPUT_CPU_ENABLED: "false"
      INPUT_DISK_ENABLED: "false"
      INPUT_DISKIO_ENABLED: "false"
      INPUT_KERNEL_ENABLED: "false"
      INPUT_MEM_ENABLED: "false"
      INPUT_PROCESS_ENABLED: "false"
      INPUT_SWAP_ENABLED: "false"
      INPUT_SYSTEM_ENABLED: "false"
      INPUT_NETSTAT_ENABLED: "false"
      INPUT_NET_ENABLED: "false"
      INPUT_LISTENER_ENABLED: "fase"
      INTERVAL: 2s
      FLUSH_INTERVAL: 2s
      FLUSH_JITTER: 0s
    command: ["-m", "restart"]
    depends_on:
      - kafka

  sut:
    image: appcelerator/sut
    build:
      context: ./sut
      dockerfile: Dockerfile
    command: ["/bin/test-queue.sh", "16"]
    volumes:
      - /tmp/docker-compose-telegraf-output:/var/data
      - /var/run/docker.sock:/var/run/docker-host.sock:ro
    depends_on:
      - telegraf-agent
      - telegraf-consumer
      - kafka
      - zookeeper
