version: "2"
services:
  telegraf:
    image: appcelerator/telegraf
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8094:8094"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
      - /tmp/docker-compose-telegraf-output:/var/data
    environment:
      OUTPUT_INFLUXDB_ENABLED: "false"
      OUTPUT_FILE_ENABLED: "true"
      OUTPUT_FILE_PATH: "/var/data/output.dat"
      INPUT_DOCKER_ENABLED: "true"
      INPUT_LISTENER_ENABLED: "true"
    labels:
      - "ServiceUUId=system.telegraf"
      - "io.appcelerator.amp.build.mounts=/var/run/docker.sock,/var/run/utmp,/tmp/docker-compose-telegraf-output:/var/data"

  sut:
    image: appcelerator/sut
    build:
      context: ./sut
      dockerfile: Dockerfile
    volumes:
      - /tmp/docker-compose-telegraf-output:/var/data
      - /var/run/docker.sock:/var/run/docker-host.sock:ro
    labels:
      - "io.appcelerator.amp.build.mounts=/tmp/docker-compose-telegraf-output:/var/data,/var/run/docker.sock:/var/run/docker-host.sock"
