version: "2"
services:

  nats:
    image: appcelerator/amp-nats-streaming:0.3.0
    command: ["-DV"]
    ports:
      - "4222:4222"
      - "8222:8222"

  telegraf-agent:
    image: appcelerator/telegraf
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8094:8094"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    environment:
      DEBUG_MODE: "true"
      OUTPUT_INFLUXDB_ENABLED: "false"
      OUTPUT_NATS_ENABLED: "true"
      OUTPUT_KAFKA_ENABLED: "false"
      OUTPUT_NATS_URL: "nats://nats:4222"
      OUTPUT_NATS_SUBJECT: "telegraf"
      INPUT_DOCKER_ENABLED: "false"
      INPUT_CPU_ENABLED: "false"
      INPUT_DISK_ENABLED: "false"
      INPUT_DISKIO_ENABLED: "false"
      INPUT_KERNEL_ENABLED: "false"
      INPUT_MEM_ENABLED: "false"
      INPUT_PROCESS_ENABLED: "false"
      INPUT_SWAP_ENABLED: "false"
      INPUT_SYSTEM_ENABLED: "false"
      INPUT_NETSTAT_ENABLED: "false"
      INPUT_NET_ENABLED: "false"
      INPUT_LISTENER_ENABLED: "true"
      INTERVAL: 2s
      FLUSH_INTERVAL: 2s
      FLUSH_JITTER: 0s

  telegraf-consumer:
    image: appcelerator/telegraf
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/docker-compose-telegraf-output:/var/data
    environment:
      DEBUG_MODE: "true"
      OUTPUT_INFLUXDB_ENABLED: "false"
      OUTPUT_FILE_ENABLED: "true"
      OUTPUT_FILE_PATH: "/var/data/output.dat"
      OUTPUT_NATS_ENABLED: "false"
      INPUT_KAFKA_ENABLED: "false"
      INPUT_NATS_ENABLED: "true"
      INPUT_NATS_URL: "nats://nats:4222"
      INPUT_NATS_SUBJECT: "telegraf"
      INPUT_DOCKER_ENABLED: "false"
      INPUT_CPU_ENABLED: "false"
      INPUT_DISK_ENABLED: "false"
      INPUT_DISKIO_ENABLED: "false"
      INPUT_KERNEL_ENABLED: "false"
      INPUT_MEM_ENABLED: "false"
      INPUT_PROCESS_ENABLED: "false"
      INPUT_SWAP_ENABLED: "false"
      INPUT_SYSTEM_ENABLED: "false"
      INPUT_NETSTAT_ENABLED: "false"
      INPUT_NET_ENABLED: "false"
      INPUT_LISTENER_ENABLED: "false"
      METRIC_BUFFER_LIMIT: 5000
      INTERVAL: 3s
      FLUSH_INTERVAL: 3s
      FLUSH_JITTER: 0s
    command: ["-m", "restart"]
    depends_on:
      - nats

  sut:
    image: appcelerator/sut
    build:
      context: ./sut
      dockerfile: Dockerfile
    command: ["/bin/test-queue.sh"]
    volumes:
      - /tmp/docker-compose-telegraf-output:/var/data
      - /var/run/docker.sock:/var/run/docker-host.sock:ro
    depends_on:
      - telegraf-agent
      - telegraf-consumer
      - nats
