// Code generated by protoc-gen-go.
// source: github.com/appcelerator/amp/data/accounts/accounts.proto
// DO NOT EDIT!

/*
Package accounts is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/data/accounts/accounts.proto

It has these top-level messages:
	User
	Team
	OrganizationMember
	Organization
	Account
*/
package accounts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrganizationRole int32

const (
	OrganizationRole_ORGANIZATION_MEMBER OrganizationRole = 0
	OrganizationRole_ORGANIZATION_OWNER  OrganizationRole = 1
)

var OrganizationRole_name = map[int32]string{
	0: "ORGANIZATION_MEMBER",
	1: "ORGANIZATION_OWNER",
}
var OrganizationRole_value = map[string]int32{
	"ORGANIZATION_MEMBER": 0,
	"ORGANIZATION_OWNER":  1,
}

func (x OrganizationRole) String() string {
	return proto.EnumName(OrganizationRole_name, int32(x))
}
func (OrganizationRole) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AccountType int32

const (
	AccountType_USER         AccountType = 0
	AccountType_ORGANIZATION AccountType = 1
)

var AccountType_name = map[int32]string{
	0: "USER",
	1: "ORGANIZATION",
}
var AccountType_value = map[string]int32{
	"USER":         0,
	"ORGANIZATION": 1,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (AccountType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type User struct {
	Name         string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email        string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	PasswordHash string `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash" json:"password_hash,omitempty"`
	IsVerified   bool   `protobuf:"varint,4,opt,name=is_verified,json=isVerified" json:"is_verified,omitempty"`
	CreateDt     int64  `protobuf:"varint,5,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *User) GetIsVerified() bool {
	if m != nil {
		return m.IsVerified
	}
	return false
}

func (m *User) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

type Team struct {
	Name     string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CreateDt int64    `protobuf:"varint,2,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
	Members  []string `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
}

func (m *Team) Reset()                    { *m = Team{} }
func (m *Team) String() string            { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()               {}
func (*Team) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

func (m *Team) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

type OrganizationMember struct {
	Name string           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Role OrganizationRole `protobuf:"varint,2,opt,name=role,enum=accounts.OrganizationRole" json:"role,omitempty"`
}

func (m *OrganizationMember) Reset()                    { *m = OrganizationMember{} }
func (m *OrganizationMember) String() string            { return proto.CompactTextString(m) }
func (*OrganizationMember) ProtoMessage()               {}
func (*OrganizationMember) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OrganizationMember) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrganizationMember) GetRole() OrganizationRole {
	if m != nil {
		return m.Role
	}
	return OrganizationRole_ORGANIZATION_MEMBER
}

type Organization struct {
	Name     string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email    string                `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	CreateDt int64                 `protobuf:"varint,3,opt,name=create_dt,json=createDt" json:"create_dt,omitempty"`
	Members  []*OrganizationMember `protobuf:"bytes,4,rep,name=members" json:"members,omitempty"`
	Teams    []*Team               `protobuf:"bytes,5,rep,name=teams" json:"teams,omitempty"`
}

func (m *Organization) Reset()                    { *m = Organization{} }
func (m *Organization) String() string            { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()               {}
func (*Organization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Organization) GetCreateDt() int64 {
	if m != nil {
		return m.CreateDt
	}
	return 0
}

func (m *Organization) GetMembers() []*OrganizationMember {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Organization) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

type Account struct {
	Type AccountType `protobuf:"varint,1,opt,name=type,enum=accounts.AccountType" json:"type,omitempty"`
	Name string      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Account) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_USER
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "accounts.User")
	proto.RegisterType((*Team)(nil), "accounts.Team")
	proto.RegisterType((*OrganizationMember)(nil), "accounts.OrganizationMember")
	proto.RegisterType((*Organization)(nil), "accounts.Organization")
	proto.RegisterType((*Account)(nil), "accounts.Account")
	proto.RegisterEnum("accounts.OrganizationRole", OrganizationRole_name, OrganizationRole_value)
	proto.RegisterEnum("accounts.AccountType", AccountType_name, AccountType_value)
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/data/accounts/accounts.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0xb6, 0xb4, 0xb8, 0x70, 0x40, 0xd2, 0x8c, 0x7f, 0x13, 0x35, 0xb1, 0xa9, 0x5e, 0x74, 0xf7,
	0x02, 0x12, 0x4c, 0x8c, 0xb7, 0xa8, 0xc4, 0xdd, 0x0b, 0x20, 0x8e, 0xac, 0x1a, 0x6f, 0xc8, 0xa1,
	0x1c, 0x97, 0x49, 0x18, 0xa6, 0x99, 0x99, 0xd5, 0xac, 0xaf, 0xe1, 0xa3, 0xf8, 0x82, 0xc6, 0xe9,
	0xf2, 0x53, 0xc2, 0x8d, 0x77, 0x73, 0xbe, 0x9f, 0x9e, 0xf3, 0x7d, 0x29, 0xbc, 0xb9, 0x92, 0x6e,
	0x79, 0x3d, 0xef, 0xe6, 0x5a, 0xf5, 0xb0, 0x28, 0x72, 0x5a, 0x91, 0x41, 0xa7, 0x4d, 0x0f, 0x55,
	0xd1, 0x5b, 0xa0, 0xc3, 0x1e, 0xe6, 0xb9, 0xbe, 0x5e, 0x3b, 0xbb, 0x7d, 0x74, 0x0b, 0xa3, 0x9d,
	0x66, 0x8d, 0xcd, 0x9c, 0xfe, 0x0e, 0x20, 0xba, 0xb4, 0x64, 0x18, 0x83, 0x68, 0x8d, 0x8a, 0x78,
	0x90, 0x04, 0x59, 0x53, 0xf8, 0x37, 0x7b, 0x00, 0x75, 0x52, 0x28, 0x57, 0xbc, 0xe6, 0xc1, 0x72,
	0x60, 0x2f, 0xe0, 0x5e, 0x81, 0xd6, 0xfe, 0xd4, 0x66, 0x31, 0x5b, 0xa2, 0x5d, 0xf2, 0xd0, 0xb3,
	0xed, 0x0d, 0x78, 0x8e, 0x76, 0xc9, 0x9e, 0x43, 0x4b, 0xda, 0xd9, 0x0f, 0x32, 0xf2, 0xbb, 0xa4,
	0x05, 0x8f, 0x92, 0x20, 0x6b, 0x08, 0x90, 0xf6, 0xf3, 0x2d, 0xc2, 0x9e, 0x42, 0x33, 0x37, 0x84,
	0x8e, 0x66, 0x0b, 0xc7, 0xeb, 0x49, 0x90, 0x85, 0xa2, 0x51, 0x02, 0xef, 0x5d, 0xfa, 0x11, 0xa2,
	0x29, 0xa1, 0x3a, 0x7a, 0x54, 0xc5, 0x58, 0xab, 0x1a, 0x19, 0x87, 0x13, 0x45, 0x6a, 0x4e, 0xc6,
	0xf2, 0x30, 0x09, 0xb3, 0xa6, 0xd8, 0x8c, 0xe9, 0x57, 0x60, 0x13, 0x73, 0x85, 0x6b, 0xf9, 0x0b,
	0x9d, 0xd4, 0xeb, 0x91, 0x87, 0x8f, 0x2e, 0xe8, 0x42, 0x64, 0xf4, 0x8a, 0xfc, 0xb7, 0x3b, 0xfd,
	0x27, 0xdd, 0x6d, 0x77, 0xfb, 0x7e, 0xa1, 0x57, 0x24, 0xbc, 0x2e, 0xfd, 0x13, 0x40, 0x7b, 0x9f,
	0xfa, 0x8f, 0x2a, 0x2b, 0x59, 0xc2, 0x83, 0x2c, 0xaf, 0x77, 0x59, 0xa2, 0x24, 0xcc, 0x5a, 0xfd,
	0x67, 0xc7, 0x4f, 0x29, 0xa3, 0x6c, 0x93, 0xb2, 0x97, 0x50, 0x77, 0x84, 0xca, 0xf2, 0xba, 0x77,
	0x75, 0x76, 0xae, 0x7f, 0x9d, 0x8a, 0x92, 0x4c, 0xcf, 0xe1, 0x64, 0x50, 0xe2, 0xec, 0x14, 0x22,
	0x77, 0x53, 0x94, 0xf7, 0x76, 0xfa, 0x0f, 0x77, 0xfa, 0x5b, 0xc1, 0xf4, 0xa6, 0x20, 0xe1, 0x25,
	0xdb, 0x68, 0xb5, 0x5d, 0xb4, 0xb3, 0x77, 0x10, 0x1f, 0x36, 0xc3, 0x1e, 0xc3, 0xfd, 0x89, 0xf8,
	0x30, 0x18, 0x5f, 0x7c, 0x1b, 0x4c, 0x2f, 0x26, 0xe3, 0xd9, 0x68, 0x38, 0x7a, 0x3b, 0x14, 0xf1,
	0x1d, 0xf6, 0x08, 0x58, 0x85, 0x98, 0x7c, 0x19, 0x0f, 0x45, 0x1c, 0x9c, 0x9d, 0x42, 0x6b, 0x6f,
	0x1b, 0x6b, 0x40, 0x74, 0xf9, 0xc9, 0x1b, 0x62, 0x68, 0xef, 0x1b, 0xe2, 0x60, 0x7e, 0xd7, 0xff,
	0xc3, 0xaf, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x18, 0x34, 0x87, 0xff, 0x02, 0x00, 0x00,
}
