#!/bin/bash
set -e

TAGS=( latest 1.5 1.5.0 )
OWNER=appcelerator
IMAGE=amptools

docker build -t ${OWNER}/${IMAGE} .

for tag in "${TAGS[@]}"
do
  docker tag ${OWNER}/${IMAGE} ${OWNER}/${IMAGE}:${tag}
  docker push ${OWNER}/${IMAGE}:${tag}
done

