version: "3"

services:
    db:
        image: 'postgres:9.4'
    redis:
        image: 'redis:latest'
    result:
        image: 'danjng/example-voting-app-result:latest'
        deploy:
            labels:
                io.amp.label: "results:80"
        networks:
            - public 
    vote:
        image: 'docker/example-voting-app-vote:latest'
        deploy:
            replicas: 5
            labels:
                io.amp.label: "vote:80"
    worker:
        image: 'docker/example-voting-app-worker:latest'
        deploy:
            replicas: 3

networks:
    public:
        external:
            name: ampcore_public            
