version: "3"

services:
    bash-server:
        image: 'registry.local.appcelerator.io/ws-bash-server'
        deploy:
            labels:
                io.amp.mapping: "ws:4000"
    web:
        image: 'registry.local.appcelerator.io/ws-bash-web'
        deploy:
            labels:
                io.amp.mapping: "web:80"

networks:
    public:
        external:
            name: ampcore_public