version: "3.1"

networks:
  default:
    external:
      name: ampnet

volumes:
  elasticsearch-data:
  etcd-data:

services:

  elasticsearch:
    image: appcelerator/elasticsearch-amp:5.4.2
    networks:
      - default
    volumes:
      - elasticsearch-data:/opt/elasticsearch-5.4.2/data
    labels:
      io.amp.role: "infrastructure"
    environment:
      NETWORK_HOST: "_eth0_"
      JAVA_HEAP_SIZE: "${ES_JAVA_HEAP_SIZE:-1024}"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.search == true

  nats:
    image: appcelerator/amp-nats-streaming:v0.5.0
    networks:
      - default
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.mq == true

  etcd:
    image: appcelerator/etcd:3.1.9
    networks:
      - default
    volumes:
      - etcd-data:/data
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 1
    command:
      - "--advertise-client-urls"
      - "http://etcd:2379"
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.kv == true
