version: "3"

networks:
  default:
    external:
      name: ampnet

volumes:
  logstash-data:

services:

  logstash:
    image: appcelerator/amp-logstash:5.5.0
    networks:
      - default
    volumes:
      - logstash-data:/usr/share/logstash/data
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.core == true

  ampbeat:
    image: appcelerator/ampbeat:${TAG:-0.13.1}
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.core == true
    labels:
      io.amp.role: "infrastructure"

  kibana:
    image: appcelerator/kibana:5.5.0
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.mapping: "kibana:5601"
      placement:
        constraints:
        - node.labels.amp.type.core == true
    labels:
      io.amp.role: "infrastructure"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      SERVICE_PORTS: 5601
      VIRTUAL_HOST: "http://kibana.*,https://kibana.*"
