version: "3.2"

networks:
  default:
    external:
      name: ampnet

volumes:
  prometheus:

services:

  elasticsearch:
    image: appcelerator/elasticsearch-amp:5.3.2
    networks:
      - default
    labels:
      io.amp.role: "infrastructure"
    environment:
      NETWORK_HOST: "_eth0_"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.search == true

  nats:
    image: appcelerator/amp-nats-streaming:v0.3.8
    networks:
      default:
        aliases:
          - nats
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.mq == true

  etcd:
    image: appcelerator/etcd:3.1.6
    networks:
      default:
        aliases:
          - etcd
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 1
    command:
      - "--advertise-client-urls"
      - "http://etcd:2379"
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.kv == true

  prometheus:
    image: prom/prometheus
    networks:
      default:
        aliases:
          - prometheus
    volumes:
      - prometheus:/etc/prometheus
    ports:
      - target: 9090
        published: 9090
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.metrics == true
