version: "3.2"

networks:
  default:
    external:
      name: ampnet

services:

  elasticsearch:
    image: appcelerator/elasticsearch-amp:5.3.2
    networks:
      - default
    labels:
      io.amp.role: "infrastructure"
    environment:
      MIN_MASTER_NODES: 2
      NETWORK_HOST: "_eth0_"
      UNICAST_HOSTS: "tasks.elasticsearch"
    deploy:
      mode: replicated
      replicas: 3
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.search == true

  nats:
    image: appcelerator/amp-nats-streaming:v0.4.0
    networks:
      default:
        aliases:
          - nats
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.mq == true

  etcd:
    image: appcelerator/etcd:3.1.8
    networks:
      default:
        aliases:
          - etcd
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 3
    command:
      - "--advertise-client-urls"
      - "http://etcd:2379"
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: replicated
      replicas: 3
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.kv == true
