version: "3.1"

networks:
  proxy:
  monitoring-public:
  logs-public:
  core-public:
  portal-public:
  default:
    external:
      name: ampnet

secrets:
  certificate_atomiq:
    external: true

services:

  proxy:
    image: dockercloud/haproxy
    networks:
    - proxy
    - monitoring-public
    - logs-public
    - core-public
    - portal-public
    - default
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 2s
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.route == true
    environment:
      CERT_FOLDER: "/run/secrets"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.amp.role: "infrastructure"
    ports:
      - "80:80"
      - "443:443"
      - "1936:1936"
    secrets:
      - source: certificate_atomiq
        target: cert0.pem
        mode: 0400
