version: "3"

networks:
  default:
    external:
      name: ampnet
  infrastructure:

services:

  visualizer:
    image: manomarks/visualizer
    networks:
      - default
    ports:
      - "50180:8080/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer
    networks:
      - default
    ports:
      - "50190:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  amp-ui:
    image: appcelerator/amp-ui:1.0.0
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    environment:
      SERVICE_PORTS: "3333"
      VIRTUAL_HOST: "http://ui.*,https://ui.*"
      FORCE_SSL: 1
      LOCAL_ENDPOINT: "true"
      ENDPOINTS: "cloud.atomiq.io"
    labels:
      io.amp.role: "infrastructure"
