version: "3"

networks:
  default:
    external:
      name: ampnet
  infrastructure:

services:

  portal:
    image: appcelerator/amp-portal:${TAG:-0.10.1}
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    environment:
      SERVICE_PORTS: "3333"
      VIRTUAL_HOST: "http://ui.*,https://ui.*,http://cloud.*,http://local.*,https://cloud.*,https://local.*"
      FORCE_SSL: 1
    labels:
      io.amp.role: "infrastructure"
