version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  visualizer:
    image: manomarks/visualizer
    networks:
      - default
    environment:
      SERVICE_PORTS: "8080"
      VIRTUAL_HOST: "http://visualizer,https://visualizer.*"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer
    networks:
      - default
    environment:
      SERVICE_PORTS: "9000"
      VIRTUAL_HOST: "http://portainer.*,https://portainer.*"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
