version: "3.3"

networks:
  public:
    external: true
  db:
    driver: overlay

services:
  consul:
    image: consul:1.0.1
    networks:
      - db
      - public
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      placement:
        constraints:
          - node.labels.amp.type.user == true
    environment:
      SERVICE_PORTS: 8500
      VIRTUAL_HOST: "https://consul.examples.*,consul.examples.*"
      CONSUL_BIND_INTERFACE: "eth0"
      CONSUL_CLIENT_INTERFACE: "eth0"
    command: ["agent", "-server", "-client=0.0.0.0", "-ui", "-bootstrap-expect=3", "-retry-join=consul"]
