#!/bin/bash

SYNC=${SYNC:-false}
SYSTEM_PRUNE=${SYSTEM_PRUNE:-false}
#SIGNAL_URL=
LABELS=${LABELS:-amp.type.user=true amp.type.core=true amp.type.search=true amp.type.mq=true amp.type.kv=true amp.type.metrics=true}
CHANNEL=${CHANNEL:-stable}
#PLUGINS=
REGION=${REGION:-us-west-2}
STACK_NAME=${STACK_NAME:-unset}
VPC_ID=${VPC_ID:-unset}
#DOCKER_DEVICE=/dev/sdl
SYSTEMD_DOCKER_OVERRIDE=/etc/systemd/system/docker.service.d/docker.conf
SYSV_DOCKER_DEFAULT=/etc/default/docker
#LEADER=

_init_system(){
  systemctl --version >/dev/null 2>&1 && echo systemd && return
  [[ `/sbin/init --version` =~ upstart ]] && echo upstart && return
  echo sysv
}

_install_docker(){
  local _release=$(lsb_release -is)
  local _host
  # on Debian style systems, this checks that docker-ce is installed
  grep -A1 docker-ce /var/lib/dpkg/status | grep -q "installed$"
  if [[ $? -ne 0 ]]; then
    case $CHANNEL in
    stable) _host="get.docker.com" ;;
    edge|beta|test) _host="test.docker.com" ;;
    experimental) _host="experimental.docker.com" ;;
    *) return 1 ;;
    esac
    echo "installing Docker from $_host" >&2
    wget -qO- "https://$_host/" | sh || return 1
  fi
  [[ "x$_release" = "xUbuntu" ]] && usermod -G docker ubuntu 2>/dev/null
  [[ "x$_release" = "xDebian" ]] && usermod -G docker admin  2>/dev/null
  if [[ $(_init_system) = "systemd" ]]; then
    systemctl enable docker.service
    docker version -f {{.Server.Version}} &>/dev/null || systemctl start docker.service
  else
    chkconfig docker on
    docker version -f {{.Server.Version}} &>/dev/null || service docker start
  fi
  docker version >&2
}

# install Docker plugins
# specification of a plugin is in the form PluginName:Version#Options
# plugin specifications should be space separated
_install_plugins(){
  local plugin
  local alias
  local options
  for plugin in $PLUGINS; do
    options="${plugin#*#}"
    [[ "x$options" = "x$plugin" ]] && options="" || options="${options//#/ }"
    plugin="${plugin%%#*}"
    alias=${plugin#store/}
    alias=${alias%:*}
    docker plugin install "$plugin" $options --alias "$alias" --grant-all-permissions # || return 1
  done
  return 0
}

_configure_system_prune(){
  local _cmd="docker system prune -af"
  local _cron_spec="@hourly"

  [[ "x$SYSTEM_PRUNE" != x@(true|yes) ]] && return 0
  echo "configuring crontab for system prune" >&2
  (crontab -l 2>/dev/null; echo "$_cron_spec $_cmd") | crontab -
}

_restart_docker(){
  echo "restarting Docker" >&2
  if [[ $(_init_system) = "systemd" ]]; then
    systemctl restart docker.service
  else
    service docker restart
  fi
}

_sanity_check(){
  which aws >/dev/null || return 1
  which jq >/dev/null || return 1
}

# installs the cfn tools, to be able to signal AWS that the application part of the deployment is done
_install_helpers(){
  [[ "x$SYNC" != "xtrue" ]] && return 0
  [[ -x /usr/local/bin/cfn-signal ]] && return 0
  python -c "import pkg_resources" || curl https://bootstrap.pypa.io/ez_setup.py | python
  curl -sSf https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xzf -
  (cd aws-cfn-bootstrap-[0-9.]* && python setup.py install) || return 1
  rm -rf aws-cfn-bootstrap-[0-9.]*
  [[ -x /usr/local/bin/cfn-signal ]]
}

_stop_docker(){
  if [[ $(_init_system) = "systemd" ]]; then
    systemctl stop docker.service &>/dev/null
  else
    service docker stop &>/dev/null
  fi
}

_mount_docker_volume(){
  local _mount_point="/var/lib/docker"
  local _device
  local _fstype=xfs
  [[ -z "$1" ]] && return 0
  _device=$(echo $1 | sed 's/\/sd/\/xvd/')
  mkfs.$_fstype $_device || return 1
  echo "$_device    $_mount_point   $_fstype    defaults    0    2" >> /etc/fstab
  rm -rf "$_mount_point"
  mkdir -p "$_mount_point"
  mount "$_mount_point"
}

_system_prerequisites(){
  typeset -i mmc
  local mmcmin=262144
  if mmc=$(sysctl -n vm.max_map_count 2>/dev/null); then
    if [[ $mmc -lt $mmcmin ]]; then
      echo "setting vm.max_map_count to a safe value for elasticsearch"
      sysctl -w vm.max_map_count=262144 || return 1
      echo "vm.max_map_count = 262144" > /etc/sysctl.d/99-amp.conf
    fi
  else
    return 1
  fi
}

# update the docker daemon configuration with the mirror registries
_set_mirror_registries(){
  local _registries="$*"
  local _registry
  local _tmp
  if [[ ! -f /etc/docker/daemon.json ]]; then
    echo "{}" > /etc/docker/daemon.json
  fi
  _tmp=$(mktemp)
  for _registry in $_registries; do
    # Docker pull only accept lower case names,
    # so it's safer to use lower case also in the registry mirror list
    _registry=$(echo "$_registry" | tr '[:upper:]' '[:lower:]'})
    if ! echo "$_registry" | grep -q "://" ; then
      echo "$_registry should contain a scheme, ignore" >&2
      continue
    fi
    echo "adding registry $_registry" >&2
    cat /etc/docker/daemon.json | jq ".[\"registry-mirrors\"] |= .+ [\"$_registry\"]" > "$_tmp" || return 1
    mv "$_tmp" /etc/docker/daemon.json
    if echo "$_registry" | grep -q "http://" ; then
      # declare it as insecure registry
      cat /etc/docker/daemon.json | jq ".[\"insecure-registries\"] |= .+ [\"${_registry}\"]" > "$_tmp" || return 1
      mv "$_tmp" /etc/docker/daemon.json
    fi
  done
}

_set_log_rotation(){
  local _max_size=${1:-10m}
  local _max_file=${2:-3}
  if [[ ! -f /etc/docker/daemon.json ]]; then
    echo "{}" > /etc/docker/daemon.json
  fi
  _tmp=$(mktemp)
  echo "setting log rotation" >&2
  cat /etc/docker/daemon.json | jq ".\"log-opts\".\"max-size\" = \"$_max_size\" | .\"log-opts\".\"max-file\" = \"$_max_file\"" > "$_tmp" || return 1
  mv "$_tmp" /etc/docker/daemon.json
}

_set_metrics_address(){
  local _host=${1:-127.0.0.1}
  local _port=${2:-9323}
  if [[ ! -f /etc/docker/daemon.json ]]; then
    echo "{}" > /etc/docker/daemon.json
  fi
  # multihost bridge is most probably 172.18.0.1
  if [[ "$_host" = "bridge" ]]; then
    _host=$(ip route show dev docker_gwbridge | sed 's/.*src \([0-9\.]*\).*/\1/')
    [[ -z "$_host" ]] && _host=0.0.0.0
  fi
  _tmp=$(mktemp)
  echo "setting the metrics address ($_host:$_port)" >&2
  cat /etc/docker/daemon.json | jq ".\"metrics-addr\" = \"${_host}:${_port}\" | .experimental = true" > "$_tmp" || return 1
  mv "$_tmp" /etc/docker/daemon.json
}

_get_worker_join_token(){
  local _manager=$1
  local _loop=0
  local _timeout=900
  local _token
  echo "retrieving the swarm worker token (will timeout after $_timeout s)" >&2
  SECONDS=0
  while [[ $SECONDS -lt $_timeout ]]; do
    _token=$(docker -H "$_manager:2375" swarm join-token -q worker)
    if [[ $? -eq 0 && -n "$_token" ]]; then
      echo "worker token obtained ($SECONDS s)" >&2
      echo $_token
      return 0
    fi
    sleep 2
  done
  echo "timeout" >&2
  return 1
}

_swarm_join(){
  local _manager=$1
  local _token
  if [[ -n "$_manager" ]]; then
    _token=$(_get_worker_join_token "$_manager") || return 1
  else
    # infrakit mode
    _manager="{{ SPEC.SwarmJoinIP }}"
    _token="{{ SWARM_JOIN_TOKENS.Worker }}"
  fi
  echo "joining the Swarm" >&2
  docker swarm join --token "$_token" "${_manager}:2377"
}

# add labels on the Swarm node
# TODO: should be done by InfraKit, not by the node itself
_label_node(){
  local _manager=$1
  local _self
  local _publicip
  [[ -z "$_manager" ]] && return 0
  _self=$(docker info -f '{{.Swarm.NodeID}}') || return 1
  _publicip=$(curl -sf 169.254.169.254/latest/meta-data/public-ipv4) || return 1
  echo "applying label PublicIP=$_publicip" >&2
  docker -H "$_manager" node update --label-add "PublicIP=$_publicip" "$_self" >/dev/null || return 1
  for _label in $LABELS; do
    echo "applying label $_label" >&2
    docker -H "$_manager" node update --label-add "${_label}" "$_self" >/dev/null || return 1
  done
}

_get_node_ip(){
  local _myip
  _myip=$(curl 169.254.169.254/latest/meta-data/local-ipv4)
  echo $_myip
}

_smoke_test(){
  local _state
  SECONDS=0
  while [[ $SECONDS -lt 10 ]]; do
    _state=$(docker info -f '{{.Swarm.LocalNodeState}}')
    [[ "x$_state" = "xactive" ]] && return 0
    sleep 1
  done
  echo "smoke tests fail:" >&2
  docker info -f '{{.Swarm.LocalNodeState}}' >&2
  return 1
}

_signal_aws() {
  [[ "x$SYNC" != "xtrue" ]] && return 0
  [[ -x /usr/local/bin/cfn-signal ]] || return 1
  /usr/local/bin/cfn-signal --stack "${STACK_NAME}" --region "${REGION}" --success true "${SIGNAL_URL}"
  return 0
}

_sanity_check || exit 1
_install_helpers || exit 1
_stop_docker
_mount_docker_volume $DOCKER_DEVICE || exit 1
_system_prerequisites || exit 1
nodeip=$(_get_node_ip)
_install_docker || exit 1
_install_plugins || exit 1
_set_mirror_registries "$MIRROR_REGISTRIES" || exit 1
_set_log_rotation "10m" "3" || exit 1
_set_metrics_address "bridge" "9323" || exit 1
_restart_docker || exit 1
_swarm_join "$LEADER" || exit 1
_label_node "$LEADER" || exit 1
_configure_system_prune || exit 1
_smoke_test || exit 1
_signal_aws
