// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/appcelerator/amp/api/rpc/resource/resource.proto

/*
Package resource is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/resource/resource.proto

It has these top-level messages:
	ResourceEntry
	ListRequest
	ListReply
	AddToTeamRequest
	RemoveFromTeamRequest
	ChangePermissionLevelRequest
*/
package resource

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import accounts "github.com/appcelerator/amp/data/accounts"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResourceType int32

const (
	ResourceType_RESOURCE_STACK        ResourceType = 0
	ResourceType_RESOURCE_DASHBOARD    ResourceType = 1
	ResourceType_RESOURCE_USER         ResourceType = 2
	ResourceType_RESOURCE_ORGANIZATION ResourceType = 3
	ResourceType_RESOURCE_TEAM         ResourceType = 4
)

var ResourceType_name = map[int32]string{
	0: "RESOURCE_STACK",
	1: "RESOURCE_DASHBOARD",
	2: "RESOURCE_USER",
	3: "RESOURCE_ORGANIZATION",
	4: "RESOURCE_TEAM",
}
var ResourceType_value = map[string]int32{
	"RESOURCE_STACK":        0,
	"RESOURCE_DASHBOARD":    1,
	"RESOURCE_USER":         2,
	"RESOURCE_ORGANIZATION": 3,
	"RESOURCE_TEAM":         4,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}
func (ResourceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Action int32

const (
	Action_ACTION_CREATE Action = 0
	Action_ACTION_READ   Action = 1
	Action_ACTION_UPDATE Action = 2
	Action_ACTION_DELETE Action = 3
)

var Action_name = map[int32]string{
	0: "ACTION_CREATE",
	1: "ACTION_READ",
	2: "ACTION_UPDATE",
	3: "ACTION_DELETE",
}
var Action_value = map[string]int32{
	"ACTION_CREATE": 0,
	"ACTION_READ":   1,
	"ACTION_UPDATE": 2,
	"ACTION_DELETE": 3,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}
func (Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ResourceEntry struct {
	Id    string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type  ResourceType      `protobuf:"varint,2,opt,name=type,enum=resource.ResourceType" json:"type,omitempty"`
	Name  string            `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Owner *accounts.Account `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
}

func (m *ResourceEntry) Reset()                    { *m = ResourceEntry{} }
func (m *ResourceEntry) String() string            { return proto.CompactTextString(m) }
func (*ResourceEntry) ProtoMessage()               {}
func (*ResourceEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResourceEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ResourceEntry) GetType() ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceType_RESOURCE_STACK
}

func (m *ResourceEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResourceEntry) GetOwner() *accounts.Account {
	if m != nil {
		return m.Owner
	}
	return nil
}

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ListReply struct {
	Resources []*ResourceEntry `protobuf:"bytes,1,rep,name=resources" json:"resources,omitempty"`
}

func (m *ListReply) Reset()                    { *m = ListReply{} }
func (m *ListReply) String() string            { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()               {}
func (*ListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListReply) GetResources() []*ResourceEntry {
	if m != nil {
		return m.Resources
	}
	return nil
}

type AddToTeamRequest struct {
	ResourceId       string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	OrganizationName string `protobuf:"bytes,2,opt,name=organization_name,json=organizationName" json:"organization_name,omitempty"`
	TeamName         string `protobuf:"bytes,3,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
}

func (m *AddToTeamRequest) Reset()                    { *m = AddToTeamRequest{} }
func (m *AddToTeamRequest) String() string            { return proto.CompactTextString(m) }
func (*AddToTeamRequest) ProtoMessage()               {}
func (*AddToTeamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddToTeamRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *AddToTeamRequest) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *AddToTeamRequest) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

type RemoveFromTeamRequest struct {
	ResourceId       string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	OrganizationName string `protobuf:"bytes,2,opt,name=organization_name,json=organizationName" json:"organization_name,omitempty"`
	TeamName         string `protobuf:"bytes,3,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
}

func (m *RemoveFromTeamRequest) Reset()                    { *m = RemoveFromTeamRequest{} }
func (m *RemoveFromTeamRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveFromTeamRequest) ProtoMessage()               {}
func (*RemoveFromTeamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RemoveFromTeamRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *RemoveFromTeamRequest) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *RemoveFromTeamRequest) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

type ChangePermissionLevelRequest struct {
	OrganizationName string                       `protobuf:"bytes,1,opt,name=organization_name,json=organizationName" json:"organization_name,omitempty"`
	TeamName         string                       `protobuf:"bytes,2,opt,name=team_name,json=teamName" json:"team_name,omitempty"`
	ResourceId       string                       `protobuf:"bytes,3,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	PermissionLevel  accounts.TeamPermissionLevel `protobuf:"varint,4,opt,name=permission_level,json=permissionLevel,enum=accounts.TeamPermissionLevel" json:"permission_level,omitempty"`
}

func (m *ChangePermissionLevelRequest) Reset()                    { *m = ChangePermissionLevelRequest{} }
func (m *ChangePermissionLevelRequest) String() string            { return proto.CompactTextString(m) }
func (*ChangePermissionLevelRequest) ProtoMessage()               {}
func (*ChangePermissionLevelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ChangePermissionLevelRequest) GetOrganizationName() string {
	if m != nil {
		return m.OrganizationName
	}
	return ""
}

func (m *ChangePermissionLevelRequest) GetTeamName() string {
	if m != nil {
		return m.TeamName
	}
	return ""
}

func (m *ChangePermissionLevelRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *ChangePermissionLevelRequest) GetPermissionLevel() accounts.TeamPermissionLevel {
	if m != nil {
		return m.PermissionLevel
	}
	return accounts.TeamPermissionLevel_TEAM_READ
}

func init() {
	proto.RegisterType((*ResourceEntry)(nil), "resource.ResourceEntry")
	proto.RegisterType((*ListRequest)(nil), "resource.ListRequest")
	proto.RegisterType((*ListReply)(nil), "resource.ListReply")
	proto.RegisterType((*AddToTeamRequest)(nil), "resource.AddToTeamRequest")
	proto.RegisterType((*RemoveFromTeamRequest)(nil), "resource.RemoveFromTeamRequest")
	proto.RegisterType((*ChangePermissionLevelRequest)(nil), "resource.ChangePermissionLevelRequest")
	proto.RegisterEnum("resource.ResourceType", ResourceType_name, ResourceType_value)
	proto.RegisterEnum("resource.Action", Action_name, Action_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Resource service

type ResourceClient interface {
	ResourceList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error)
	ResourceAddToTeam(ctx context.Context, in *AddToTeamRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	ResourceChangePermissionLevel(ctx context.Context, in *ChangePermissionLevelRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	ResourceRemoveFromTeam(ctx context.Context, in *RemoveFromTeamRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type resourceClient struct {
	cc *grpc.ClientConn
}

func NewResourceClient(cc *grpc.ClientConn) ResourceClient {
	return &resourceClient{cc}
}

func (c *resourceClient) ResourceList(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := grpc.Invoke(ctx, "/resource.Resource/ResourceList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) ResourceAddToTeam(ctx context.Context, in *AddToTeamRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/resource.Resource/ResourceAddToTeam", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) ResourceChangePermissionLevel(ctx context.Context, in *ChangePermissionLevelRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/resource.Resource/ResourceChangePermissionLevel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceClient) ResourceRemoveFromTeam(ctx context.Context, in *RemoveFromTeamRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/resource.Resource/ResourceRemoveFromTeam", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Resource service

type ResourceServer interface {
	ResourceList(context.Context, *ListRequest) (*ListReply, error)
	ResourceAddToTeam(context.Context, *AddToTeamRequest) (*google_protobuf.Empty, error)
	ResourceChangePermissionLevel(context.Context, *ChangePermissionLevelRequest) (*google_protobuf.Empty, error)
	ResourceRemoveFromTeam(context.Context, *RemoveFromTeamRequest) (*google_protobuf.Empty, error)
}

func RegisterResourceServer(s *grpc.Server, srv ResourceServer) {
	s.RegisterService(&_Resource_serviceDesc, srv)
}

func _Resource_ResourceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).ResourceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/ResourceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).ResourceList(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_ResourceAddToTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).ResourceAddToTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/ResourceAddToTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).ResourceAddToTeam(ctx, req.(*AddToTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_ResourceChangePermissionLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePermissionLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).ResourceChangePermissionLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/ResourceChangePermissionLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).ResourceChangePermissionLevel(ctx, req.(*ChangePermissionLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resource_ResourceRemoveFromTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFromTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServer).ResourceRemoveFromTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/resource.Resource/ResourceRemoveFromTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServer).ResourceRemoveFromTeam(ctx, req.(*RemoveFromTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Resource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "resource.Resource",
	HandlerType: (*ResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResourceList",
			Handler:    _Resource_ResourceList_Handler,
		},
		{
			MethodName: "ResourceAddToTeam",
			Handler:    _Resource_ResourceAddToTeam_Handler,
		},
		{
			MethodName: "ResourceChangePermissionLevel",
			Handler:    _Resource_ResourceChangePermissionLevel_Handler,
		},
		{
			MethodName: "ResourceRemoveFromTeam",
			Handler:    _Resource_ResourceRemoveFromTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/appcelerator/amp/api/rpc/resource/resource.proto",
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/resource/resource.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 717 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xc1, 0x6e, 0xda, 0x4a,
	0x14, 0x8d, 0x0d, 0x2f, 0x0a, 0x97, 0x07, 0x31, 0xf3, 0x04, 0x8f, 0xc7, 0x4b, 0x14, 0xe4, 0x45,
	0x8b, 0xa8, 0xc4, 0xa8, 0x44, 0x95, 0xaa, 0x76, 0xe5, 0x80, 0xdb, 0x44, 0x4d, 0x43, 0x32, 0x38,
	0xaa, 0x94, 0x0d, 0x9a, 0xc0, 0x94, 0x58, 0xc2, 0x9e, 0xa9, 0x6d, 0x52, 0x51, 0xc4, 0x26, 0xab,
	0xee, 0xfb, 0x09, 0xdd, 0xf5, 0x17, 0xfa, 0x19, 0xf9, 0x85, 0xae, 0xfb, 0x0d, 0x95, 0x8d, 0x6d,
	0x0c, 0x49, 0xd3, 0x2e, 0x5a, 0x75, 0x83, 0xc6, 0xe7, 0xde, 0xb9, 0xf7, 0x9c, 0xe1, 0xdc, 0x0b,
	0x4f, 0x87, 0xa6, 0x77, 0x31, 0x3e, 0x6f, 0xf4, 0xb9, 0x85, 0xa9, 0x10, 0x7d, 0x36, 0x62, 0x0e,
	0xf5, 0xb8, 0x83, 0xa9, 0x25, 0x30, 0x15, 0x26, 0x76, 0x44, 0x1f, 0x3b, 0xcc, 0xe5, 0x63, 0xa7,
	0xcf, 0xe2, 0x43, 0x43, 0x38, 0xdc, 0xe3, 0x68, 0x23, 0xfa, 0xae, 0x3c, 0xbe, 0xab, 0xcc, 0x80,
	0x7a, 0x14, 0xd3, 0x7e, 0x9f, 0x8f, 0x6d, 0xcf, 0x8d, 0x0f, 0xf3, 0x1a, 0x95, 0xdd, 0xc4, 0xcd,
	0x21, 0x1f, 0x51, 0x7b, 0x88, 0x83, 0xc0, 0xf9, 0xf8, 0x35, 0x16, 0xde, 0x44, 0x30, 0x17, 0x33,
	0x4b, 0x78, 0x93, 0xf9, 0x6f, 0x78, 0x69, 0x6b, 0xc8, 0xf9, 0x70, 0xc4, 0x02, 0x82, 0xd4, 0xb6,
	0xb9, 0x47, 0x3d, 0x93, 0xdb, 0x61, 0x49, 0xf5, 0xbd, 0x04, 0x39, 0x12, 0x32, 0xd3, 0x6d, 0xcf,
	0x99, 0xa0, 0x3c, 0xc8, 0xe6, 0xa0, 0x2c, 0x55, 0xa5, 0x5a, 0x86, 0xc8, 0xe6, 0x00, 0xd5, 0x21,
	0xed, 0x97, 0x2e, 0xcb, 0x55, 0xa9, 0x96, 0x6f, 0x96, 0x1a, 0xb1, 0xae, 0xe8, 0x9a, 0x31, 0x11,
	0x8c, 0x04, 0x39, 0x08, 0x41, 0xda, 0xa6, 0x16, 0x2b, 0xa7, 0x82, 0xdb, 0xc1, 0x19, 0xdd, 0x87,
	0xbf, 0xf8, 0x5b, 0x9b, 0x39, 0xe5, 0x74, 0x55, 0xaa, 0x65, 0x9b, 0x85, 0x46, 0x2c, 0x4a, 0x9b,
	0x1f, 0xc8, 0x3c, 0xae, 0xe6, 0x20, 0x7b, 0x68, 0xba, 0x1e, 0x61, 0x6f, 0xc6, 0xcc, 0xf5, 0xd4,
	0x3d, 0xc8, 0xcc, 0x3f, 0xc5, 0x68, 0x82, 0x1e, 0x41, 0x26, 0xea, 0xeb, 0x96, 0xa5, 0x6a, 0xaa,
	0x96, 0x6d, 0xfe, 0x7b, 0x93, 0x49, 0x20, 0x80, 0x2c, 0x32, 0xd5, 0x19, 0x28, 0xda, 0x60, 0x60,
	0x70, 0x83, 0x51, 0x2b, 0xac, 0x8b, 0x76, 0x20, 0x1b, 0x25, 0xf4, 0x62, 0xa1, 0x10, 0x41, 0x07,
	0x03, 0xf4, 0x00, 0x0a, 0xdc, 0x19, 0x52, 0xdb, 0x7c, 0x17, 0xbc, 0x54, 0x2f, 0x50, 0x24, 0x07,
	0x69, 0x4a, 0x32, 0x70, 0xe4, 0xab, 0xfb, 0x1f, 0x32, 0x1e, 0xa3, 0x56, 0x2f, 0x21, 0x7b, 0xc3,
	0x07, 0xfc, 0xa0, 0x7a, 0x25, 0x41, 0x91, 0x30, 0x8b, 0x5f, 0xb2, 0x67, 0x0e, 0xb7, 0xfe, 0x10,
	0x89, 0x6b, 0x09, 0xb6, 0x5a, 0x17, 0xd4, 0x1e, 0xb2, 0x63, 0xe6, 0x58, 0xa6, 0xeb, 0x9a, 0xdc,
	0x3e, 0x64, 0x97, 0x6c, 0x14, 0x71, 0xb9, 0xb5, 0x95, 0xf4, 0x33, 0xad, 0xe4, 0xe5, 0x56, 0xab,
	0xaa, 0x52, 0x37, 0x54, 0xed, 0x83, 0x22, 0x62, 0x12, 0xbd, 0x91, 0xcf, 0x22, 0xb0, 0x45, 0xbe,
	0xb9, 0xbd, 0xb0, 0x85, 0xff, 0x4e, 0xab, 0x54, 0x37, 0xc5, 0x32, 0x50, 0x9f, 0xc2, 0xdf, 0x49,
	0xff, 0x21, 0x04, 0x79, 0xa2, 0x77, 0x3b, 0xa7, 0xa4, 0xa5, 0xf7, 0xba, 0x86, 0xd6, 0x7a, 0xa1,
	0xac, 0xa1, 0x12, 0xa0, 0x18, 0x6b, 0x6b, 0xdd, 0xfd, 0xbd, 0x8e, 0x46, 0xda, 0x8a, 0x84, 0x0a,
	0x90, 0x8b, 0xf1, 0xd3, 0xae, 0x4e, 0x14, 0x19, 0xfd, 0x07, 0xc5, 0x18, 0xea, 0x90, 0xe7, 0xda,
	0xd1, 0xc1, 0x99, 0x66, 0x1c, 0x74, 0x8e, 0x94, 0xd4, 0x52, 0xb6, 0xa1, 0x6b, 0x2f, 0x95, 0x74,
	0x9d, 0xc0, 0xba, 0xd6, 0xf7, 0x9f, 0xc4, 0x0f, 0x6a, 0x2d, 0x3f, 0xb1, 0xd7, 0x22, 0xba, 0x66,
	0xe8, 0xca, 0x1a, 0xda, 0x84, 0x6c, 0x08, 0x11, 0x5d, 0x0b, 0xdb, 0x85, 0xc0, 0xe9, 0x71, 0xdb,
	0xcf, 0x91, 0x13, 0x50, 0x5b, 0x3f, 0xd4, 0x0d, 0x5d, 0x49, 0x35, 0xbf, 0xa6, 0x61, 0x23, 0x52,
	0x84, 0x4e, 0x16, 0xea, 0xfc, 0x19, 0x40, 0xc5, 0x85, 0xd7, 0x13, 0x23, 0x52, 0xf9, 0x67, 0x15,
	0x16, 0xa3, 0x89, 0x5a, 0xbc, 0xba, 0xfe, 0xf2, 0x41, 0xde, 0x44, 0x39, 0x7c, 0xf9, 0x30, 0x5e,
	0x42, 0x2e, 0xfa, 0x28, 0x41, 0x21, 0xaa, 0x19, 0xcf, 0x04, 0xaa, 0x2c, 0x2a, 0xac, 0x0e, 0x4a,
	0xa5, 0xd4, 0x98, 0x6f, 0x8e, 0x46, 0xb4, 0x63, 0x1a, 0xba, 0xbf, 0x56, 0xd4, 0xb3, 0xa0, 0x81,
	0xa1, 0x76, 0x96, 0x1a, 0xe0, 0x69, 0xe2, 0xaf, 0x9f, 0xe1, 0xa4, 0x71, 0x5c, 0x3c, 0xbd, 0x61,
	0xb0, 0x19, 0xf6, 0x5d, 0xe3, 0xe2, 0x69, 0xec, 0xa6, 0xd9, 0x13, 0xa9, 0x8e, 0x3e, 0x4b, 0xb0,
	0x1d, 0xb1, 0xbc, 0xd5, 0xb4, 0xe8, 0xde, 0x82, 0xf1, 0x5d, 0xae, 0xfe, 0x11, 0xfb, 0xca, 0xef,
	0x60, 0xff, 0x49, 0x82, 0x52, 0xc4, 0x7e, 0x79, 0xee, 0xd1, 0x4e, 0x72, 0x5b, 0xdd, 0xb2, 0x11,
	0xbe, 0xcb, 0xf7, 0x55, 0xc0, 0xf7, 0xa4, 0xfe, 0xab, 0xf9, 0x9e, 0xaf, 0x07, 0x8d, 0x76, 0xbf,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x96, 0x4e, 0x33, 0x30, 0xd6, 0x06, 0x00, 0x00,
}
