#!/bin/bash

echo $@

set -euo pipefail

# expected from makefile
export UG="${UG:-$(id -u):$(id -g)}"
export VERSION="${VERSION:-0.0.0}"
export BUILD="${BUILD:-$(git rev-parse HEAD | cut -c1-8)}"
export OWNER="${OWNER:-appcelerator}"
export REPO="${REPO:-github.com/$OWNER/amp}"

docker image list amptools | grep -q amptools || $(dirname $0)/image-for-local-user

AMPTOOLS=amptools
docker run -it --rm --name amptools \
    -u $UG \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $HOME/.ssh:/root/.ssh:ro \
    -v $PWD:/go/src/$REPO \
    -w /go/src/$REPO \
    -e VERSION=$VERSION \
    -e BUILD=$BUILD \
    -e OWNER=$OWNER \
    -e REPO=$REPO \
    $AMPTOOLS "$@"
