#!/bin/bash

echo $@

set -euo pipefail

# expected from makefile
export UG="${UG:-$(id -u):$(id -g)}"
export VERSION="${VERSION:-0.0.0}"
export BUILD="${BUILD:-$(git rev-parse HEAD | cut -c1-8)}"
export OWNER="${OWNER:-appcelerator}"
export REPO="${REPO:-github.com/$OWNER/amp}"

TOOLS=appcelerator/amptools:latest
LOCALTOOLS=amptools

tmpdir=$(mktemp -d)

# Map the host user id to the container user ("sudoer") so that the
# user has sudo permission in the container. This allows sudo access
# to Docker while able to save files in mounted volumes on the host
# with the correct owner (not root).
# Based on code thanks to @ndegory after brainstorming session about using sudo.
map_user() {
cat > $tmpdir/Dockerfile << EOF
FROM $TOOLS
RUN sed -i "s/sudoer:x:[0-9]*:[0-9]*/sudoer:x:$UG/" /etc/passwd
EOF
    docker build -t $LOCALTOOLS $tmpdir
}

docker image list amptools | grep -q amptools || map_user

docker run -it --rm --name amptools \
    -u $UG \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v $HOME/.ssh:/root/.ssh:ro \
    -v $PWD:/go/src/$REPO \
    -w /go/src/$REPO \
    -e VERSION=$VERSION \
    -e BUILD=$BUILD \
    -e OWNER=$OWNER \
    -e REPO=$REPO \
    $LOCALTOOLS "$@"

cleanup() {
  rm -rf $tmpdir
}

trap cleanup EXIT

