#!/usr/bin/env bash
# Build an alpine image
# usage: build4alpine REPO/FILENAME PKG-TO-BUILD [LDFLAGS]

DEST=$GOPATH/src/$1
PKG=$2
LDFLAGS="${3:-$LDFLAGS}"

GOOS=linux GOARCH=$GOARCH CGO_ENABLED=0 go build -a -ldflags "$LDFLAGS" -o $DEST $PKG
