#!/bin/bash

set -euo pipefail

APP=$1

# build variables (injected into binaries by linker -ldflags below)
VERSION="${VERSION:-1.0.0}"
BUILD="${BUILD:-$(git rev-parse HEAD | cut -c1-8)}"

OWNER=appcelerator
REPO=github.com/$OWNER/amp

GOOS=${GOOS:-$(uname | tr [:upper:] [:lower:])}
GOARCH=${GOARCH:-amd64}

DOCKER_RUN="docker run -t --rm"
GOTOOLS=appcelerator/gotools2:1.2.0

GO="$DOCKER_RUN --name go -v $HOME/.ssh:/root/.ssh:ro -v $GOPATH/bin:/go/bin -v $PWD:/go/src/$REPO -w /go/src/$REPO -e GOOS=$GOOS -e GOARCH=$GOARCH $GOTOOLS go"

CMDDIR=cmd

$GO build -ldflags "-X main.Version=$VERSION -X main.Build=$BUILD" $REPO/$CMDDIR/$APP
