#!/bin/bash

set -euo pipefail

APP=$1

# build variables (injected into binaries by linker -ldflags below)
VERSION="1.0.0"
BUILD=$(git rev-parse HEAD | cut -c1-8)

OWNER=appcelerator
REPO=github.com/$OWNER/amp

GOOS=$(uname | tr [:upper:] [:lower:])
GOARCH=amd64

DOCKER_RUN="docker run -t --rm"
GOTOOLS=appcelerator/gotools2

GO="$DOCKER_RUN --name go -v $HOME/.ssh:/root/.ssh -v $GOPATH/bin:/go/bin -v $PWD:/go/src/$REPO -w /go/src/$REPO -e GOOS=$GOOS -e GOARCH=$GOARCH $GOTOOLS go"

CMDDIR=cmd

$GO build -ldflags "-X main.Version=$VERSION -X main.Build=$BUILD" $REPO/$CMDDIR/$APP
