#!/usr/bin/env bash
# Build an alpine image
# usage: build4alpine REPO BINARY-NAME PKG-TO-BUILD [LDFLAGS]

DEST=$GOPATH/src/$1
NAME=$2
PKG=$3
LDFLAGS="${4:-$LDFLAGS}"

GOOS=linux GOARCH=$GOARCH CGO_ENABLED=0 go build \
  -a \
  -installsuffix alpine \
  -ldflags "$LDFLAGS" \
  -o $DEST/alpine/$GOARCH/$NAME $PKG

