#!/usr/bin/env bash

# this command
readonly CMD=$(basename $0)
readonly BOOTSTRAPDIR="$(dirname $0)/../bootstrap"

usage() {
  echo usage:  $CMD [-t timeout] [-i interval] clusterid
  exit 1
}

ok() {
  exit 0
}

error() {
  echo "$CMD: $1" >&2
  usage
}

main() {
  SECONDS=0
  [[ ! -x $1 ]] && error "$1 is not an executable"
  while true; do
    "$@" &> /dev/null
    [[ $? -eq 0 ]] && ok
    [[ "${TIMEOUT}" -eq 0 || "${SECONDS}" -gt "${TIMEOUT}" ]] && error "timed out"
    sleep "${INTERVAL}"
  done
}

# set options to default values
TIMEOUT=360
INTERVAL=2

while getopts 't:i:' opt; do
  case $opt in
    t) TIMEOUT=$OPTARG ;;
    i) INTERVAL=$OPTARG ;;
  esac
done
readonly TIMEOUT
readonly INTERVAL

# shift remaining options to the left and update positional params
# so expected command argument after the options have been processed is $1
# (OPTIND points to next param after options, but is 1-based, hence OPTIND-1)
shift $((OPTIND-1))

[[ -z "$1" ]] && usage
main $BOOTSTRAPDIR/bootstrap -s $1
