#!/usr/bin/env bash

usage() {
    echo "usage: ctrcheck NAME [FILTER] [TIMEOUT]"
    echo "example: ctrcheck foo running 60"
    exit 1
}

[[ $# -eq 0 ]] && usage

NAME="$1"

STATUS="${2:-running}"

# max script timeout, default = 300 seconds (5m)
TIMEOUT="${3:-300}"

SECONDS=0
while true; do
     name=$(docker ps --filter name="$NAME" --filter status="$STATUS" --format '{{ .Name }}' | wc -w)
     # if command fails, it's probably because the node is not up yet
     [[ $? -ne 0 ]] && [[ $SECONDS -lt $TIMEOUT ]] && continue
     [[ $name -eq $NAME ]] && exit 0
	 [[ $SECONDS -gt $TIMEOUT ]] && exit 1
done
