#!/bin/bash

usage() {
    echo "usage: curlcheck URL [STATUSCODE] [TIMEOUT] [INTERVAL]"
    echo "example: curlcheck docker.com 200 60 1"
    exit 1
}

[[ $# -eq 0 ]] && usage

# HTTP URL to curl
URL="$1"

# expected HTTP status code
CODE="${2:-200}"

# max script timeout, default = 3000 seconds (5m)
TIMEOUT="${3:-3000}"

# poll sleep interval, default = 1 second
INTERVAL="${4:-1}"

SECONDS=0
while true; do
	status=$(curl -L -s -o /dev/null -w '%{http_code}\n' "$URL")
	echo $status
	[[ $status -eq $CODE ]] && exit 0
	[[ $SECONDS -gt $TIMEOUT ]] && exit 1
	sleep $INTERVAL 
done

