#!/bin/bash

SUCCESS=0

CID=$1

# This script uses other scripts expected to be in the same directory
# This gets absolute path to script (resolving symlinks)
readonly SP="$(cd "$(dirname "$0")"; pwd -P)"

# commands
readonly bootstrap="$SP/../bootstrap/bootstrap"
readonly clustercheck="$SP/clustercheck"
readonly curlcheck="$SP/curlcheck"
readonly swarmcheck="$SP/swarmcheck"
readonly servicescheck="$SP/servicescheck"

checkexit() {
  [[ $1 -ne 0 ]] && printf "${@:2} (exit $1)\n" && exit $1
}

cleanup() {
  [[ SUCCESS -ne 1 && ! -z $CID ]] && echo "clean up" && $bootstrap -d $CID
}
trap cleanup EXIT

ok() {
  echo ok
}

pushimage() {
  echo "push image: $1/$2"
  docker tag $2 $1/$2
  checkexit $? "error tagging image"
  docker push $1/$2
  checkexit $? "error pushing image"
  ok
}

deploystack() {
  echo "deploy $1 => $2"
  docker run -it --rm --network=hostnet -v $(dirname $SP)/stacks:/stacks docker --host=m1 stack deploy -c /stacks/$1 $2
  checkexit $? "error deploying stack"
  ok
}

if [ -z $CID ]; then
  echo "bootstrapping cluster"
  CID=$($bootstrap -f)
  checkexit $? "bootstrap failed"
  echo $CID
else
  $bootstrap -s $CID
  if [ $? -ne 0 ]; then
    echo "bootstrapping cluster: $CID"
    $bootstrap -fi $CID
    checkexit $? "bootstrap failed"
    echo $CID
  fi
fi

echo "wait for cluster"
$clustercheck $CID
checkexit $? "cluster timed out"
ok

echo "wait for swarm mode"
$swarmcheck 300
checkexit $? "swarm mode timed out"
ok

echo "wait for registry"
$curlcheck localhost:5000/v2/ 200 10
checkexit $? "registry timed out"
ok

echo "push images to cluster"
pushimage localhost:5000 appcelerator/amplifier:local
pushimage localhost:5000 appcelerator/ampbeat:local
pushimage localhost:5000 appcelerator/agent:local

echo "deploy amplifier stack to cluster"
deploystack amplifier.stack.yml amplifier
echo "wait for all amplifier stack service replicas to be running"
$servicescheck 600
checkexit $? "amplifier service replica checks timed out"
ok

echo "deploy monitoring-core stack to cluster"
deploystack monitoring-core.stack.yml monitoring-core
maxwait=580
echo "wait for all monitoring-core service replicas to be running ($maxwait sec)"
$servicescheck $maxwait
checkexit $? "monitoring-core service replica checks timed out"
ok

echo "deploy monitoring-aux stack to cluster"
deploystack monitoring-aux.stack.yml monitoring-aux
echo "wait for all monitoring-aux service replicas to be running ($maxwait sec)"
$servicescheck $maxwait
checkexit $? "monitoring-aux service replica checks timed out"
ok

echo "deploy monitoring-agent stack to cluster"
deploystack monitoring-agent.stack.yml monitoring-agent
echo "wait for all monitoring-agent service replicas to be running ($maxwait sec)"
$servicescheck $maxwait
checkexit $? "monitoring-agent service replica checks timed out"
ok

# final sanity check
$servicescheck 0
checkexit $? "global service replica checks timed out"
ok
docker run -it --rm --network=hostnet docker --host=m1 service ls

SUCCESS=1

