#!/bin/bash

UG="${UG:-$(id -u):$(id -g)}"
AMPTOOLS=appcelerator/amptools:latest
LOCALAMPTOOLS=amptools

# build a temporary image with the image docker user remapped to the host user and group id
cat > Dockerfile.amptools << EOF
FROM $AMPTOOLS
RUN sed -i "s/sudoer:x:[0-9]*:[0-9]*/sudoer:x:$UG/" /etc/passwd
EOF
rc=0
docker build -f Dockerfile.amptools -t $LOCALAMPTOOLS .
if [ $? -ne 0 ]; then
 rc=1
fi
rm Dockerfile.amptools
exit $rc
