#!/bin/bash

usage() {
    echo "usage: swarmcheck [TIMEOUT]"
    echo "example: swarmcheck 120"
    exit 1
}

[[ $# -eq 0 ]] && usage

# max script timeout, default = 300 seconds (5m)
TIMEOUT="${1:-300}"

SECONDS=0
while true; do
    nc=$(docker node ls | awk '{ print $1 }' | wc -w)
    accepted=$(docker node ls --filter membership=accepted | awk '{ print $1 }' | wc -w)
    [[ $nc -eq $accepted ]] && exit 0
    [[ $SECONDS -gt $TIMEOUT ]] && exit 1
done
