#!/usr/bin/env bash

usage() {
    echo "usage: versioncheck [TIMEOUT]"
    echo "example: versioncheck 120"
    exit 1
}

[[ $# -eq 0 ]] && usage

AMP="amp --server localhost:50101"

# max script timeout, default = 300 seconds (5m)
TIMEOUT="${1:-300}"

SECONDS=0
while true; do
    $AMP version
    docker run -it --rm --network=hostnet -v $PWD/stacks:/stacks docker --host=m1 service ls
    echo "-------------------------------"
    # looking for the server information line
    output=$($AMP version | grep '^Server:')
    # try again if the text "not connected" appears
    [[ -n "$output" ]] && echo "$output" | grep -qv "not connected" && [[ $SECONDS -lt $TIMEOUT ]] && $AMP version && break
    [[ $SECONDS -gt $TIMEOUT ]] && echo "version check timed out" && exit 1
done
