#!/bin/bash

DEST=$GOPATH/src/$1
NAME=$2
PKG=$3
LDFLAGS=$4

# target => $GOOS $GOARCH
# see: https://golang.org/doc/install/source#environment
TARGETS=(
    alpine amd64
    darwin amd64
    linux amd64
    windows amd64
)

for ((i=0; i<"${#TARGETS[@]}"; $((i=$i+2)) )); do
  GOOS="${TARGETS[i]}"
  GOARCH="${TARGETS[i+1]}"
  OUTPUT=$DEST/$GOOS/$GOARCH/$NAME
  if [[ $GOOS = "windows" ]]; then OUTPUT=$OUTPUT".exe"; fi
  echo $OUTPUT
  if [[ $GOOS = "alpine" ]]; then
    # build alpine as a special case
    GOOS=linux GOARCH=$GOARCH CGO_ENABLED=0 go build -a -ldflags "$LDFLAGS" \
      -o $DEST/alpine/$GOARCH/$NAME $PKG
  else
    GOOS=$GOOS GOARCH=$GOARCH go build -ldflags "$LDFLAGS" -o $OUTPUT $PKG
  fi
done
