#!/bin/bash

DEST=$GOPATH/src/$1
NAME=$2
PKG=$3
LDFLAGS=$4

# target => $GOOS $GOARCH
# see: https://golang.org/doc/install/source#environment
TARGETS=(
    darwin amd64
    linux amd64
    windows amd64
)

for ((i=0; i<"${#TARGETS[@]}"; $((i=i+2)) )); do
  GOOS="${TARGETS[i]}"
  GOARCH="${TARGETS[i+1]}"
  OUTPUT="$DEST/$GOOS/$GOARCH/$NAME"
  [[ "$GOOS" = "windows" ]] && OUTPUT="${OUTPUT}.exe"
  echo "$OUTPUT"
  GOOS=$GOOS GOARCH=$GOARCH go build -ldflags "$LDFLAGS" -o "$OUTPUT" "$PKG"
done
