version: "3"
services:
    web:
        image: appcelerator/amp-demo-service
        deploy:
            mode: replicated
            replicas: 3
            labels:
            io.amp.mapping: "www:3000"
        environment:
            REDIS_PASSWORD: password
        networks:
            - public

    redis:
        image: redis
        environment:
            - PASSWORD=password
                 
networks:
    public:
        external:
            name: ampcore_public            

