version: "3"
services:
    pinger:
        image: appcelerator/pinger
        deploy:
            mode: replicated
            replicas: 1
            labels:
                hello: world
                foo: bar
