services:
  pinger:
    image: appcelerator/pinger
    replicas: 1
    networks:
      net-test11:
        aliases:
          - test2-pinger
networks:
  net-test11:
    driver: overlay
    ipam:
      driver: default
      config:
      - subnet: 10.16.238.0/24
        gateway: 10.16.238.1




