version: "3"

services:
    pinger:
        image: appcelerator/pinger
        deploy:
            mode: replicated
            replicas: 2
            labels:
                io.amp.mapping: "www:3000"
        networks:
        - public

networks:
    public:
        external:
            name: ampcore_public               


