---
- include: set-constants.yml
- include: upload-userdata.yml
- include: run-instance.yml
- include: wait-for-instance.yml
- include: snapshot-volume.yml
#- include: set-volumes.yml
- include: register-ami.yml
- include: copy-ami.yml
- include: terminate-instance.yml
