version: "2"
services:
  sut:
    image: appcelerator/sut
    build:
      context: ./sut
      dockerfile: Dockerfile

  telegraf:
    image: appcelerator/telegraf:telegraf-1.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    environment:
      OUTPUT_INFLUXDB_ENABLED: "true"
      INFLUXDB_URL: "http://influxdb:8086"
      INPUT_DOCKER_ENABLED: "true"

  influxdb:
    image: appcelerator/influxdb-amp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
      - "8083:8083"
