version: "3"

services:
    micro:
        image: 'registry.local.atomiq.io/micro'
        labels:
            io.amp.mapping: "www:3000"
        networks:
            - public

networks:
    public:
        external:
            name: ampcore_public