version: "2"
services:
  elasticsearch:
    image: appcelerator/elasticsearch-amp:latest
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: appcelerator/kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    build: .

  sut:
    image: appcelerator/sut
    build:
      context: ./sut
      dockerfile: Dockerfile
    depends_on:
      - kibana
      - elasticsearch
