version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  pinger:
    image: subfuzion/pinger:${TAG:-latest}
    networks:
      default:
        aliases:
          - pinger
    environment:
      SERVICE_PORTS: "3000"
      VIRTUAL_HOST: "https://pinger.*"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
