version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  pinger:
    image: appcelerator/pinger:${TAG:-latest}
    networks:
      default:
        aliases:
          - pinger
    environment:
      SERVICE_PORTS: "3000"
      VIRTUAL_HOST: "pinger.examples.*,https://pinger.examples.*"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.labels.amp.type.user == true]
