services:
    pinger:
        image: appcelerator/pinger
        deploy:
            labels:
                io.amp.mapping: "www:3000"
        networks:
            - public

networks:
    public:
        external:
            name: ampcore_public