version: "3"

networks:
  backend:
    driver: overlay
  public:
    external: true

services:
  go:
    image: htilford/go-redis-counter
    networks:
      - public
      - backend
    environment:
      SERVICE_PORTS: "80"
      VIRTUAL_HOST: "http://go.counter.examples*,https://go.counter.examples.*"
    deploy:
      replicas: 3
      placement:
        constraints: [node.labels.amp.type.user == true]

  redis:
    image: redis
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.amp.type.user == true]
