version: "3"
networks:
  default:
    external:
      name: ampnet
services:
  python:
    image: tutum/quickstart-python
    networks:
      - default
    environment:
      SERVICE_PORTS: "80"
      VIRTUAL_HOST: "http://python.*,https://python.*"
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
  go:
    image: htilford/go-redis-counter
    networks:
      - default
    environment:
      SERVICE_PORTS: "80"
      VIRTUAL_HOST: "http://go.*,https://go.*"
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
  redis:
    image: redis
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
