version: "3"

services:
    python:
        image: tutum/quickstart-python
        deploy:
            replicas: 3
            labels:
                 io.amp.mapping: "python:80"
        networks:
            - public

    go:
        image: htilford/go-redis-counter
        deploy:
            replicat: 3

    redis:
        image: redis

networks:
    public:
        external:
            name: ampcore_public    