version: "3.3"

networks:
  db:
    driver: overlay

configs:
  mongo_dbinit:
    external: true
  consul_kv:
    external: true

services:
  mongo-init:
    image: mongo:3.4.10
    networks:
      - db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.amp.type.user == true
      restart_policy:
        condition: none
    environment:
      MBAAS_MONGO_ADMIN_USERNAME: "appcadmin"
      MBAAS_MONGO_ADMIN_PASSWORD: "changeme"
      MBAAS_MONGO_PRODUCTS: "arrowdb dashboard"
      MBAAS_MONGO_ARROWDB_USERNAME: "appcelerator"
      MBAAS_MONGO_ARROWDB_PASSWORD: "changeme"
      MBAAS_MONGO_DASHBOARD_USERNAME: "appcelerator"
      MBAAS_MONGO_DASHBOARD_PASSWORD: "changeme"
    command:
      ["/usr/local/bin/mongo_dbinit.sh"]
    configs:
      - source: mongo_dbinit
        target: /usr/local/bin/mongo_dbinit.sh
        mode: 0554

  consul-init:
    image: consul:1.0.0
    networks:
      - db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.amp.type.user == true
      restart_policy:
        condition: none
    environment:
      CONSUL_HTTP_ADDR: "consul:8500"
    command:
      ["consul", "kv", "import", "@values.json"]
    configs:
      - source: consul_kv
        target: /values.json
        mode: 0554
