version: "3.3"

networks:
  public:
    external: true
  backend:
    driver: overlay

services:

  acs:
    image: services-registry.cloudapp-enterprise-preprod.appctest.com:5000/arrowcloud/arrowdb:1.6.0-sp2
    networks:
      - backend
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.amp.type.user == true
    environment:
      CONSUL: consul
      SERVICE_PORTS: 8082
      VIRTUAL_HOST: "https://acs.mbaas.*,acs.mbaas.*"
    entrypoint:
      - /usr/local/bin/start-arrowdb.sh
      - api
      - production

  dashboard:
    image: services-registry.cloudapp-enterprise-preprod.appctest.com:5000/arrowcloud/dashboard:1.6.0-sp2
    networks:
      - backend
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.amp.type.user == true
    environment:
      CONSUL: consul
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      SERVICE_PORTS: 9009
      VIRTUAL_HOST: "https://dashboard.mbaas.*,dashboard.mbaas.*"
    entrypoint:
      - /usr/local/bin/start-360-docker.sh
      - production
