version: "3.3"

networks:
  default:
    external:
      name: ampnet

services:

  acs:
    image: services-registry.cloudapp-enterprise-preprod.appctest.com:5000/arrowcloud/arrowdb:1.6.2
    networks:
      - default
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.amp.type.user == true
    environment:
      CONSUL: consul
      SERVICE_PORTS: 8082
      VIRTUAL_HOST: "https://acs.mbaas.*,acs.mbaas.*"
    entrypoint:
      - /usr/local/bin/start-arrowdb.sh
      - api
      - production
