version: "3.3"

networks:
  public:
    external: true
  monit:
    external: true
  backend:
    driver: overlay
  db:
    driver: overlay

volumes:
  mongo-primary-db:
  mongo-secondary-db:
  mongo-arbiter-db:
  consul-data:
  redis-data:

services:
  mongo-primary:
    image: mongo:3.4.10
    networks:
      - backend
      - db
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.amp.type.user == true
    #volumes:
      #- mongo-primary-db:/data/db
    environment:
      SERVICE_PORTS: 28017
      VIRTUAL_HOST: "mongo.mbaas.*,https://mongo.mbaas.*"
    command:
      ["--httpinterface", "--rest", "--replSet", "data"]

  mongo-secondary:
    image: mongo:3.4.10
    networks:
      - backend
      - db
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.amp.type.user == true
    #volumes:
      #- mongo-secondary-db:/data/db
    environment:
      SERVICE_PORTS: 28017
      VIRTUAL_HOST: "mongo.mbaas.*,https://mongo.mbaas.*"
    command:
      ["--httpinterface", "--rest", "--replSet", "data"]

  mongo-arbiter:
    image: mongo:3.4.10
    networks:
      - db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.amp.type.user == true
    #volumes:
      #- mongo-arbiter-db:/data/db
    command:
      ["--httpinterface", "--rest", "--replSet", "data"]

  mongo_exporter:
    image: eses/mongodb_exporter:latest
    networks:
      - db
      - monit
    environment:
      MONGODB_URI: "mongodb://mongo-primary:27017"
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.amp.type.user == true
      labels:
        io.amp.metrics.port: "9104"
        io.amp.metrics.mode: "exporter"

  consul:
    image: consul:1.0.0
    networks:
      - backend
      - db
      - public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.amp.type.user == true
    volumes:
      - consul-data:/consul/data
    environment:
      SERVICE_PORTS: 8500
      VIRTUAL_HOST: "https://consul.mbaas.*,consul.mbaas.*"

  consul_exporter:
    image: prom/consul-exporter:v0.3.0
    networks:
      - db
      - monit
    command:
      ["-consul.server=consul:8500"]
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.amp.type.user == true
      labels:
        io.amp.metrics.port: "9107"
        io.amp.metrics.mode: "exporter"

  redis:
    image: redis:alpine
    networks:
      - db
      - backend
    volumes:
      - redis-data:/data
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.amp.type.user == true

  redis_exporter:
    image: oliver006/redis_exporter:v0.13
    networks:
      - db
      - monit
    environment:
      REDIS_ADDR: "redis://redis:6379"
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.amp.type.user == true
      labels:
        io.amp.metrics.port: "9121"
        io.amp.metrics.mode: "exporter"
