version: "3"

networks:
  default:
    external:
      name: ampnet

volumes:
  ampagent:

services:

  amplifier:
    image: appcelerator/amplifier:local
    networks:
      default:
        aliases:
          - amplifier
    ports:
      - "50101:50101"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  agent:
    image: appcelerator/agent:local
    networks:
      default:
        aliases:
          - agent
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
    volumes:
      - ampagent:/containers
      - /var/run/docker.sock:/var/run/docker.sock

  haproxy:
    image: appcelerator/amphaproxy:1.0.0
    networks:
      - default
    ports:
      - "50180:80"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints: [node.role == manager]
    labels:
      io.amp.role: "infrastructure"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
