version: "3"

networks:
  default:
    external:
      name: ampnet
  infrastructure:

volumes:
  amp-etcd:

services:

  visualizer:
    image: manomarks/visualizer
    networks:
      - default
    ports:
      - "8080:8080/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer
    networks:
      - default
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  amplifier:
    image: appcelerator/amplifier:local
    networks:
      - default
      - infrastructure
    ports:
      - "50101:50101"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 3
      labels:
        io.amp.role: "amp.infrastructure"
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  etcd:
    image: appcelerator/etcd:3.1.5
    command:
      - "--listen-client-urls"
      - "http://0.0.0.0:2379"
      - "--advertise-client-urls"
      - "http://etcd:2379"
    networks:
      infrastructure:
        aliases:
          - "etcd"
    volumes:
      - amp-etcd:/data
    deploy:
      labels:
        io.amp.role: "amp.infrastructure"
      placement:
        constraints: [node.role == manager]
