version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  ampbeat:
    image: appcelerator/ampbeat:${TAG:-latest}
    networks:
      default:
        aliases:
          - ampbeat
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"

  kibana:
    image: appcelerator/kibana:5.3.1
    networks:
      default:
        aliases:
          - kibana
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.mapping: "kibana:5601"
    labels:
      io.amp.role: "infrastructure"
    environment: [
      "ELASTICSEARCH_URL=http://elasticsearch:9200",
      "SERVICE_PORTS=5601",
      "VIRTUAL_HOST=https://dashboard.*"
    ]
    ports:
      - "50106:5601"
