version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  elasticsearch:
    image: appcelerator/elasticsearch-amp:5.3.0
    networks:
      - default
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints: [node.role == worker]

  nats:
    image: appcelerator/amp-nats-streaming:v0.3.8
    networks:
      default:
        aliases:
          - nats
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints: [node.role == worker]

  etcd:
    image: appcelerator/etcd:3.1.6
    networks:
      default:
        aliases:
          - etcd
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 3
    command:
      - "--advertise-client-urls"
      - "http://etcd:2379"
    labels:
      io.amp.role: "infrastructure"
    deploy:
      mode: replicated
      replicas: 3
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints: [node.role == worker]

