version: "3"

networks:
  default:
    external:
      name: ampnet
  infrastructure:

services:

  visualizer:
    image: manomarks/visualizer
    networks:
      - default
    ports:
      - "50180:8080/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints: [node.role == manager]

  portainer:
    image: portainer/portainer
    networks:
      - default
    ports:
      - "50190:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
