version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  funchttp:
    image: appcelerator/funchttp:${TAG-latest}
    networks:
      default:
        aliases:
          - funchttp
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
    environment:
      - "SERVICE_PORTS=80"
      - "VIRTUAL_HOST=https://faas.*"

  funcexec:
    image: appcelerator/funcexec:${TAG-latest}
    networks:
      default:
        aliases:
          - funcexec
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
