version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  funchttp:
    image: appcelerator/funchttp:local
    networks:
      default:
        aliases:
          - funchttp
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.mapping: "funchttp:80"
    labels:
      io.amp.role: "infrastructure"
    ports:
      - "50102:80"

  funcexec:
    image: appcelerator/funcexec:local
    networks:
      default:
        aliases:
          - funcexec
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
