version: "3"

networks:
  default:
    external:
      name: ampnet
  infrastructure:

volumes:
  amp-beat:

services:

  elasticsearch:
    image: appcelerator/elasticsearch-amp:5.2.2
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
    networks:
      - default
      - infrastructure

  nats:
    image: appcelerator/amp-nats-streaming:v0.3.8
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
    networks:
      - default
      - infrastructure

  kibana:
    image: blacktop/kibana:5.2
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.mapping: "kibana:5601"
    labels:
      io.amp.role: "infrastructure"
    environment: [
      "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ]
    ports:
      - "5601:5601"
    networks:
      - default
      - infrastructure
    depends_on:
      - elasticsearch
