version: "3"

networks:
  default:
    external:
      name: ampnet
  infrastructure:

volumes:
  ampagent:

services:

  elasticsearch:
    image: appcelerator/elasticsearch-amp:5.3.0
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
    networks:
      - default
      - infrastructure

  nats:
    image: appcelerator/amp-nats-streaming:v0.3.8
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
    networks:
      - default
      - infrastructure
    ports:
      - "4222:4222"

  agent:
    image: appcelerator/amp-agent:local
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
    volumes:
      - ampagent:/containers
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - infrastructure
    depends_on:
      - nats

  ampbeat:
    image: appcelerator/ampbeat:local
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
    networks:
      - default
      - infrastructure
    depends_on:
      - nats
      - elasticsearch

  kibana:
    image: appcelerator/kibana:5.3.0
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.mapping: "kibana:5601"
    labels:
      io.amp.role: "infrastructure"
    environment: [
      "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ]
    ports:
      - "5601:5601"
    networks:
      - default
      - infrastructure
    depends_on:
      - elasticsearch
