version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  elasticsearch:
    image: appcelerator/elasticsearch-amp:5.3.0
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"

  nats:
    image: appcelerator/amp-nats-streaming:v0.3.8
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
    labels:
      io.amp.role: "infrastructure"
    ports:
      - "4222:4222"
