version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  pinger:
    image: subfuzion/pinger
    networks:
      default:
        aliases:
          - pinger
    ports:
      - "50105:3000"
    deploy:
      replicas: 3
      labels:
        io.amp.role: "pinger"
      restart_policy:
        condition: on-failure

