version: "3.1"

networks:
  default:
    external:
      name: ampnet

volumes:
  etcd-data:

services:

  etcd:
    image: appcelerator/etcd:3.1.10
    networks:
      default:
    volumes:
      - etcd-data:/data
    environment:
      SERVICE_NAME: "etcd"
      MIN_SEEDS_COUNT: 3
    command:
      - "--advertise-client-urls"
      - "http://etcd:2379"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "10s"
      amp.service.stabilize.timeout: "40s"
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: any
        delay: 5s
        window: 25s
      labels:
        io.amp.role: "infrastructure"
        io.amp.metrics.port: "2379"
      placement:
        constraints:
        - node.labels.amp.type.kv == true
