version: "3.1"

networks:
  default:
    external:
      name: ampnet

services:

  etcd:
    image: appcelerator/etcd:3.1.10
    networks:
      - default
    environment:
      ETCDCTL_API: 3
    command: ["sh", "-c", "etcdctl --endpoints http://${AMP_STACK:-amp}_etcd:2379 endpoint health | grep -qw healthy"]
    labels:
      io.amp.role: "infrastructure"
      io.amp.test:
      amp.service.stabilize.delay: "0s"
      amp.service.stabilize.timeout: "20s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.test:
      placement:
        constraints:
        - node.labels.amp.type.core == true
      restart_policy:
        condition: none
