version: "3.1"

networks:
  default:
    external:
      name: ampnet

services:

  nats:
    image: appcelerator/alpine:3.6.0
    networks:
      - default
    command: ["curl", "-sfm", "5", "${AMP_STACK:-amp}_nats:8222/subsz"]
    labels:
      io.amp.role: "infrastructure"
      io.amp.test:
      amp.service.stabilize.delay: "0s"
      amp.service.stabilize.timeout: "20s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.test:
      placement:
        constraints:
        - node.labels.amp.type.core == true
      restart_policy:
        condition: none
