version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  ampbeat:
    image: appcelerator/ampbeat:${TAG:-0.12.0}
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.core == true
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "20s"
