version: "3"

networks:
  default:
    external:
      name: ampnet

volumes:
  logstash-data:

services:

  logstash:
    image: appcelerator/amp-logstash:5.5.0
    networks:
      - default
    volumes:
      - logstash-data:/usr/share/logstash/data
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.core == true
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "20s"
