version: "3.1"

networks:
  default:
    external:
      name: ampnet

services:

  kibana:
    image: appcelerator/alpine:3.6.0
    networks:
      - default
    command: ["curl", "--retry", "3", "--retry-connrefused", "--retry-delay", "5", "-sfm", "5", "${AMP_STACK:-amp}_kibana:5601/app/kibana#/discover"]
    labels:
      io.amp.role: "infrastructure"
      io.amp.test:
      amp.service.stabilize.delay: "0s"
      amp.service.stabilize.timeout: "35s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.test:
      placement:
        constraints:
        - node.labels.amp.type.core == true
      restart_policy:
        condition: none
