version: "3"

networks:
  default:
    external:
      name: ampnet

services:

  kibana:
    image: appcelerator/kibana:5.5.0
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.mapping: "kibana:5601"
      placement:
        constraints:
        - node.labels.amp.type.core == true
      resources:
        limits:
          cpus: '1'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 200M
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "60s"
      amp.service.pull.timeout: "120s"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      SERVICE_PORTS: 5601
      VIRTUAL_HOST: "http://kibana.*,https://kibana.*"
