version: "3.1"

networks:
  default:
    external:
      name: ampnet

services:

  nats_exporter:
    image: appcelerator/alpine:3.6.0
    networks:
      - default
    command: ["curl", "-sf", "${AMP_STACK:-amp}_nats_exporter:7777/metrics"]
    labels:
      io.amp.role: "infrastructure"
      io.amp.test:
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
        io.amp.test:
      placement:
        constraints:
        - node.labels.amp.type.core == true
      restart_policy:
        condition: none
