version: "3.3"

networks:
  default:
    external:
      name: ampnet

volumes:
  prometheus-data:

configs:
  prometheus_alerts_rules:
    external: true

services:

  prometheus:
    image: appcelerator/amp-prometheus:${TAG:-0.15.0}
    networks:
      - default
    volumes:
      - prometheus-data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      SERVICE_PORTS: 9090
      VIRTUAL_HOST: "http://alerts.*,https://alerts.*"
    ports:
      - "9090:9090"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "45s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.metrics == true
      resources:
        limits:
          memory: 2G
        reservations:
          cpus: '0.10'
          memory: 500M
    configs:
      - source: prometheus_alerts_rules
        target: /etc/prometheus/alerts.rules
        mode: 0400
