version: "3.1"

networks:
  default:
    external:
      name: ampnet

volumes:
  grafana-data:

services:

  grafana:
    image: appcelerator/grafana-amp:1.2.4
    networks:
      - default
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      SERVICE_PORTS: 3000
      VIRTUAL_HOST: "http://dashboard.*,https://dashboard.*"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "10s"
      amp.service.stabilize.timeout: "30s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.metrics == true
