version: "3.1"

networks:
  default:
    external:
      name: ampnet

volumes:
  grafana-data:

services:

  grafana:
    image: appcelerator/grafana-amp:1.2.5
    networks:
      - default
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      SERVICE_PORTS: 3000
      VIRTUAL_HOST: "http://dashboard.*,https://dashboard.*"
    ports:
      - "3000:3000"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "8s"
      amp.service.stabilize.timeout: "60s"
      amp.service.pull.timeout: "120s"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.core == true
      resources:
        limits:
          cpus: '1'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 50M
