version: "3.1"

networks:
  default:
    external:
      name: ampnet

secrets:
  certificate_atomiq:
    external: true

services:

  proxy:
    image: dockercloud/haproxy
    networks:
      - default
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
      placement:
        constraints:
        - node.labels.amp.type.route == true
    environment:
      CERT_FOLDER: "/run/secrets"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "20s"
    ports:
      - "80:80"
      - "443:443"
      - "1936:1936"
    secrets:
      - source: certificate_atomiq
        target: cert0.pem
        mode: 0400
