version: "3.1"

networks:
  default:
    external:
      name: ampnet

secrets:
  amplifier_yml:
    external: true
  certificate_amp:
    external: true

services:

  amplifier:
    image: appcelerator/amplifier:${TAG:-0.14.1}
    networks:
      - default
    environment:
      REGISTRATION: ${REGISTRATION:-email}
      NOTIFICATIONS: ${NOTIFICATIONS:-true}
    ports:
      - "50101:50101"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "4s"
      amp.service.stabilize.timeout: "30s"
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
        io.amp.metrics.port: "5100"
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.labels.amp.type.api == true
    secrets:
      - source: amplifier_yml
        target: amplifier.yml
        mode: 0400
      - source: certificate_amp
        target: cert0.pem
        mode: 0400

