version: "3.1"

networks:
  default:
    external:
      name: ampnet

services:

  gateway:
    image: appcelerator/gateway:${TAG:-0.15.0}
    networks:
      - default
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "5s"
      amp.service.stabilize.timeout: "20s"
    environment:
      SERVICE_PORTS: 80
      VIRTUAL_HOST: "https://gw.*,http://gw.*"
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
      restart_policy:
        condition: on-failure
      placement:
        constraints:
        - node.labels.amp.type.core == true
      resources:
        limits:
          memory: 100M
        reservations:
          cpus: '0.05'
          memory: 20M
