version: "3.1"

networks:
  default:
    external:
      name: ampnet

volumes:
  ampagent:

services:

  agent:
    image: appcelerator/agent:${TAG:-0.15.0}
    networks:
      - default
    deploy:
      mode: global
      labels:
        io.amp.role: "infrastructure"
      resources:
        limits:
          cpus: '0.05'
          memory: 15M
    labels:
      io.amp.role: "infrastructure"
      amp.service.stabilize.delay: "3s"
      amp.service.stabilize.timeout: "20s"
    volumes:
      - ampagent:/containers
      - /var/run/docker.sock:/var/run/docker.sock
