- stack-create:
  cmd: amp stack up
  args:
     - "{{call .uniq `stack1`}}"
  options:
     - -f ../../../api/rpc/stack/test_samples/sample-04.yml
  expectation: stack-id

- stack-list:
  cmd: amp stack ls
  args:
    -
  options:
    -
  expectation: stack-list

- stack-stop:
  cmd: amp stack stop
  args:
    - "{{call .uniq `stack1`}}"
  options:
    -
  expectation: stack-id

- stack-list:
  cmd: amp stack ls
  args:
    -
  options:
    -
  expectation: stack-unavailable

- stack-restart:
  cmd: amp stack start
  args:
    - "{{call .uniq `stack1`}}"
  options:
    -
  expectation: stack-id

- stack-list:
  cmd: amp stack ls
  args:
    -
  options:
    -
  expectation: stack-list

- stack-stop:
  cmd: amp stack stop
  args:
    - "{{call .uniq `stack1`}}"
  options:
    -
  expectation: stack-id

- stack-remove:
  cmd: amp stack rm
  args:
    - "{{call .uniq `stack1`}}"
  options:
    -
  expectation: stack-id

- stack-list:
  cmd: amp stack ls
  args:
    -
  options:
    -
  expectation: stack-unavailable
