- stack-create:
  cmd: amp stack up
  args:
  options:
     - -f ../../../api/rpc/stack/test_samples/sample-04.yml
     - stack1
  expectation: ([a-z0-9]{64})

- stack-list:
  cmd: amp stack ls
  args:
  options:
  expectation: ((NAME)(\s)+(ID)(\s)+(STATE)((.)|(\s))+(stack1)(\s)+([a-z0-9]{64})(\s)+(Running)((.)|(\s))(.)*)

- stack-stop:
  cmd: amp stack stop
  args:
    - stack1
  options:
  expectation: ([a-z0-9]{64})

- stack-list:
  cmd: amp stack ls
  args:
  options:
  expectation: "No stack is available"

- stack-restart:
  cmd: amp stack start
  args:
    - stack1
  options:
  expectation: ([a-z0-9]{64})

- stack-list:
  cmd: amp stack ls
  args:
  options:
  expectation: ((NAME)(\s)+(ID)(\s)+(STATE)((.)|(\s))+(stack1)(\s)+([a-z0-9]{64})(\s)+(Running)((.)|(\s))(.)*)

- stack-stop:
  cmd: amp stack stop
  args:
    - stack1
  options:
  expectation: ([a-z0-9]{64})

- stack-remove:
  cmd: amp stack rm
  args:
    - stack1
  options:
  expectation: ([a-z0-9]{64})

- stack-list:
  cmd: amp stack ls
  args:
  options:
  expectation: "No stack is available"
