#!/bin/bash

set -e

amp="amp -s localhost"

rm -f ~/.config/amp/token

$amp user signup --name user --password password --email email@user.amp

$amp login --name user --password password
TOKEN=$(cat ~/.config/amp/token)

# no stacks yet
curl -k --header "Authorization: amp $TOKEN" https://gw.local.atomiq.io/v1/stacks | grep "{}"

# deploy a stack
$amp stack deploy -c "tests/gateway/pinger.yml" pinger

# TODO: need to use servicescheck or similar
sleep 15

# TODO: use jq
$ curl -k --header "Authorization: amp $TOKEN" https://gw.local.atomiq.io/v1/stacks | grep "{\"stacks\":"
#  {"stacks":[{"stack":{"id":"f48137d2c207f352","name":"pinger","owner":{"name":"qube"}},"service":"1"}]}

