// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/appcelerator/amp/api/rpc/logs/logs.proto

/*
Package logs is a generated protocol buffer package.

It is generated from these files:
	github.com/appcelerator/amp/api/rpc/logs/logs.proto

It has these top-level messages:
	LogEntry
	GetRequest
	GetReply
*/
package logs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogEntry struct {
	Timestamp          string            `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	ContainerId        string            `protobuf:"bytes,2,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ContainerName      string            `protobuf:"bytes,3,opt,name=container_name,json=containerName" json:"container_name,omitempty"`
	ContainerShortName string            `protobuf:"bytes,4,opt,name=container_short_name,json=containerShortName" json:"container_short_name,omitempty"`
	ContainerState     string            `protobuf:"bytes,5,opt,name=container_state,json=containerState" json:"container_state,omitempty"`
	ServiceName        string            `protobuf:"bytes,6,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	ServiceId          string            `protobuf:"bytes,7,opt,name=service_id,json=serviceId" json:"service_id,omitempty"`
	TaskId             string            `protobuf:"bytes,8,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	TaskSlot           int32             `protobuf:"varint,9,opt,name=task_slot,json=taskSlot" json:"task_slot,omitempty"`
	StackName          string            `protobuf:"bytes,10,opt,name=stack_name,json=stackName" json:"stack_name,omitempty"`
	StackId            string            `protobuf:"bytes,11,opt,name=stack_id,json=stackId" json:"stack_id,omitempty"`
	NodeId             string            `protobuf:"bytes,12,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	TimeId             string            `protobuf:"bytes,13,opt,name=time_id,json=timeId" json:"time_id,omitempty"`
	Labels             map[string]string `protobuf:"bytes,14,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Msg                string            `protobuf:"bytes,15,opt,name=msg" json:"msg,omitempty"`
	FromId             string            `protobuf:"bytes,16,opt,name=from_id,json=fromId" json:"from_id,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogEntry) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *LogEntry) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *LogEntry) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *LogEntry) GetContainerShortName() string {
	if m != nil {
		return m.ContainerShortName
	}
	return ""
}

func (m *LogEntry) GetContainerState() string {
	if m != nil {
		return m.ContainerState
	}
	return ""
}

func (m *LogEntry) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *LogEntry) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *LogEntry) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *LogEntry) GetTaskSlot() int32 {
	if m != nil {
		return m.TaskSlot
	}
	return 0
}

func (m *LogEntry) GetStackName() string {
	if m != nil {
		return m.StackName
	}
	return ""
}

func (m *LogEntry) GetStackId() string {
	if m != nil {
		return m.StackId
	}
	return ""
}

func (m *LogEntry) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *LogEntry) GetTimeId() string {
	if m != nil {
		return m.TimeId
	}
	return ""
}

func (m *LogEntry) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *LogEntry) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LogEntry) GetFromId() string {
	if m != nil {
		return m.FromId
	}
	return ""
}

type GetRequest struct {
	Container      string `protobuf:"bytes,1,opt,name=container" json:"container,omitempty"`
	Message        string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Node           string `protobuf:"bytes,3,opt,name=node" json:"node,omitempty"`
	Regexp         bool   `protobuf:"varint,4,opt,name=regexp" json:"regexp,omitempty"`
	Size           int32  `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	Service        string `protobuf:"bytes,6,opt,name=service" json:"service,omitempty"`
	Stack          string `protobuf:"bytes,7,opt,name=stack" json:"stack,omitempty"`
	Task           string `protobuf:"bytes,8,opt,name=task" json:"task,omitempty"`
	IncludeAmpLogs bool   `protobuf:"varint,9,opt,name=includeAmpLogs" json:"includeAmpLogs,omitempty"`
	Since          int32  `protobuf:"varint,10,opt,name=since" json:"since,omitempty"`
	From           string `protobuf:"bytes,11,opt,name=from" json:"from,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetRequest) GetContainer() string {
	if m != nil {
		return m.Container
	}
	return ""
}

func (m *GetRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetRequest) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *GetRequest) GetRegexp() bool {
	if m != nil {
		return m.Regexp
	}
	return false
}

func (m *GetRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *GetRequest) GetStack() string {
	if m != nil {
		return m.Stack
	}
	return ""
}

func (m *GetRequest) GetTask() string {
	if m != nil {
		return m.Task
	}
	return ""
}

func (m *GetRequest) GetIncludeAmpLogs() bool {
	if m != nil {
		return m.IncludeAmpLogs
	}
	return false
}

func (m *GetRequest) GetSince() int32 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *GetRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

type GetReply struct {
	Entries []*LogEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	Size    int32       `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Total   int32       `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
}

func (m *GetReply) Reset()                    { *m = GetReply{} }
func (m *GetReply) String() string            { return proto.CompactTextString(m) }
func (*GetReply) ProtoMessage()               {}
func (*GetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetReply) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *GetReply) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetReply) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*LogEntry)(nil), "logs.LogEntry")
	proto.RegisterType((*GetRequest)(nil), "logs.GetRequest")
	proto.RegisterType((*GetReply)(nil), "logs.GetReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Logs service

type LogsClient interface {
	LogsGet(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	LogsGetStream(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (Logs_LogsGetStreamClient, error)
}

type logsClient struct {
	cc *grpc.ClientConn
}

func NewLogsClient(cc *grpc.ClientConn) LogsClient {
	return &logsClient{cc}
}

func (c *logsClient) LogsGet(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := grpc.Invoke(ctx, "/logs.Logs/LogsGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsClient) LogsGetStream(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (Logs_LogsGetStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Logs_serviceDesc.Streams[0], c.cc, "/logs.Logs/LogsGetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &logsLogsGetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Logs_LogsGetStreamClient interface {
	Recv() (*LogEntry, error)
	grpc.ClientStream
}

type logsLogsGetStreamClient struct {
	grpc.ClientStream
}

func (x *logsLogsGetStreamClient) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Logs service

type LogsServer interface {
	LogsGet(context.Context, *GetRequest) (*GetReply, error)
	LogsGetStream(*GetRequest, Logs_LogsGetStreamServer) error
}

func RegisterLogsServer(s *grpc.Server, srv LogsServer) {
	s.RegisterService(&_Logs_serviceDesc, srv)
}

func _Logs_LogsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServer).LogsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logs.Logs/LogsGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServer).LogsGet(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logs_LogsGetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogsServer).LogsGetStream(m, &logsLogsGetStreamServer{stream})
}

type Logs_LogsGetStreamServer interface {
	Send(*LogEntry) error
	grpc.ServerStream
}

type logsLogsGetStreamServer struct {
	grpc.ServerStream
}

func (x *logsLogsGetStreamServer) Send(m *LogEntry) error {
	return x.ServerStream.SendMsg(m)
}

var _Logs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logs.Logs",
	HandlerType: (*LogsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogsGet",
			Handler:    _Logs_LogsGet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LogsGetStream",
			Handler:       _Logs_LogsGetStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/appcelerator/amp/api/rpc/logs/logs.proto",
}

func init() {
	proto.RegisterFile("github.com/appcelerator/amp/api/rpc/logs/logs.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 646 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x96, 0xd3, 0x38, 0x71, 0x26, 0x4d, 0x5a, 0xed, 0x1f, 0xfd, 0x98, 0x50, 0xa4, 0x62, 0x09,
	0x88, 0x7a, 0x88, 0x4b, 0x7b, 0x81, 0x9e, 0xe0, 0x80, 0xaa, 0x48, 0x15, 0x48, 0xce, 0x1d, 0xb4,
	0xb5, 0x17, 0x77, 0x55, 0xdb, 0x6b, 0xbc, 0x9b, 0x8a, 0x70, 0xe4, 0x15, 0x38, 0xc1, 0x2b, 0x71,
	0xe4, 0x15, 0x78, 0x10, 0x34, 0xb3, 0xeb, 0x24, 0x20, 0x71, 0x49, 0x66, 0xe6, 0xfb, 0xf6, 0xdb,
	0xd9, 0xf9, 0x46, 0x86, 0xf3, 0x5c, 0x9a, 0x9b, 0xd5, 0xf5, 0x3c, 0x55, 0x65, 0xcc, 0xeb, 0x3a,
	0x15, 0x85, 0x68, 0xb8, 0x51, 0x4d, 0xcc, 0xcb, 0x3a, 0xe6, 0xb5, 0x8c, 0x9b, 0x3a, 0x8d, 0x0b,
	0x95, 0x6b, 0xfa, 0x99, 0xd7, 0x8d, 0x32, 0x8a, 0x75, 0x31, 0x9e, 0x1e, 0xe5, 0x4a, 0xe5, 0x85,
	0x20, 0x16, 0xaf, 0x2a, 0x65, 0xb8, 0x91, 0xaa, 0x72, 0x9c, 0xe8, 0x47, 0x17, 0x82, 0x2b, 0x95,
	0xbf, 0xae, 0x4c, 0xb3, 0x66, 0x47, 0x30, 0x30, 0xb2, 0x14, 0xda, 0xf0, 0xb2, 0x0e, 0xbd, 0x63,
	0x6f, 0x36, 0x48, 0xb6, 0x05, 0xf6, 0x08, 0xf6, 0x53, 0x55, 0x19, 0x2e, 0x2b, 0xd1, 0xbc, 0x97,
	0x59, 0xd8, 0x21, 0xc2, 0x70, 0x53, 0x5b, 0x64, 0xec, 0x31, 0x8c, 0xb7, 0x94, 0x8a, 0x97, 0x22,
	0xdc, 0x23, 0xd2, 0x68, 0x53, 0x7d, 0xc3, 0x4b, 0xc1, 0x4e, 0x61, 0xb2, 0xa5, 0xe9, 0x1b, 0xd5,
	0x18, 0x4b, 0xee, 0x12, 0x99, 0x6d, 0xb0, 0x25, 0x42, 0x74, 0xe2, 0x29, 0x1c, 0xec, 0x9c, 0x30,
	0xdc, 0x88, 0xd0, 0x27, 0xf2, 0xf6, 0xbe, 0x25, 0x56, 0xb1, 0x49, 0x2d, 0x9a, 0x3b, 0x99, 0x0a,
	0x2b, 0xd9, 0xb3, 0x4d, 0xba, 0x1a, 0x69, 0x3d, 0x04, 0x68, 0x29, 0x32, 0x0b, 0xfb, 0xf6, 0x99,
	0xae, 0xb2, 0xc8, 0xd8, 0x3d, 0xe8, 0x1b, 0xae, 0x6f, 0x11, 0x0b, 0x08, 0xeb, 0x61, 0xba, 0xc8,
	0xd8, 0x03, 0x18, 0x10, 0xa0, 0x0b, 0x65, 0xc2, 0xc1, 0xb1, 0x37, 0xf3, 0x93, 0x00, 0x0b, 0xcb,
	0x42, 0x19, 0x12, 0x35, 0x3c, 0xbd, 0xb5, 0xb7, 0x82, 0x13, 0xc5, 0x0a, 0xdd, 0x79, 0x1f, 0x02,
	0x0b, 0xcb, 0x2c, 0x1c, 0x12, 0xd8, 0xa7, 0xdc, 0xde, 0x57, 0xa9, 0x8c, 0x7a, 0xd9, 0xb7, 0xf7,
	0x61, 0xea, 0x1a, 0x91, 0x25, 0x01, 0x23, 0xd7, 0x88, 0x2c, 0x11, 0x38, 0x83, 0x5e, 0xc1, 0xaf,
	0x45, 0xa1, 0xc3, 0xf1, 0xf1, 0xde, 0x6c, 0x78, 0x36, 0x9d, 0x93, 0xe9, 0xad, 0x8d, 0xf3, 0x2b,
	0x02, 0x29, 0x4e, 0x1c, 0x93, 0x1d, 0xc2, 0x5e, 0xa9, 0xf3, 0xf0, 0x80, 0x84, 0x30, 0x44, 0xf9,
	0x0f, 0x8d, 0x2a, 0x51, 0xfe, 0xd0, 0xca, 0x63, 0xba, 0xc8, 0xa6, 0x2f, 0x60, 0xb8, 0xa3, 0x80,
	0x27, 0x6f, 0xc5, 0xda, 0xad, 0x03, 0x86, 0x6c, 0x02, 0xfe, 0x1d, 0x2f, 0x56, 0xc2, 0x6d, 0x80,
	0x4d, 0x2e, 0x3a, 0xcf, 0xbd, 0xe8, 0x7b, 0x07, 0xe0, 0x52, 0x98, 0x44, 0x7c, 0x5c, 0x09, 0x6d,
	0x70, 0x9f, 0x36, 0xf6, 0xb4, 0xfb, 0xb4, 0x29, 0xb0, 0x10, 0xfa, 0xa5, 0xd0, 0x9a, 0xe7, 0xad,
	0x50, 0x9b, 0x32, 0x06, 0x5d, 0x9c, 0x81, 0x5b, 0x1e, 0x8a, 0xd9, 0xff, 0xd0, 0x6b, 0x44, 0x2e,
	0x3e, 0xd5, 0xb4, 0x25, 0x41, 0xe2, 0x32, 0xe4, 0x6a, 0xf9, 0xd9, 0xae, 0x83, 0x9f, 0x50, 0x8c,
	0xca, 0xce, 0x4f, 0xe7, 0x7f, 0x9b, 0x62, 0xeb, 0x34, 0x77, 0x67, 0xbb, 0x4d, 0x50, 0x03, 0x8d,
	0x74, 0x7e, 0x53, 0xcc, 0x9e, 0xc0, 0x58, 0x56, 0x69, 0xb1, 0xca, 0xc4, 0xab, 0xb2, 0xbe, 0x52,
	0xb9, 0x26, 0xcb, 0x83, 0xe4, 0xaf, 0x2a, 0x29, 0xca, 0x2a, 0xb5, 0x9e, 0xfb, 0x89, 0x4d, 0x50,
	0x11, 0xa7, 0xe9, 0xbc, 0xa6, 0x38, 0x7a, 0x07, 0x01, 0xcd, 0xa6, 0x2e, 0xd6, 0x6c, 0x06, 0x7d,
	0x51, 0x99, 0x46, 0x0a, 0x1d, 0x7a, 0xe4, 0xe1, 0xf8, 0x4f, 0x0f, 0x93, 0x16, 0xde, 0xbc, 0xaf,
	0xb3, 0xf3, 0xbe, 0x09, 0xf8, 0x46, 0x19, 0x5e, 0xd0, 0x80, 0xfc, 0xc4, 0x26, 0x67, 0xdf, 0x3c,
	0xe8, 0x52, 0x4b, 0x2f, 0xa1, 0x8f, 0xff, 0x97, 0xc2, 0xb0, 0x43, 0x2b, 0xbb, 0xf5, 0x64, 0x3a,
	0xde, 0xa9, 0xd4, 0xc5, 0x3a, 0xfa, 0xef, 0xcb, 0xcf, 0x5f, 0x5f, 0x3b, 0xa3, 0x28, 0x88, 0xef,
	0x9e, 0xd1, 0xc7, 0xe3, 0xc2, 0x3b, 0x61, 0x6f, 0x61, 0xe4, 0x14, 0x96, 0xa6, 0x11, 0xbc, 0xfc,
	0xb7, 0x4e, 0xdb, 0x70, 0x34, 0x25, 0x9d, 0x49, 0x74, 0xd0, 0xea, 0xc4, 0x9a, 0x8e, 0x5e, 0x78,
	0x27, 0xa7, 0xde, 0x75, 0x8f, 0xbe, 0x36, 0xe7, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xcc,
	0x37, 0x86, 0xc8, 0x04, 0x00, 0x00,
}
