#!/usr/bin/env bash

REPO=github.com/appcelerator/amp
PKG=$REPO/cmd/ampmake
DEST=$GOPATH/src/$REPO/bin

TARGETS=(
    darwin amd64
    linux amd64
    windows amd64
)

for ((i=0; i<"${#TARGETS[@]}"; $((i=$i+2)) )); do
  GOOS="${TARGETS[i]}"
  GOARCH="${TARGETS[i+1]}"
  OUTPUT=$DEST/$GOOS/$GOARCH/ampmake
  if [[ $GOOS = "windows" ]]; then OUTPUT=$OUTPUT".exe"; fi
  echo $OUTPUT
  GOOS=$GOOS GOARCH=$GOARCH go build -o $OUTPUT $PKG || exit $?
done
